### PR TITLE
Amending fixes from #2093

### PR DESCRIPTION
**Pull request by clebertsuconic**
Amending fixes from #2093

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@michaelandrepearce this is removing the version bumping check. I don't think we need it.


If we merge this PR, #2093 would be closed automatically by the apache bot.


let me know what you think

**Comment by michaelandrepearce** [comment]
Version check was because after the version its fixed client side.

**Comment by clebertsuconic** [comment]
The only change I saw on the client was a queueQuery done first... the server's change would still be compatible with older clients from what I saw.

If we really need a version check.. we would need a test showing where it breaks

**Comment by michaelandrepearce** [comment]
Thanks for sending pr to my private fork, looks fine and just cross wires / my misunderstanding of what you meant. Im happy,

**Comment by michaelandrepearce** [comment]
So as i said im away from a computer so i cant test it but as long as the test passes i added im happy.

**Comment by michaelandrepearce** [comment]
Eg +1 Im happy with what you have i think its all fine

**Comment by clebertsuconic** [comment]
#2093 is merged. .this is no longer needed.

**Pull request closed without merging**
