### PR TITLE
Revert "NO-JIRA Fix compiler warning in FederationStreamConnectMessage"

### PR DESCRIPTION
**Pull request by franz1981**
This reverts commit 9fe17d40

### CODE REVIEW

**Comment by franz1981** [comment]
Please don't merge it yet: we need to understand what's going on :)

**Comment by clebertsuconic** [comment]
I see lots of this when running the testsuite:


```
[Thread-3 (ActiveMQ-remoting-threads-ActiveMQServerImpl::serverUUID=3c528f5b-469b-11ea-a46e-e0d55e27b7f3-1090222535)] 10:39:03,467 WARN  [org.apache.activemq.artemis.core.server] AMQ222218: Server disconnecting: Error decoding buffer: java.lang.IllegalStateException: java.lang.IllegalStateException: Error. Unable to instantiate FederationPolicy: org.apache.activemq.artemis.core.config.federation.FederationAddressPolicyConfiguration.<init>(null)
	at org.apache.activemq.artemis.core.protocol.core.impl.RemotingConnectionImpl.bufferReceived(RemotingConnectionImpl.java:390) [:]
	at org.apache.activemq.artemis.core.remoting.server.impl.RemotingServiceImpl$DelegatingBufferHandler.bufferReceived(RemotingServiceImpl.java:654) [:]
	at org.apache.activemq.artemis.core.remoting.impl.invm.InVMConnection$1.run(InVMConnection.java:204) [:]
	at org.apache.activemq.artemis.utils.actors.OrderedExecutor.doTask(OrderedExecutor.java:42) [:]
	at org.apache.activemq.artemis.utils.actors.OrderedExecutor.doTask(OrderedExecutor.java:31) [:]
	at org.apache.activemq.artemis.utils.actors.ProcessorBase.executePendingTasks(ProcessorBase.java:66) [:]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_151]
	at org.apache.activemq.artemis.utils.ActiveMQThreadFactory$1.run(ActiveMQThreadFactory.java:118) [:2.12.0-SNAPSHOT]
Caused by: java.lang.IllegalStateException: Error. Unable to instantiate FederationPolicy: org.apache.activemq.artemis.core.config.federation.FederationAddressPolicyConfiguration.<init>(null)
	at org.apache.activemq.artemis.core.protocol.core.impl.wireformat.FederationStreamConnectMessage.getFederationPolicy(FederationStreamConnectMessage.java:153) [:]
	at org.apache.activemq.artemis.core.protocol.core.impl.wireformat.FederationStreamConnectMessage.decodeRest(FederationStreamConnectMessage.java:131) [:]
	at org.apache.activemq.artemis.core.protocol.core.impl.PacketImpl.decode(PacketImpl.java:364) [:]
	at org.apache.activemq.artemis.core.protocol.ServerPacketDecoder.slowPathDecode(ServerPacketDecoder.java:266) [:]
	at org.apache.activemq.artemis.core.protocol.ServerPacketDecoder.decode(ServerPacketDecoder.java:138) [:]
	at org.apache.activemq.artemis.core.protocol.core.impl.RemotingConnectionImpl.bufferReceived(RemotingConnectionImpl.java:377) [:]
	... 8 more
Caused by: java.lang.NoSuchMethodException: org.apache.activemq.artemis.core.config.federation.FederationAddressPolicyConfiguration.<init>(null)
	at java.lang.Class.getConstructor0(Class.java:3082) [rt.jar:1.8.0_151]
	at java.lang.Class.getConstructor(Class.java:1825) [rt.jar:1.8.0_151]
	at org.apache.activemq.artemis.core.protocol.core.impl.wireformat.FederationStreamConnectMessage.getFederationPolicy(FederationStreamConnectMessage.java:151) [:]
	... 13 more

```

**Comment by clebertsuconic** [comment]
@cshannon ??

**Comment by clebertsuconic** [comment]
I will go ahead and merge this based on the discussions at #2960

**Comment by cshannon** [comment]
@clebertsuconic - the reason the PR was opened was because of that error

**Comment by cshannon** [comment]
@clebertsuconic - Also as pointed out in the other discussion, simply changing it to Class<?>[] should fix the issue instead of Class<?>

**Comment by clebertsuconic** [comment]
@cshannon if you want to send a PR fixing...

I would kindly ask to wait someone run the whole testsuite before merging it though? send the PR but keep it under review until the testsuiste is ran.

**Comment by sebthom** [comment]
@clebertsuconic I created a new PR https://github.com/apache/activemq-artemis/pull/2969

**Pull request closed without merging**
