### PR TITLE
ARTEMIS-2508 Crititical analyser trigger shutdown if removeAllMessages

### PR DESCRIPTION
**Pull request by brusdev**
The crititical analyser trigger the broker shutdown if try to
removeAllMessages with a huge queue. The iterQueue is split so as
not to keep the lock too time.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@wy96f what about not use the page Executor for the delete?

The page executor was meant for cleanup and paging, not for deleting references on the queue.

**Comment by clebertsuconic** [comment]
I don't understand why we are using an executor now for removing? why not just remove the locks and keep the change simple?

**Comment by clebertsuconic** [comment]
hold a future waiting for the result has the same result as using the main thread anyway, right?

**Comment by brusdev** [comment]
I used the page Executor because the iteration on paged queue seemed like quite similar to depage. Now I see your points of views so I'll just remove the locks and I'll keep it in the caller thread.

**Comment by wy96f** [comment]
> @wy96f what about not use the page Executor for the delete?
> 
> The page executor was meant for cleanup and paging, not for deleting references on the queue.

Yes, that's what i thought :)

**Pull request closed without merging**
