### PR TITLE
ARTEMIS-2290 JMSBridgeImpl::stop is failing when called from FailureHandler

### PR DESCRIPTION
**Pull request by franz1981**

### CODE REVIEW

**Comment by franz1981** [comment]
I'm writing a test for it :+1:

**Comment by michaelandrepearce** [comment]
> I'm writing a test for it 

:)

**Comment by franz1981** [comment]
@clebertsuconic @michaelandrepearce I need to understand a thing first: I see that the bridge stop could happen from any thread (FailureHandler or any caller thread): JMSBridgeImpl::stop is supposed to wait a completed racing stop happening from another thread?

**Comment by michaelandrepearce** [comment]
@franz1981 i honestly dont know. We had some early issues with the jmsbridge so ended up where we needed to bridge different jms providers with a remote app made with spring integration.

**Comment by franz1981** [comment]
I understand this and I would say that logic and scalability of JMSBridge could be improved for sure (it uses 3 threads for bridge!!)...
Not sure I would do it in this PR to avoid introducing too many changes...

**Comment by franz1981** [comment]
I will add a test fo it in a separate PR: it seems not easy to be reproduced :+1:

**Pull request closed without merging**
