### PR TITLE
Enables Google's Error Prone and fixes some mistakes

### PR DESCRIPTION
**Pull request by thiagokronig**
Also, I can squash or drop any of the commits. Let me know how can I be helpful.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
Nice one!!!!
Will run some tests and merge it on monday

**Comment by clebertsuconic** [comment]
@thiagokronig  can I ask you a favor?  Can you send a test Pull Request with anything? just as a test?

It can't be me.. it has to be from someone who's not on the open list (and I'm one of the admins on the server)

I had created long ago a PR check build in one of our servers, and I used an user my server was configured with (HornetQBot). I had paused disabled the process but these messages are still happening.

I just deleted the jenkins project..

 I just wanted to make sure this HornetQBot message won't happen again.

**Comment by thiagokronig** [comment]
AFK here. If you can wait 1 hour, I'll send the null PR

**Comment by clebertsuconic** [comment]
@thiagokronig  any time before monday. I won't be doing much work over the weekend...

I just sent a message to dev-list explaining these HOrnetQBot messages... I'm chasing what's causing them.. I had removed the project and they still coming through.

**Comment by thiagokronig** [comment]
I sent the dummy PR. No HornetQBot messages received so far.

**Comment by clebertsuconic** [comment]
I will delay merging this until the release.. (I already have one of my own committs being delayed now)...

However I'm cherrying pick one of your committs (the URIFactory one)...

If you could please rebase after I merge #245

**Pull request closed without merging**
