### PR TITLE
[ARTEMIS-1666] List of prepared transaction details returns Object.toString() instead of Json string

### PR DESCRIPTION
**Pull request by yersan**
Issue: https://issues.apache.org/jira/browse/ARTEMIS-1666
JBEAP Issue: https://issues.jboss.org/browse/JBEAP-14177

### CODE REVIEW

**Comment by jbertram** [comment]
Typically issues like this would be fixed on the 'master' branch first and then back-ported to any other branches to avoid regressions.  Although the JMSServerManager is deprecated on 'master' I think this is still worth fixing there first and then back-porting it to the 1.x branch.

**Comment by jbertram** [comment]
If you don't want to do it let me know, and I'll do it.  No worries.

In any case, I think this PR should be closed.

**Comment by yersan** [comment]
@jbertram will it work for you if I create a new one PR on master branch and let this one open for 1.x?

**Comment by jbertram** [comment]
Ideally there would be a new PR on master and then a cherry-pick of that same commit onto 1.x (which would preclude this PR from staying open).

**Comment by yersan** [comment]
Ok, I'm going to close this one and create a new one for master and for 1.x (cherry-picked from master once it is merged)

**Comment by yersan** [comment]
@jbertram Note that there is no JMSServerControlTest test on master branch, but it exists on 1.x. This test can be used to cover this issue against regression, how do you usually deal with these cases? will it be fine if, when this issue is cherry picked for 1.x, we add a new commit including the test case into the PR over 1.x?

**Comment by jbertram** [comment]
So forget what I said before.  I'll merge this PR and then send a different one upstream to deal with this issue in a different way given the management objects have changed so substantially here.

**Comment by jbertram** [comment]
Although this has been merged the PR won't be closed automatically (something funny going on in the automation).  @yersan, please close this PR manually.

**Comment by yersan** [comment]
@jbertram Done, thanks!

**Pull request closed without merging**
