### PR TITLE
ARTEMIS-781 add journal record for address binding

### PR DESCRIPTION
**Pull request by jbertram**
This is just a first pass on the address journal record.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
PrintData and Export?

**Comment by clebertsuconic** [comment]
Ohhh... this is Artemis-781 branch. didn't realize that.

should we be doing PRs on it? or just commit straight? I was doing straight committs when I was working with Howard on OpenWire.

**Comment by jbertram** [comment]
I hadn't considered pushing directly, but that would certainly be faster.  I'll leave this to be merged and push others directly.

**Comment by mtaylor** [comment]
@jbertram just push direct for now, we'll tidy up when we merge onto master

**Comment by clebertsuconic** [comment]
@mtaylor One issue I had one merging from a parallel branch was giving proper authorship. I had rebased against master before.. and solving conflicts was a hell.. I had to squash everything and I just made a mention on the commit it was a group effort and the authors involved.


I would constantly squash by author and push -f, to make rebase easier later

**Pull request closed without merging**
