### PR TITLE
ARTEMIS-762 Reflect management changes in AMQP protocol

### PR DESCRIPTION
**Pull request by mtaylor**

### CODE REVIEW

**Comment by tabish121** [comment]
Was the commit of the log file intentional?

**Comment by mtaylor** [comment]
@tabish121 good catch

**Comment by mtaylor** [comment]
@tabish121 removed and added **/*.log to my gitignore :) cheers

**Comment by tabish121** [comment]
The tests seem to be using sleep calls to determine connection closed which is not the best given that it might close long before, or not depending on the speed of the machine, I'd recommend using the Wait class that was pulled over from 5.x where you can do a "Wait.waitFor(new Wait.Condition() { return ....} );"  that way you can avoid adding a bunch of extra time to the tests unnecessarily

**Comment by tabish121** [comment]
The remote close on the connection doesn't appear to provide any ErrorCondition to the remote to give it any indication of why it was closed which is less than ideal.  There's a couple different stock AMQP error conditions that could be used, in the case of the Queue being deleted you could for instance use the "amqp:resource-deleted" error to at least give the remote some hint to what happened.

**Comment by clebertsuconic** [comment]
@mtaylor  I have rebased the whole thing into my branch here:

https://github.com/clebertsuconic/activemq-artemis/tree/ARTEMIS-762


I was going to merge this, but I'm not sure about if this is ready to merge yet give @tabish121  comments. you want me to merge directly.. or you want to fetch my branch and rebase here?

**Comment by mtaylor** [comment]
@clebertsuconic please leave this I have made the changes locally, but need to modify the test client to handle disconnect errors.  Will update shortly.

**Comment by clebertsuconic** [comment]
@mtaylor is this ready now?

**Comment by mtaylor** [comment]
@clebertsuconic Yes this is ready to go.  Cheers

**Pull request closed without merging**
