### PR TITLE
ARTEMIS-2075 - allow Extra backups to try to replicate more than once

### PR DESCRIPTION
**Pull request by andytaylor**
https://issues.apache.org/jira/browse/ARTEMIS-2075

### CODE REVIEW

**Comment by andytaylor** [comment]
this will need cherry picking into 2.6.x as well

**Comment by andytaylor** [comment]
please retest this

**Comment by andytaylor** [comment]
retest this please

**Comment by clebertsuconic** [comment]
@andytaylor I have added a few questions to the JIRA, as the question is about the JIRA and not the PR itself.

**Pull request merged**
