### PR TITLE
ARTEMIS-898 - Adding documentation for Plugin support

### PR DESCRIPTION
**Pull request by cshannon**
Started a new chapter in the user manual for plugin support

### CODE REVIEW

**Comment by cshannon** [comment]
@clebertsuconic - I added basic documentation for the plugin feature here but I think for next release it would also be good to add to the existing examples with a sample plugin to show how it can be used.

**Comment by clebertsuconic** [comment]
did you think about using ServiceLocator?

**Comment by cshannon** [comment]
No, what do you mean?

**Comment by clebertsuconic** [comment]
Like how we load the ProtocolManagers...

Each jar defines a org.apache.activemq.artemis.spi.core.protocol.ProtocolManagerFactory file


Then on RemotingServiceImpl::

```
   private void resolveProtocols(ClassLoader loader) {
      ServiceLoader<ProtocolManagerFactory> serviceLoader = ServiceLoader.load(ProtocolManagerFactory.class, loader);
      loadProtocolManagerFactories(serviceLoader);
   }

   /**
    * Loads the protocols found into a map.
    *
    * @param protocolManagerFactoryCollection
    */
   private void loadProtocolManagerFactories(Iterable<ProtocolManagerFactory> protocolManagerFactoryCollection) {
      for (ProtocolManagerFactory next : protocolManagerFactoryCollection) {
         MessagePersister.registerProtocol(next);
         String[] protocols = next.getProtocols();
         for (String protocol : protocols) {
            ActiveMQServerLogger.LOGGER.addingProtocolSupport(protocol, next.getModuleName());
            protocolMap.put(protocol, next);
         }
      }
   }
```


Perhaps we could instruct users to do something similar. Just having this definition done.


We would have to provide a XML property to resolve plugins, being defaulted to false if we did this.

**Comment by cshannon** [comment]
I would say that the ServiceLoader stuff makes more sense for internal things like the protocol manager.  I think a lot of users would want to have more explicit control over registering plugins.  Being able to just call off the configuration api seems easier and a user can add plugins anyway they want and in any jar they want as long as it is on the classpath.

**Comment by mattrpav** [comment]
I'd suggest that ServiceLocator support would be handy for plugins; however, it would require another layer of convention as plugin writers would have to know to build their plugins with conservative defaults, or disable themselves unless specifically configured.

**Comment by michaelandrepearce** [comment]
Could I suggest this feature goes to 2..1.1 release rather than holding up 2.1.0 tag? If there's still design and implementation details being fleshed out.?

**Comment by cshannon** [comment]
Yeah I wouldn't put it into 2.1.0 at this point.  If it gets added it would be a future release.  There are issues to work out with using the ServiceLocator support such as how to specify plugin order, disabling plugins, etc.

**Pull request closed without merging**
