### PR TITLE
ARTEMIS-1242 OpenWire Transactions never removed

### PR DESCRIPTION
**Pull request by gaohoward**
Openwire doesn't remove the finished transactions
(committed or rolledback).

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
LGTM

**Comment by andytaylor** [comment]
LGTM is a new one to me, had to google it :)

**Comment by andytaylor** [comment]
Howard, Im not sure but if the commit or rollback fails then you need to add back the tx is some cases, for instance if you try to commit a suspended tx. take a look at what serversessionimpl does

**Comment by gaohoward** [comment]
@andytaylor done. added 2 more tests to make sure it works as expected.

**Pull request closed without merging**
