### PR TITLE
Added npm shrinkwrap file

### PR DESCRIPTION
**Pull request by paulgallagher75**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
why do we need that?

**Comment by paulgallagher75** [comment]
Instructions for regenerating the shrinkwrap file -

After altering the package.json and changing version

1. have npm in path
2. cd activemq-artemis/artemis-website
3. npm cache clean; rm -rf ./node_modules/ ./node npm-shrinkwrap.json
4. npm install --save-dev
5. npm shrinkwrap --dev

the new npm-shrinkwrap.json should be written

**Comment by clebertsuconic** [comment]
Can you add some information on the hacking guide? in specific how to upgrade the gitbook and generate this file?

**Comment by paulgallagher75** [comment]
Have update the hacking guide now

**Pull request merged**
