### PR TITLE
ARTEMIS-1335 Update Netty to 4.1.14 - MQTT fix

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Fix for MQTT in connect due to deprecated methods bug causing NPE, call new methods and null check ourselves.

Also raised https://github.com/netty/netty/issues/7076 upstream but i guess we will keep this, as the old methods are deprecated anyhow.

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
@clebertsuconic @mtaylor found the problem in MQTT when upgrade of Netty and fixed it, and sorted it. If you could merge/validate.

**Comment by michaelandrepearce** [comment]
build box still has perm issue.

**Comment by mtaylor** [comment]
@michaelandrepearce Thanks for this.  I actually raised the String usage for the APIs with the Netty guys.  That was a couple versions ago, looks like we got caught out during the upgrade.  Cheers.

**Comment by michaelandrepearce** [comment]
@mtaylor it would have been fine if weren't for a bug in their code change to keep the deprecated method. Would have been easier to spot if they just removed the method because then would have been compile time. Hey ho. We're now using the new methods :) and we save a byte[] to string to byte[] skip and a jump now so that's good.

**Pull request closed without merging**
