### PR TITLE
ARTEMIS-1596 STOMP consumer/producer auto-creates address with wrong routing-type

### PR DESCRIPTION
**Pull request by jostbg**

### CODE REVIEW

**Comment by jbertram** [comment]
You should squash these commits together into a single commit and also add a test to reproduce the failure and verify the fix.

**Comment by jostbg** [comment]
@jbertram before I do so, I got one question. The original code was a bit unclear so I did some guessing, but should the queue only auto-created when the "address" routing type is not MULTICAST or always, i.e. is this assumption correct: https://github.com/apache/activemq-artemis/pull/1766/commits/3d0680e351db6cac65d087f33326405860961507#diff-2be6e6baef830595c16a9daa3d951615R283

**Comment by jbertram** [comment]
Your assumption is correct.  Do not auto-create the queue if the routing-type is MULTICAST.

**Comment by jostbg** [comment]
Done.

**Pull request closed without merging**
