### PR TITLE
ARTEMIS-1623  ActiveMQServerPlugin impl for logging various broker events

### PR DESCRIPTION
**Pull request by pgfox**
Similar concept to the ActiveMQ 5.x loggingBrokerPlugin.
Commit includes:
- plugin impl
- tests using byteman for checking logging with AMQP, CORE and Openwire
- doc on how to configure plugin 

For configuration details please see broker-plugins.md

### CODE REVIEW

**Comment by pgfox** [comment]
@jbertram , @michaelandrepearce  Thanks for reviewing this PR. I will try to implement all the above suggestions. 

on the DEBUG vs. INFO I will make it clearer in the docs; there is a before/after on most of the plugin events . For INFO I log a slightly reduced log in the "after" point. For DEBUG I log a more detailed entry before and after. 

I will try to follow the established pattern for the LOG codes; create an interface LoggingActiveMQServerPluginLogger that extends the BasicLogger.  It there any restriction on the 2 digit Logger Code I use - I think "83" is the last number currently used so I guess "84" would be ok? Or is there a pattern to choosing that value?

**Comment by michaelandrepearce** [comment]
@pgfox sounds good/sensible to me, unless anyone says otherwise I would have chosen the same.

**Comment by michaelandrepearce** [comment]
Did this get merged? I’m not sure it was ready I was expecting some changes from @pgfox

**Comment by pgfox** [comment]
I still had to do the suggested changes we discussed :( 

Sorry I did not think the would be merged yet. I hope to get those changes pushed to the PR in the next day or so.

**Comment by pgfox** [comment]
@clebertsuconic  
There was some outstanding improvements suggested by @jbertram @michaelandrepearce  (above) on this PR that I have not finish yet. 

Can I just open a new PR for those improvement when I have them completed? I should have them done in the next day or so. Sorry, for any confusion this has caused.

**Comment by clebertsuconic** [comment]
@pgfox I had missed there were still pending things.. I read it wrongly.
Can you send another PR? or should I revert and you sending it again?

**Comment by pgfox** [comment]
@clebertsuconic no problem Clebert. I will create a new PR when I have those pending things completed.

**Pull request closed without merging**
