### PR TITLE
ARTEMIS-5201 when non embedded use exit(1) on exception for artemis c…

### PR DESCRIPTION
**Pull request by gtully**
…li main like artemis boot

### CODE REVIEW

**Review by brusdev — APPROVED** [review]
Full test-suite and example passed

**Comment by brusdev** [comment]
Ignore my previous comment, I'm still executing the full test-suite and examples for this PR.

**Comment by clebertsuconic** [comment]
@gtully what exception were you having that led you to make this change?

**Comment by brusdev** [comment]
Execution of full test-suite and examples completed and successful!

**Comment by gtully** [comment]
> @gtully what exception were you having that led you to make this change?

They were security related, but all are ignored in the main method. I am using the Artemis cli main directly and need a jvm exit code on error

**Pull request merged**
