### PR TITLE
ARTEMIS-786 Store user's password in hash form by default

### PR DESCRIPTION
**Pull request by gaohoward**
- passwords stored using PBKDF2 algothrim
- implements cli user command to help create and manage user/roles

### CODE REVIEW

**Comment by clebertsuconic** [comment]
looks nice...

Let me run the whole testsuite before merging though.. I want also to run the examples. Have you done it?


I'm a bit concerned with the examples as this will touch configurations.

**Comment by clebertsuconic** [comment]
@jbertram I will let you handle it then...
please run the whole testsuite, including examples?

**Comment by jbertram** [comment]
There are other places in the configuration where passwords can be masked (e.g. using org.apache.activemq.artemis.utils.PasswordMaskingUtil).  It would be ideal to have a unified approach to all password masking/hashing if possible.  Otherwise we will need to support multiple commands for masking/hashing.  For what it's worth, 5.x uses an encryption/decryption scheme using Jasypt which is pretty simple and effective.

**Comment by gaohoward** [comment]
Good point. I was aware of this but didn't think it clearly. We can introduce Jasypt to replace current encrypt/decript util for 2 ways, but I'm not sure this 2-way is suitable for this, which is the only place where hashing seems the preferred way (other places for password need a 2-way algorithm because the broker needs to decrypt them at runtime). I'll talk to you before I do any changes.

**Comment by gaohoward** [comment]
@jbertram I move the hash factory api into the same PasswordMaskingUtil to reduce confusion, so that both 2-way encryption and one-way hashing APIs are in the same util class. But I'm not sure what's the benefit of bring in Jasypt. The PasswordMaskingUtil provides a general API which enables user to use customized password encoder/decoder like Jasypt, if he really want it. What do you think?

**Comment by gaohoward** [comment]
hmm, sth wrong with Jenkins I think. My local run is ok.

**Comment by jbertram** [comment]
The whole masking/hashing process still seems like a bit of a jumble to me.  To mask a password there's a raw Java command (e.g. "java -cp &lt;classPath> org.apache.activemq.artemis.utils.DefaultSensitiveStringCodec &lt;password-to-encode>") and then there's a new command you've added to hash a password.  I think it would provide a much better user experience to unify both, if possible.

**Comment by gaohoward** [comment]
ok, let me think about it. Thanks.

**Comment by gaohoward** [comment]
@jbertram So I did some refactoring:

* Now DefaultSensitiveStringCodec supports 2 kinds of masking
  one-way hashing and two-way encoding/decoding
* one-way hashing is used by cli and PropertiesLoginModule, it also has
  a verify method to help checking passwords
* two-way is used by other password masking in artemis. (existing feature)
* Other utils like HashProcessor doesn't do hashing or encoding.
  They are used to facilitate password management (either plaintext or
  hashed).
* Cli commands is used for user management and manual changing is not needed
  (although user can use raw DefaultSensitiveStringCodec to to it).

**Comment by jbertram** [comment]
Is there a command to generate an encoded password so that you can put that into your configuration?  I didn't see anything related to that.

**Comment by gaohoward** [comment]
There is a command AddUser which takes a user name and password and put them in the config (you can choose plaintext or hash to store the password).

**Comment by jbertram** [comment]
Right, but isn't that the one-way hash that goes into a properties file for the PropertiesLoginModule?

**Comment by jbertram** [comment]
I'm talking about a command to *encode* a password to put into the broker.xml (e.g. for clusterpassword).

**Comment by gaohoward** [comment]
yes, the old "java -cp <classPath> org.apache.activemq.artemis.utils.DefaultSensitiveStringCodec <password-to-encode>" still works as before.

**Comment by jbertram** [comment]
I think having a command in the CLI to do that would be ideal, similar to what we have for one-way hashing.

**Comment by gaohoward** [comment]
good idea. If you mean just doing the masking that could be done easily. If you mean also update the broker.xml with the command, I think it'll need some thinking and should be done in a separate JIRA. what do you think?

**Comment by jbertram** [comment]
Just doing the masking and spitting it std-out is fine with me.  Will be simple to cut/paste from there.

**Comment by gaohoward** [comment]
ok got it. I'll add a command for that, maybe with options allowing user to do one-way hashing or 2way masking. Thanks.

**Comment by gaohoward** [comment]
@jbertram I added the command, pls take a look.

**Comment by clebertsuconic** [comment]
@jbertram is this ready to be merged? I should release this week (I'm a week late already). and this seems a nice feature.

**Pull request closed without merging**
