### PR TITLE
Allow configurable size for client global pools

### PR DESCRIPTION
**Pull request by mtaylor**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
Why don't you do this. Instantiate the global pool on ActiveMQClient... and have the ServerLocator to get the instance from the ActiveMQClient when the pool changed.

you would create a method ActiveMQClient.setThreadPool(Executors....) and all the ServerLocator would do is to get it from there.

**Comment by mtaylor** [comment]
Injecting the globalPool is the same as injecting the local pool on each ServerLocator...  I can also add the ability to inject a global pool on the ActiveMQClient to make it simpler?  The current API manages thread pools at the server locator level.  e.g. setThreadPoolMaxSize(final int threadPoolMaxSize), I've extended that to allow a local pool to be injected also.  The next step for me was to use this pool injection in the RA.  Changing the global pool imo adds more complexity... what happens when the globalThreadPool is changed after a client is already initialized?

**Comment by clebertsuconic** [comment]
>>  what happens when the globalThreadPool is changed after a client is already initialized?

nothing.. or if you want to you could throw an exception after the pool has been utilized.

**Comment by mtaylor** [comment]
OK I can add this as well

**Comment by clebertsuconic** [comment]
I don't really mind about injecting the pool on Serverlocator if not the global. All we need it a global Thread pool.


It will be a non used feature IMO.

**Comment by clebertsuconic** [comment]
also it will be hard to throw an error.. (how to do it on the testsuite?) 

I would just reinit the pool. and let old clients keep the pool where they got it from.

**Comment by mtaylor** [comment]
ok

**Comment by clebertsuconic** [comment]
This is broken, the pool is rejecting tasks beyond the max. We need to use a BlockingQueue, but that will also require coreSize==maxSize. it's basically a fixedCachePoolSize, which is what we need.

**Comment by clebertsuconic** [comment]
@mtaylor This will have my proposed changes into this:
https://github.com/apache/activemq-artemis/commit/334cbebc13197d65b7f9acf65d62d0c5d6f6cbef


I don't know yet what to do with the core-pool-size.. it seems moot with the concept of letting runnables to be queued. this becomes simply a fixed-sized thread pool executors, but this is exactly what we need.

**Pull request closed without merging**
