### PR TITLE
ARTEMIS-1270 Management Console - Hawtio Solution

### PR DESCRIPTION
**Pull request by michaelandrepearce**
WIP - Just for review

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
@clebertsuconic see i make two commits, one for my work solely (aka setting up and also the activemq brand plugin) and then another for the artemis-plugin noting Andy T as author, to give correct authorship acknowledgement.

**Comment by michaelandrepearce** [comment]
re mail thread bits, addressed:
point 1) - url path changed from /hawtio/ to /console/
point 8) fuse properties renamed.

**Comment by michaelandrepearce** [comment]
addressed:
3) simply removed the feature/tab (isn't required)
4) dashboard is now just a jvm default (no camel)
5) simply removed 
9) war is now slimmed down to: 14.7mb, almost same size as acitvemq 5's

**Comment by clebertsuconic** [comment]
just one request here.. don't leave master on an intermediate state this week.. I want to release before end of this week / early next week as I sent the heads up earlier. 

We can merge this now if we're sure it's ready.. otherwise lets wait till next week.

**Comment by michaelandrepearce** [comment]
Oh don't merge yet!

**Comment by michaelandrepearce** [comment]
As PR states is WIP , is just to give visibility to all

**Comment by michaelandrepearce** [comment]
3) section overlaid with references to other products removed.
6) with the reduction of the war and removal of features, this seems to no longer be generated
2) about page now fully customised with wording coming from https://activemq.apache.org/artemis/, a small powered by is also added, as well as version section now including artemis version

**Comment by michaelandrepearce** [comment]
7 - custom help, with iframe loading the artemis docs (note would be nicer if we had an alias on the web for https://activemq.apache.org/artemis/docs/LATEST so we don't have to code in the link version)

**Comment by michaelandrepearce** [comment]
@clebertsuconic i think I've address'ed now 1-9 on the list Dan gave. Only bit left is adding/updating artemis LICENSE/NOTICE. 

Whats the process on this.

Is it manual or is it automated, who needs to verify it?

After this the only last bit is aligning up the login (so don't have to bypass)

**Comment by michaelandrepearce** [comment]
Update on 7) made it use the local user-guide available.

**Comment by michaelandrepearce** [comment]
here is list of packaged code/content/jars etc, and their licenses


commons-codec-1.10.jar,ASL
commons-fileupload-1.3.2.jar,ASL
commons-io-2.2.jar,ASL
commons-logging-1.0.3.jar,ASL
hawtio-core-1.5.0.jar,ASL
hawtio-git-1.5.0.jar,ASL
hawtio-system-1.5.0.jar,ASL
hawtio-util-1.5.0.jar,ASL
httpclient-4.5.2.jar,ASL
httpcore-4.4.4.jar,ASL
jolokia-core-1.3.5.jar,ASL
json-simple-1.1.1.jar,ASL
org.osgi.core-4.3.0.jar,ASL
org.osgi.enterprise-4.2.0.jar,ASL
slf4j-api-1.7.21.jar,ASL


code licenses (some have seperate CCYB licenses for docs, but only code is packaged/redistributed up)

angular,MIT
colreorder, BSD (3 point)
cubism, ASL
dagre, MIT License
dangle, MIT

dozerXXX, ASL (hawtio)
elastic, MIT
gnatt-chart-d3, ASL
hawtio-plugin-loader ASL (hawtio)
html5shiv, MIT
jolokia, ASL
jquery, MIT
jsonschema.js, MIT
jsuri, MIT
KeyTable, BSD
less, ASL
loggingInit (hawtio)
marked, MIT
metrics-watcher ASL
mvGraphs (hawtio)
ng-grid, MIT
prefixfree, MIT
rainbow, ASL (covers also all pattern js under language folder)
sugar, MIT
toastr, MIT
bootstrap, MIT
uri.js, MIT
zeroclipboard, MIT

codemirror, MIT
D3, BSD clause 3
font-awesome, MIT
js-logger, MIT
underscore, MIT

**Comment by michaelandrepearce** [comment]
@clebertsuconic or anyone can you let me know or point me in the direction what I need to do re Artemis's license/notice files for each of the license types. To meet ASF rulings.

ASL
MIT
BSD clause 3

**Comment by michaelandrepearce** [comment]
From here:
http://www.apache.org/legal/resolved.html#category-a

We just have to list the components and the license and point to the location of the dependency in LICENSE

It's seems there is no need to touch NOTICE file for these licenses.

Can this be confirmed?

**Comment by michaelandrepearce** [comment]
now includes updated LICENSE file updated for the above licenses not under ASL, it seems none require any NOTICE update.

**Comment by michaelandrepearce** [comment]
On back of Dan's comment if we can further reduce the size of the war.

Rather than spending the effort in a complex and hard to maintain overlay, i thought i would see what is actually the high% of usages, so i ran daisy disk over to find the usage:
40% is bower components (all needed - bootstrap, d3 etc)
20% is app, but within that app.js the main js at 50% and 40% is theme/fonts (which are used)
15% is WEB-IF all used
10% is lib all used

I think trying to single out a few things will bring little return will just bring un-needed complexity, i would not go this route, and accept the war is the most sensible size without going down the diminishing returns route.

**Comment by michaelandrepearce** [comment]
@clebertsuconic @mtaylor  I think this is nearing ready for merge. I will want to quickly catch up with you both maybe IRC on monday?, as need to discuss something.

**Comment by clebertsuconic** [comment]
You think it would be good on the release ?  How much work to get the authentication working ?


Or ready to merge but not release.  


We can talk on Monday.  I'm not doing much coding this weekend.

**Comment by michaelandrepearce** [comment]
@clebertsuconic if we can sort authentication, yes. This is what I'd like to speak to you and @mtaylor on.

**Comment by michaelandrepearce** [comment]
@clebertsuconic i believe I've sorted the security, so if secure and admin role you can login. It be still good to catchup with yourself and @mtaylor on IRC later today privately quickly.

**Comment by michaelandrepearce** [comment]
Rebased post 2.2.0 tagging, also updated logo with new logo.

**Comment by clebertsuconic** [comment]
@michaelandrepearce small tweak, can you add a link to the console on the main index?

When you go to localhost you see this list:

- API
- User Manual
- Hacking Guide
- Examples
- Apache ActiveMQ Artemis Website


it would be useful having the webconsole as the first link here.

**Comment by michaelandrepearce** [comment]
@clebertsuconic added, also re-skinned slightly so colour/theme match new logo a little better.

**Comment by andytaylor** [comment]
looks good, altho I had to tweak the build by adding 
'<exclude>**/overlays/**</exclude>'
to the rat plugin

**Comment by michaelandrepearce** [comment]
You get that if your ide generates overlay. If you just use maven , maven cleans up, I saw same thing with intellij.

We can add that to the ignores and we should add it to git ignore also I guess to avoid people accidentally checking in

**Comment by michaelandrepearce** [comment]
pushed gitignore and rat exclusion for the build time generated overlays dir ide's create.

**Comment by mtaylor** [comment]
I've just managed to get round to review this.  I've been through all the source files, both in this and the original project to ensure everything is properly licensed.  The original project was not properly licensed.  It is now and I think we can safely merge this.

Great work on this @michaelandrepearce.  There are several improvements I think we can make, such as those raised by Dan and some of my own ideas around styling etc...  But these can be done at a later date.  We can't expect the console to be 100% perfect straight away.  Let's get this merged and we can all work on the improvements.

Thanks!

**Comment by clebertsuconic** [comment]
I will merge this then.

**Comment by michaelandrepearce** [comment]
+1 merging, once current tag in flight is done, just quickly to confirm we agreed we'd immediately re-tag with the console in so we can get end user feedback asap. @mtaylor you still ok with running with that?

**Comment by clebertsuconic** [comment]
There are a few tasks that would be nice to be in a release as well.  I would do a short cycle including not only this.

**Pull request closed without merging**
