### PR TITLE
ARTEMIS-2201 Added tests on DEFAULT_JOURNAL_FILE_OPEN_TIMEOUT value

### PR DESCRIPTION
**Pull request by feuillemorte**
Added 2 tests to cover changing variable DEFAULT_JOURNAL_FILE_OPEN_TIMEOUT:
1. I'm starting a server and then checking that I have default value
2. I'm setting my random value, then starting a server and then checking that server has my value not default

### CODE REVIEW

**Comment by michalxo** [comment]
@mnovak1 @andytaylor could you please check this PR?

**Comment by mnovak1** [comment]
@michalxo Would it be possible to check that value was set to JournalFilesRepository.journalFileOpenTimeout attribute?

**Comment by michalxo** [comment]
It is a question on @feuillemorte Oleg, not me. I am not an author  :-)

**Comment by mnovak1** [comment]
@michalxo Sorry, i got confused as you were asking to check this PR :-)

@feuillemorte @franz1981 Also byteman might do the trick. Byteman rule would be triggered after write to journalFileOpenTimeout variable. Rule would call byteman helper method in test case which would set some variable to given value. Then this value would be asserted in test. I think that there are already some tests like this in Arteims test suite.

**Pull request closed without merging**
