### PR TITLE
ARTEMIS-385 fixing race

### PR DESCRIPTION
**Pull request by clebertsuconic**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@jbertram  this could be related to the issue you were hitting on backup?

**Comment by jbertram** [comment]
@clebertsuconic, I certainly think it's possible.  However, I haven't dug into that issue much as I've been working on other tasks so I can't say for sure.

**Comment by clebertsuconic** [comment]
@jbertram sure.. was just mentioning as I bumped into this by accident.

**Comment by clebertsuconic** [comment]
The failure on jenkins is non related. But there's a failure on a test and I'm investigating this.

**Comment by clebertsuconic** [comment]
test fixed! ready to merge again

**Pull request merged**
