### PR TITLE
ARTEMIS-2847 socks5h support

### PR DESCRIPTION
**Pull request by swerner0**
Added 'socksRemoteDNS' transport parameter.
If set to true, remote destination socket is created unresolved and DNS resolution is disabled.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
tests?

**Comment by swerner0** [comment]
Moved previous SOCKS tests into separate class and added test for my use case

**Comment by jbertram** [comment]
@swerner0, can you squash the commits? Everything else looks good to me.

**Comment by clebertsuconic** [comment]
I can actually squash it while I merge. don't worry about it.


I will merge this.... tests are good.

**Comment by swerner0** [comment]
ok, thanks. lemme know if you need anything else

**Pull request closed without merging**
