### PR TITLE
ARTEMIS-1746: Fix client side OpenSSL

### PR DESCRIPTION
**Pull request by blsemo**
- Added a client side open ssl context as the open ssl context does not support switching, so needs to be created correctly right away.
- Sorted out passing in of trusted keys to the open ssl wrapper - just passing in the first key does not work in cases where trust has to be established via a chain
- Added integration tests for using tc-native boring ssl wrapper.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
testTwoWaySSLVerifyClientHost is failing.. is it supposed to fail?


when merging this.. I will squash all of these commits into one.. and create a JIRA.. I can do that.. but for now I just wanted to figure out about testTwoWaySSLVerifyClientHost.

**Comment by blsemo** [comment]
None of the new tests are failing for me (or are supposed to fail) - in what configuration are you running them? If I can reproduce the failure, I can take a look.

**Comment by clebertsuconic** [comment]
I'm running on Idea... on a Mac.

**Comment by blsemo** [comment]
Ok, it seems to boil down to the difference between KQUEUE netty acceptor (Mac native) and NIO netty acceptor (pure Java, used on Windows) - NIO works, KQUEUE fails to find the cert chain. I have to investigate further, also need to check how it behaves on Linux.

**Comment by jbertram** [comment]
I ran it on Linux before your change and with your change and everything worked.

**Comment by clebertsuconic** [comment]
If it’s valid on Linux only we could just have assume calls.

**Comment by blsemo** [comment]
I think the failing test is fixed - it was caused by missing keystore/truststore files - they must have slipped through the initial git stage.

**Comment by clebertsuconic** [comment]
Thanks a lot...


I squashed all your commits into one and merged.. thanks

**Pull request closed without merging**
