### PR TITLE
ARTEMIS-1223 OutOfDirectMemoryError raised from TimedBuffer

### PR DESCRIPTION
**Pull request by franz1981**
Force allocation of direct ByteBuffer with Cleaner to help GC on tests.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
what is the difference?

**Comment by franz1981** [comment]
@clebertsuconic ``Unpooled::directBuffer`` is not specified on Netty javadoc but could allocate a direct ``ByteBuffer`` with no ``Cleaner`` in it i.e. when GC occour the JVM doesn't free it.
Calling directly ``ByteBuffer.allocateDirect`` forces the instantiation of the buffer with a ``Cleaner``, hence tests, that create and destroy multiple ``TimedBuffer`` instances do not goes OOM anymore.

**Comment by clebertsuconic** [comment]
@franz1981  mind adding some // about it?

**Comment by franz1981** [comment]
@clebertsuconic Probably it would be better to push a PR on Netty to add some doc on it too, but I agree, I'll pur a comment to make it more clear :+1:

**Pull request closed without merging**
