### PR TITLE
auto link to ARTEMIS Jira project

### PR DESCRIPTION
**Pull request by hboutemy**

### CODE REVIEW

**Comment by jbertram** [comment]
@hboutemy, I can't find any details about what this change would actually do. Can you provide any details?

**Comment by hboutemy** [comment]
yes, sure: see for example this history of commits which has defined the associated Jira id
https://github.com/apache/maven-doxia-sitetools/commits/master

you'll see that each Jira issue in commit description has a link to the Jira issue

that's what is missing currently for Artemis, that is just what this little configuration is about

here is the INFRA doc on this feature https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=127405038#Git.asf.yamlfeatures-AutolinksforJira

**Comment by gemmellr** [comment]
Neat! Done.

```
remote: GitHub meta-data changed, updating...
remote: GitHub repository meta-data updated!
remote: Setting up new auto-link for ARTEMIS-<num> -> https://issues.apache.org/jira/browse/ARTEMIS-<num>
```

https://github.com/apache/activemq-artemis/commits/main

**Comment by clebertsuconic** [comment]
this is neat! nice!

thanks

**Pull request closed without merging**
