### PR TITLE
ARTEMIS-1165 Artemis 1.x JMS bindings doesn't handle JDBC network problems

### PR DESCRIPTION
**Pull request by franz1981**

### CODE REVIEW

**Comment by andytaylor** [comment]
please retest this

**Comment by andytaylor** [comment]
retest this please

**Comment by clebertsuconic** [comment]
Best way to retest is to connect on the Jenkins console and hit rebuild. 

Or git amend.  And push -f.  That is the easiest.

**Comment by andytaylor** [comment]
rebuilding now

**Pull request merged**
