### PR TITLE
ARTEMIS-1243 Release ReferenceCounted messages

### PR DESCRIPTION
**Pull request by hwaastad**
This time make PR build compliant

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
retest this please

**Comment by michaelandrepearce** [comment]
damn it, seems there isn't installed https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin , seems build failed not due to code change but general infra issue. 

@hwaastad if you update the git commit message e.g. prefix the jira ticket "ARTEMIS-XXX" which probably should be done anyhow, and then force push to your branch that should trigger another rebuild

**Comment by hwaastad** [comment]
@michaelandrepearce 
Sure,
will you create an jira issue?

**Comment by michaelandrepearce** [comment]
If you goto https://issues.apache.org/jira/projects/ARTEMIS and create an account (if you don't have one already) you should be able to.

**Comment by michaelandrepearce** [comment]
LGTM to me.
Thanks @hwaastad great that you found the bottom of the issue with MQTT and even more awesome you're able to resolve it. Thanks for this :) 

Im not a committer, will have to wait for @clebertsuconic to merge for us. But thanks again :)

**Pull request closed without merging**
