### PR TITLE
ARTEMIS-1056 Improving Proton usage

### PR DESCRIPTION
**Pull request by clebertsuconic**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@tabish121  can you review this one?

**Comment by tabish121** [comment]
At first look this does improve things quite a bit, consumer performance now seems to track with producer performance in my tests

**Comment by clebertsuconic** [comment]
@tabish121  nice!

don't merge this yet.. I am making one final adjustment.

**Comment by tabish121** [comment]
Checkstyle is asking you for some more work.

**Comment by clebertsuconic** [comment]
@tabish121 thanks.. done

**Pull request merged**
