### PR TITLE
Artemis 1012

### PR DESCRIPTION
**Pull request by mtaylor**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
Let me the one merging this.. I want to make sure there are no clashes with what I'm doing.

I didn't see any now.. but I want to play with it.

**Comment by clebertsuconic** [comment]
@mtaylor Can you do this on the upstream branch artemis-1009 instead? too many conflicts.

Maybe I can minimize if I squash it, but it seems you could do it quickly there?

**Comment by mtaylor** [comment]
@clebertsuconic Your branch is not building for me.  Let's just review this as it is, and I'll help you rebase when the time comes.

**Comment by clebertsuconic** [comment]
Can we leave this out till Monday ?  I'm almost ready to merge mine.

**Comment by clebertsuconic** [comment]
apache/artemis-1009 builds without -Pdev... I'm fixing the checkstyle now.

**Comment by mtaylor** [comment]
@clebertsuconic I've closed this out and opened a PR againt the artemis-1009 branch.

**Comment by mtaylor** [comment]
See #1062

**Pull request closed without merging**
