### PR TITLE
ARTEMIS-93 Add default config to feature

### PR DESCRIPTION
**Pull request by cschneider**
Adds default configs to the feature so a broker is created automatically when the feature is installed.
This also fixes a bug in the feature file I introduced by placing the license header in the wrong position.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
when you build, you should do:

mvn -Pdev install

That will activate checks

**Comment by cschneider** [comment]
Sorry.. forgot to use the profile again. I will make sure I run it from now on. Btw. The checks only seem to take 10 seconds for the whole build. Wouldn't it make sense to include them in mvn install?

In this case I excluded the org.apache.activemq.artemis.cfg from the rat check as I think it does not make sense to add a license to a 3 line cfg. Is this ok?

**Comment by clebertsuconic** [comment]
@cschneider I always preferred on by default, we disabled it because of discussions on the dev list... someone downloading the source distribution would prefer making changes without being bound to checkstyle and other things.. so it was "decided" devs should use the dev profile.

**Comment by clebertsuconic** [comment]
It's ok to add ignores on the rat check for such things. yeah.

**Comment by cschneider** [comment]
Ok for me to build with the profile. In any case you can ignore my pull requests until jenkins likes them :-)
I will also make sure to then squash my commits into a single one so there is not to much noise in the commits.

**Comment by clebertsuconic** [comment]
I have no issues with the failed builds (I send failed builds myself all the time)... I was just letting you know about the -Pdev profile.

**Comment by cschneider** [comment]
Btw. I really like the Jenkins integration with the pull request. I must find out how to also support this in CXF, Aries and Karaf.

**Pull request merged**
