### PR TITLE
ARTEMIS-5174 Have dependabot ignore jgroups until JGRP-2794 is resolved

### PR DESCRIPTION
**Pull request by AntonRoskvist**
This replaces #5360

### CODE REVIEW

**Comment by jbertram** [comment]
@AntonRoskvist, can you elaborate on what compatibility issues you saw when upgrading?

**Comment by AntonRoskvist** [comment]
@jbertram 

I've actually seen slightly different issues between different versions but this is a stack trace I had saved that occurs when "rolling in" a version 2.36.0 broker to a cluster of 2.35.0 brokers:

`2024-11-06 12:48:21,198 ERROR [org.jgroups.protocols.TCP] JGRP000030: $HOSTNAME-23534: failed handling incoming message 
java.net.SocketException: Socket closed 
        at java.base/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:248) ~[?:?] 
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:327) ~[?:?] 
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[?:?] 
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[?:?] 
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966) ~[?:?] 
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244) ~[?:?] 
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284) ~[?:?] 
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343) ~[?:?] 
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201) ~[?:?] 
        at org.jgroups.BytesMessage.readPayload(BytesMessage.java:265) ~[jgroups-5.3.9.Final.jar:5.3.9.Final] 
        at org.jgroups.BaseMessage.readFrom(BaseMessage.java:317) ~[jgroups-5.3.9.Final.jar:5.3.9.Final] 
        at org.jgroups.protocols.TP.handleSingleMessage(TP.java:1327) [jgroups-5.3.9.Final.jar:5.3.9.Final] 
        at org.jgroups.protocols.TP.receive(TP.java:1302) [jgroups-5.3.9.Final.jar:5.3.9.Final] 
        at org.jgroups.blocks.cs.BaseServer.receive(BaseServer.java:213) [jgroups-5.3.9.Final.jar:5.3.9.Final] 
        at org.jgroups.blocks.cs.TcpConnection$Receiver.run(TcpConnection.java:304) [jgroups-5.3.9.Final.jar:5.3.9.Final] 
        at java.base/java.lang.Thread.run(Thread.java:833) [?:?] `
        
I've seen some variation in the effect of this as well, like two clusters forming alongside each other or the new brokers simply not forming a cluster at all until all the old ones are stopped, then restarting some or all of the new ones.

**Comment by jbertram** [comment]
What JGroups configuration were you using here?

**Comment by AntonRoskvist** [comment]
I have tried with some variations in the stack to try and get around this problem but without success. The stack I posted yesterday is using TCP as the transport, typically I use TCP_NIO. 

Similar stack using that transport:
`2024-11-06 12:30:48,947 ERROR [org.jgroups.protocols.TCP_NIO2] JGRP000030: $HOSTNAME-26050: failed handling incoming message 
java.io.EOFException: null 
        at org.jgroups.util.ByteArrayDataInputStream.readFully(ByteArrayDataInputStream.java:118) ~[jgroups-5.3.9.Final.jar:5.3.9.Final] 
        at org.jgroups.BytesMessage.readPayload(BytesMessage.java:265) ~[jgroups-5.3.9.Final.jar:5.3.9.Final] 
        at org.jgroups.BaseMessage.readFrom(BaseMessage.java:317) ~[jgroups-5.3.9.Final.jar:5.3.9.Final] 
        at org.jgroups.protocols.TP.handleSingleMessage(TP.java:1327) [jgroups-5.3.9.Final.jar:5.3.9.Final] 
        at org.jgroups.protocols.TP.receive(TP.java:1283) [jgroups-5.3.9.Final.jar:5.3.9.Final] 
        at org.jgroups.util.Util.bufferToArray(Util.java:1221) [jgroups-5.3.9.Final.jar:5.3.9.Final] 
        at org.jgroups.blocks.cs.Receiver.receive(Receiver.java:36) [jgroups-5.3.9.Final.jar:5.3.9.Final] 
        at org.jgroups.blocks.cs.NioConnection._read(NioConnection.java:226) [jgroups-5.3.9.Final.jar:5.3.9.Final] 
        at org.jgroups.blocks.cs.NioConnection.read(NioConnection.java:201) [jgroups-5.3.9.Final.jar:5.3.9.Final] 
        at org.jgroups.blocks.cs.NioBaseServer$Acceptor.run(NioBaseServer.java:145) [jgroups-5.3.9.Final.jar:5.3.9.Final] 
        at java.base/java.lang.Thread.run(Thread.java:833) [?:?] `

This is the basic config I use:
`<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="urn:org:jgroups"
           xsi:schemaLocation="urn:org:jgroups http://www.jgroups.org/schema/jgroups.xsd">

   <TCP_NIO2 bind_port="7800" bind_addr="match-interface:$IF" diag.enable_tcp="true" diag.port="7801"/>
   <TCPPING initial_hosts="$HOST1[7800],$HOST2[7800],$HOST3[7800],$HOST4[7800],$HOST5[7800]" port_range="0"/>

   <MERGE3 min_interval="5000" max_interval="10000" check_interval="15000"/>
   <RED/>
   <FD_ALL3 timeout="10000" interval="1000"/>
   <VERIFY_SUSPECT2 timeout="1500"/>
   <BARRIER/>
   <pbcast.NAKACK2 use_mcast_xmit="false"/>
   <UNICAST3/>
   <pbcast.STABLE desired_avg_gossip="50000" max_bytes="4M"/>
   <pbcast.GMS print_local_addr="true" join_timeout="2000"/>
   <UFC max_credits="2M" min_threshold="0.4"/>
   <FRAG2 frag_size="60K"/>
   <pbcast.STATE_TRANSFER/>
</config>`

**Pull request merged**
