### PR TITLE
small open wire change and another tweak

### PR DESCRIPTION
**Pull request by clebertsuconic**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@howardgao @gaohoward  It seems this is not really needed. I didn't find a real use for it at least.. all the tests are passing the same.  Can you confirm please? (talking about 36350c2)

**Comment by gaohoward** [comment]
@clebertsuconic yeah I think you can just merge it. They are not needed anywhere in the clients as far as I can tell. However I'll run the tests just to make double sure (meaning don't wait for me).

**Comment by clebertsuconic** [comment]
I already run the tests.. didn't make a difference

**Comment by gaohoward** [comment]
ok. It should be ok enough.

**Comment by clebertsuconic** [comment]
The create durable queue is creating some test failures.. the change is good but there are tests failing (probably because they need to cleanup something... I will have to check out).

Let me work on this first

**Pull request merged**
