### PR TITLE
ARTEMIS-3538: Removing // --------- comments from the codebase

### PR DESCRIPTION
**Pull request by Asukwo-comfort**
Issue link: https://issues.apache.org/jira/browse/ARTEMIS-3538

I have tried removing comments like the one below from these codebase:
// Constants -----------------------------------------------------

// Attributes ----------------------------------------------------

// Static --------------------------------------------------------

// Constructors --------------------------------------------------

Cc @clebertsuconic

### CODE REVIEW

**Comment by clebertsuconic** [comment]
there's a merge commit on your Pull Request.


please rebase against main and push -f?

**Comment by Asukwo-comfort** [comment]
Is the force-pushed meant to close my pull request? I don't get why it keeps closing my pull request whenever a force-push

@clebertsuconic

**Comment by clebertsuconic** [comment]
@Asukwo-comfort you lost your commit in your git operations... you pretty much made a mistake.

I suggest you do a checkout from apache/main -B YOUR-branch
then I would cherry-pick the commit.
Fix the diffs...
and push -f


you need to rebase and fix the inconsistencies with main.

at least for now you can recover your previous branch by doing:

git reset 872e570 
git push origin -f



Then you should checkout main:
git checkout main -B new-branch

and cherry-pick commit with the fix:


git cherry-pick 89253b8513d597af04c631ce0b32882113e5d84b


mixup the diffs...
and push -f

**Comment by clebertsuconic** [comment]
these are all regular git-fu... rebasing, fixing conflicts.. etc...

**Comment by Asukwo-comfort** [comment]
I have done the necessary fixes and added a new commit and force-pushed

@clebertsuconic

**Comment by clebertsuconic** [comment]
Thank you so much @Asukwo-comfort ...I have merged your PR (with a rebase).

I found a few extra ones that I included on a separate commit.. Thank you so much for your collaboration.


This concludes the PR you need for your outreachy application. thank you

**Comment by Asukwo-comfort** [comment]
@***@***.*** ***@***.***> I really appreciate
your effort in putting me through on this contribution. Though it actually
took me sometime to get to understand the codebase,  i will love to keep
contributing to the project so i that i can learn in process, that's if you
don't mind

**Pull request closed without merging**
