### PR TITLE
ARTEMIS-1360 Documenting runtime reloadable configuration

### PR DESCRIPTION
**Pull request by gaohoward**
Adding details about broker's configuration parameters
that can be reloaded during runtime.

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
@howardgao just a note that the queues section due to recent pr of mine to support dynamic runtime change is out of date. I can update / create a pr to update this though once this is merged.

**Comment by michaelandrepearce** [comment]
Forgot to mention looks in general good, great to see docs getting some love :)

**Comment by clebertsuconic** [comment]
@michaelandrepearce I will merge this then.

**Comment by gaohoward** [comment]
Thanks guys.

**Pull request closed without merging**
