### PR TITLE
ARTEMIS-1749 - Fixes the ssl-enabled-crl-mqtt

### PR DESCRIPTION
**Pull request by ingo1121**
Also, this is a pretty obvious fix. Doesn't quite fix ssl-enabled-dual-authentication
, though,,

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@ingo1121 can you please do these following commands?

```sh
git pull --rebase upstream master
git push origin -f
```

**Comment by clebertsuconic** [comment]
I fixed it.. but your PR was way too messed up. if I had merged your merges.. we would have created a mess on master. please no merge commits on PRs.

**Comment by clebertsuconic** [comment]
@ingo1121 actually I'm reverting this PR. These examples are not running after your change. I shouldn't have merged it in the first place

**Comment by ingo1121** [comment]
Been absent on vacation. Back now. Sorry if i messed up the revision-tree!

 Anyway, now the examples in Windows is, is far as I can judge, consistent with examples on RHEL7.

**Comment by ingo1121** [comment]
Hi!

Sorry for the mess with the git tree!

 

I have some question, though: 

 

1.	What is your normal build procedure? On my fork, I’ve made a Jenkins job, that just does a ”mvn install” ob the root directory; no profiles or anything. Is that reasonable?
2.	I tried to make a ”full example” integration test; by running ”mvn -Pexamples verify” on the examples directory. Unfortuatly it quickly runs out of steam (both on Windows and RHEL). Is this something that should be fixed? Should I register a JIRA? I notice that a lot of Java processes are left behind…

 

Regards

Ingemar

 

 

Från: clebertsuconic <notifications@github.com> 
Skickat: den 3 april 2018 00:52
Till: apache/activemq-artemis <activemq-artemis@noreply.github.com>
Kopia: ingo1121 <ingemar@lupusani.se>; Mention <mention@noreply.github.com>
Ämne: Re: [apache/activemq-artemis] ARTEMIS-1749 - Fixes the ssl-enabled-crl-mqtt (#1983)

 

I fixed it.. but your PR was way too messed up. if I had merged your merges.. we would have created a mess on master. please no merge commits on PRs.

**Pull request closed without merging**
