### PR TITLE
ARTEMIS-1592 AutoDeleted queues before sendNotification

### PR DESCRIPTION
**Pull request by clebertsuconic**
…lose is sent on clustering

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
Nice... how on earth did you find this?!! Amazing!! +1 from me

**Comment by clebertsuconic** [comment]
@michaelandrepearce I followed the test the user provided on ARTEMIS-1592

**Comment by michaelandrepearce** [comment]
Still nice...

**Comment by michaelandrepearce** [comment]
I would merge for you. But on phone atm

**Pull request closed without merging**
