### PR TITLE
ARTEMIS-1555 MQTT - Unsubscribe topic in cluster environment leaves r…

### PR DESCRIPTION
**Pull request by Skiler**
…eference to the consumer

### CODE REVIEW

**Comment by Skiler** [comment]
The commit message is too long to be included in the commit

**Comment by jbertram** [comment]
> The commit message is too long to be included in the commit

Please follow the commit recommendations in the [Hacking Guide](https://github.com/apache/activemq-artemis/blob/master/docs/hacking-guide/en/maintainers.md#commit-messages).

Also, please squash your commits and then `push -f` to your branch where the PR is based (i.e. `Skiler:remoteQueueSubscriptionRemoveConsumer`).  More details [here](https://davidwalsh.name/squash-commits-git).  GitHub will automatically pick up the changes on the PR branch.

**Comment by mtaylor** [comment]
@Skiler Good catch and nice work on the tests.  @jbertram @Skiler I am going to merge.  I will take care of the commit message and squash.  Thanks.

**Comment by jbertram** [comment]
@Skiler, nice work!

**Comment by Skiler** [comment]
@jbertram @mtaylor thanks =D

**Pull request merged**
