### PR TITLE
Support useTopologyForLoadBalancing on JMS ConnectionFactory urls

### PR DESCRIPTION
**Pull request by mvtorres**

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
Test cases needed to cover new feature, also documentation needed to describe the feature for others

**Comment by mvtorres** [comment]
This is an existing feature, I just exposed it so its usable on urls of ConnectionFactory.

Existing documentation is at https://activemq.apache.org/artemis/docs/latest/clusters.html#client-side-load-balancing

Im trying to add a testcase/logic to org.apache.activemq.artemis.tests.integration.cluster.distribution.NettySymmetricClusterTest

which was added by the original pull request

https://github.com/apache/activemq-artemis/commit/b6b8fa411f4dcf9e6ac8248489579dac8d931cb3

but Im having trouble getting that to execute locally.

When I run  

`mvn -Ptests -DfailIfNoTests=false -Dtest=NettySymmetricClusterTest test`

I'm getting 


[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 56.893 s
[INFO] Finished at: 2018-09-04T12:54:56-04:00
[INFO] Final Memory: 127M/1567M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project unit-tests: Compilation failure: Compilation failure:
[ERROR] /Users/mark/git/activemq-artemis/tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/ra/ResourceAdapterTest.java:[62,81] cannot access ActiveMQConnectionFactory
[ERROR] class file for ActiveMQConnectionFactory not found
[ERROR] /Users/mark/git/activemq-artemis/tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/ra/ResourceAdapterTest.java:[93,81] incompatible types: ActiveMQConnectionFactory cannot be converted to org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory
[ERROR] /Users/mark/git/activemq-artemis/tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/ra/ResourceAdapterTest.java:[94,82] incompatible types: ActiveMQConnectionFactory cannot be converted to org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory


Can you point me to the right direction...

Thanks

**Comment by clebertsuconic** [comment]
I usually just use the IDE to run tests...

But you probably need to build the project before running the test?

**Comment by clebertsuconic** [comment]
TBH: This currently works already. you don't need to expose the property.

The URI is used to create the serverLocator, and it will be set on it already.

**Comment by clebertsuconic** [comment]
Why don't you just use cf = new ActiveMQConnectionFActory(uri); ?

**Comment by clebertsuconic** [comment]
anyway.. if you add the property.. also add the getter.. as the externalize will it.

**Comment by mvtorres** [comment]
> Why don't you just use cf = new ActiveMQConnectionFActory(uri); ?

The existing code has the ConnectionFactory lookup via jndi, we're migrating from a different JMS provider(JBoss Messaging).

**Comment by jbertram** [comment]
@mvtorres, how is JNDI being configured?

**Comment by mvtorres** [comment]
This is the config, our app is currently running on jboss 4.3.

<mbean code="org.jboss.naming.ExternalContext"
       name="DefaultDomain:service=ExternalContext,jndiName=RemoteJMSJNDI">
	  <attribute name="JndiName">RemoteJMSJNDI</attribute>
	  <attribute name="Properties">
	   		java.naming.factory.initial=org.apache.activemq.artemis.jndi.ActiveMQInitialContextFactory
		    java.naming.provider.url=tcp://localhost:61616?useTopologyForLoadBalancing=false
		    topic.topic/eventTopic=eventTopic
...
	  </attribute>
	  <attribute name="InitialContext">javax.naming.InitialContext</attribute>
</mbean>

Artemis is running inside docker, with the connector dynamically set to the docker container ip.

**Comment by clebertsuconic** [comment]
@jbertram  I think the right fix is on the Schemas...


```java
   @Override
   protected ActiveMQConnectionFactory internalNewObject(URI uri,
                                                         Map<String, String> query,
                                                         String name) throws Exception {
      JMSConnectionOptions options = newConectionOptions(uri, query);
      ActiveMQConnectionFactory factory = ActiveMQJMSClient.createConnectionFactoryWithoutHA(options.getFactoryTypeEnum(), InVMTransportConfigurationSchema.createTransportConfiguration(uri, query, name, "org.apache.activemq.artemis.core.remoting.impl.invm.InVMConnectorFactory"));
      BeanSupport.setData(uri, factory, query);
      BeanSupport.setData(uri, factory.getServerLocator(), query);
      return factory;
   }
```

**Comment by clebertsuconic** [comment]
Please look at #2292

**Comment by mvtorres** [comment]
Thanks for the fix.

**Pull request closed without merging**
