### PR TITLE
Fix a condition check in xaCommit()

### PR DESCRIPTION
**Pull request by gaohoward**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@andytaylor  do you remember this? I think this XID was on purpose.

**Comment by gaohoward** [comment]
Is this for fixing TCK?

**Comment by clebertsuconic** [comment]
It could be...


I believe the issue here is on the ActiveMQ5 implementation, or on the test.. they should send an xaEnd before the commit.

**Comment by gaohoward** [comment]
Yeah I think you are right clebert. I'm closing this and fix it on the test side. Thanks.

**Pull request closed without merging**
