### PR TITLE
Adding jmeter-tests and instructions

### PR DESCRIPTION
**Pull request by glaucio-melo-movile**
Adding JMeter Test Samples.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
I believe a better place for this would be ./examples/perf/jmeter instead of the testsuite folder.

**Comment by clebertsuconic** [comment]
there are failures because of the lack of license headers

**Comment by clebertsuconic** [comment]
I think I will merge this under examples/perf after some tweaks to your commit if you're ok...

but can you add the ASL headers to your code? If I do that myself would be cheating :) you have to license it as apache license

**Comment by jbertram** [comment]
Would probably be worth squashing all the commits down to one as well.

**Comment by glaucio-melo-movile** [comment]
I did perform a squash locally and for some reason I'm not able to see it here properly pushed. I will close this PR and open another one with all your suggestions.

**Comment by clebertsuconic** [comment]
Git push -f would have worked

**Comment by glaucio-melo-movile** [comment]
anyway, the updated PR - https://github.com/apache/activemq-artemis/pull/187

**Pull request closed without merging**
