### PR TITLE
NO-JIRA: Javadoc for ActiveMQServerMessagePlugin interface

### PR DESCRIPTION
**Pull request by jirkadanek**

### CODE REVIEW

**Comment by jdanekrh** [comment]
I still need to try this with a broker cluster, to see what exactly happens there.

**Comment by jbertram** [comment]
I think this would be better in the User Guide rather than the JavaDoc for this class.

**Comment by jdanekrh** [comment]
Ok, I can move it there.

I saw some java classes with quite extensive Javadoc, and I felt that explaining how user provided methods are called belongs in a Javadoc.

**Comment by jdanekrh** [comment]
(Does it look reasonable so far, what I wrote? Especially that using ThreadLocal is a good idea?)

**Comment by jbertram** [comment]
I think what you wrote looks good. I wouldn't go as far as saying that using a `ThreadLocal` is a *good* idea, but it should work nonetheless. :)

**Comment by jbertram** [comment]
I'm closing this as I don't expect it will receive any further updates. Please re-open if needed.

**Pull request closed without merging**
