### PR TITLE
https://issues.apache.org/jira/browse/ARTEMIS-815 - support wildcard …

### PR DESCRIPTION
**Pull request by dejanb**
…address configuration in mqtt layer

https://issues.apache.org/jira/browse/ARTEMIS-815 - support wildcard address configuration in mqtt layer - remove old swap method

### CODE REVIEW

**Comment by clebertsuconic** [comment]
A test would be nice

**Comment by clebertsuconic** [comment]
@dejanb  I am confused.. is this new functionality, or this is just a refactoring of an existing one (on which case you wouldn't need tests).

**Comment by dejanb** [comment]
@clebertsuconic It's not a new functionality, it's just adjusting mqtt layer code, which used hard-coded wildcard characters. I'll add a test to verify wildcard syntax of ActiveMQ 5, works fine and that we can exchange messages between mqtt and JMS clients. That should help with future migrations

**Comment by jbertram** [comment]
@dejanb, where are you on the test effort?

Also, can you amend your commit message to follow the 50/72 format discussed in the [Hacking Guide](https://github.com/apache/activemq-artemis/blob/master/docs/hacking-guide/en/code.md#commitMessageDetails)?

**Comment by jbertram** [comment]
Looks like you may need to rebase.

**Comment by mtaylor** [comment]
@dejanb I've rebased and pushed another PR (so we get the PR checks) at #1021.

**Comment by dejanb** [comment]
Great. Thanks!

**Pull request closed without merging**
