### PR TITLE
ARTEMIS-1129 Fixing tests after client all

### PR DESCRIPTION
**Pull request by clebertsuconic**
Shade is generating a file named dependency-reduced-pom.xml
and this is being considered with unaproved license.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@michaelandrepearce Shade is generating a few files at the sub-modules directories (see the changes).


this was failing:
```
mvn -Ptests test
```


I only ran the examples before.. and the build is now broken without this.


do you think these changes are ok?

I'm concerned also that the release would generate these files on the source profile. Something to be checked also.

**Comment by michaelandrepearce** [comment]
@clebertsuconic def agree that it should be git ignore , as it is generated at build time. 

are you saying by adding this exclusion in rat list, the tests break, or without adding it it breaks? i am just running the build with the -Ptests profile now, waiting for it to complete locally.

I know there is the setting dependencyReducedPomLocation which allows you to move it to another directory, problem is this breaks any remaining build process and marked buggy in the shade plugin docs so i don't think we should look at that.

**Comment by clebertsuconic** [comment]
The testsuite won't work now with that Pom at root. We need to fix the testsuite by either this PR or a better fix.

**Comment by clebertsuconic** [comment]
It's broken because of the rat plugin check.  So it needs the ignore.

**Comment by michaelandrepearce** [comment]
@clebertsuconic I'm happy with this change.

I have a few more tidy up bits, been working on, as have been exploding the jars to check whats copied in and some bits like notice and license and a load of crud from jgroups, whilst still waiting the -Ptest to complete...

shall i raise a pr to your branch or direct to master?

**Comment by clebertsuconic** [comment]
@michaelandrepearce just saw your message after I merged it... 


Send it to master... I needed to merge it so I could run tests again.

**Comment by michaelandrepearce** [comment]
@clebertsuconic just seen this, rebased and re-raised against master

**Pull request closed without merging**
