### PR TITLE
ARTEMIS-1850 QueueControl.listDeliveringMessages returns empty result

### PR DESCRIPTION
**Pull request by gaohoward**
With AMQP protocol when some messages are received in a transaction,
calling JMX QueueControl.listDeliveringMessages() returns empty list
before the transaction is committed.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
this seems to break this:

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.117 sec <<< FAILURE! - in org.apache.activemq.artemis.tests.integration.amqp.AmqpFailoverEndpointDiscoveryTest

**Comment by clebertsuconic** [comment]
actually.. ignore my last comment.. i will run more tests.. probably unrelated

**Comment by gaohoward** [comment]
ok. btw I ran it within intellij it passes.

**Comment by gaohoward** [comment]
@clebertsuconic Can you merge it? thx

**Pull request merged**
