### PR TITLE
ARTEMIS-1893: Treat the detach of a link with expiry policy of link-detatch as if closed flag were true.

### PR DESCRIPTION
**Pull request by k-wall**
I believe this patch will resolve the issue I reported.

### CODE REVIEW

**Comment by andytaylor** [comment]
There is code in ProtonServerSenderContext and ProtonServerReceiverContextthat handles how to treat this scenario, maybe it sthis that needs updating rather than handling this in 2 places?

**Comment by k-wall** [comment]
Thanks for the feedback.  I did initially consider making the change in `ProtonServerSenderContext#close(boolean)` but I couldn't see a way organise for the `closed` field of the detach performative that will go back to the peer to be set to `true` from that tier in the abstraction.  It could well be my approach is naive.

Your comment above alludes to a deeper refactoring of ProtonServerSenderContext and ProtonServerReceiverContext which i think might be more that  I could undertake,

**Comment by andytaylor** [comment]
actually on second glance I think what you have done is correct

**Comment by andytaylor** [comment]
you do have 1 checkstyle violation that needs fixing

**Comment by k-wall** [comment]
That should be the checkstyle violation resolved.

**Pull request closed without merging**
