### PR TITLE
ARTEMIS-208 BrokerInfo issue, also:

### PR DESCRIPTION
**Pull request by gaohoward**
enlarged the default max size for tests to avoid send blocking.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
Let me the one merging this ?

**Comment by gaohoward** [comment]
OK.

The brokerInfo command need to have a default URL so I added the method.

**Comment by clebertsuconic** [comment]
This fix will only work on tests.... 

on a default server, the acceptor will be at 0.0.0.0, and you will be sending tcp://0.0.0.0:port to the client.


It's also wrong to the fact that the same protocolManager will server multiple acceptors in case you have multiple ports configured. on that case you will be sending the BrokerInfo for a different port or IP.


Do you have the IP the user used to connect anywhere on the connection? So, you would have to create a brokerInfo per request.. instead caching a single one...



for that reason this fix is not valid!

**Comment by gaohoward** [comment]
yeah there is going to be a problem if acceptor is using 0.0.0.0. In that case we probably need a way to find the port which the client is connected to. 
We cache the brokerInfo but not the brokerURL, you can see we do send a brokerInfo based on connection request, see method 

ConnectionEntry createConnectionEntry(Acceptor acceptorUsed, Connection connection)

I think what's need to to is to pass a copy of brokerInfo to the new connection.

Thanks
Howard

**Comment by clebertsuconic** [comment]
Please don't cache the BrokerInfo. Just create one based on the conversation between the client and server. 

It's not a problem.. the current implementation is not fit for a production server... it needs to be fixed.

I don't remember how to get the IP the client used to connect now through the connection, but you certainly need that, and need the proper implementation.

**Comment by clebertsuconic** [comment]
@gaohoward  BTW: most of our servers are going to be configured with 0.0.0.0... run a standard server..


Play with the openwire examples on Artemis... it doesn't work on them.

**Comment by gaohoward** [comment]
ok, I can get the information from netty server connection's configuration.

**Comment by clebertsuconic** [comment]
No howard, the information is at the NettyConnection... 

Please close this PR, I'm sending my own with your commit and an extra fix which I will ask your input

**Comment by gaohoward** [comment]
ok

**Pull request closed without merging**
