### PR TITLE
ARTEMIS-1413: FIX JMSDeliveryMode/Priority on AMQP to CORE conversion

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Added test case for cross protocol on JMSDeliveryMode proving issue, and asserting fix
Added fix to AmqpCoreConverter to ensure durability (JMSDeliveryMode) is retained.

### CODE REVIEW

**Comment by tabish121** [comment]
Some checkstyle violations introduced into the test code

**Comment by michaelandrepearce** [comment]
@tabish121 yeah, just fixed

**Comment by tabish121** [comment]
I'd suggest squashing these fixes into a single commit and updating the original JIRA to reflect everything that is being fixed as it only reflects the deliveryMode at present.

**Comment by michaelandrepearce** [comment]
yeah will do that (squashing) tomorrow now, is late here, the second one (priority) I found on finding the cause of the first, thus a second commit done later.

**Comment by michaelandrepearce** [comment]
Updated Jira title to mention additional jmspriority also fixed, squashed commits and updated pr title also.

**Pull request merged**
