### PR TITLE
ARTEMIS-1002 Use default PooledBufferAllocator in ActiveMQBuffers

### PR DESCRIPTION
**Pull request by mtaylor**
I'd like feedback from @willr3 before this is merged as @willr3 did the original work around the perf gains and I don't want to reverse that good work.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@mtaylor Currently the only place we use the DEFAULT is on AMQP Converter.

I would also change https://github.com/apache/activemq-artemis/blob/master/artemis-core-client/src/main/java/org/apache/activemq/artemis/core/remoting/impl/netty/PartialPooledByteBufAllocator.java#L31 to use the DEFAULT here. I looked at the implementation and it wouldn't change any semantics. Highly recommended IMO.

**Comment by mtaylor** [comment]
@clebertsuconic The difference is that the DEFAULT pooled is platform specific on whether to use direct buffers or not.  We specifically switch this to false in the PartialPooledByteBufAllocator.  Could this be an issue here?

**Comment by clebertsuconic** [comment]
@mtaylor I didn't think it would be an issue, because the defaultPooled is only used on getBuffer method. the explicit methods that we use (directbyteBuffer, heapBuffer are not affected by that parameter).

I would also change the PartialPooledbytebufferAllocator on the client. We will endup actually saving bytes if we do this.

**Comment by mtaylor** [comment]
@clebertsuconic When you say client I suppose you mean the AMQP test client right?  i.e. activemq-artemis/tests/artemis-test-support/src/main/java/org/apache/activemq/transport/amqp/client/transport/PartialPooledByteBufAllocator.java

**Comment by clebertsuconic** [comment]
@mtaylor Oh.. right... I actually read it org.apache.activemq.core.client.. something like that... 
that's the one class I saw it.. but I confused the usage.. my bad!

**Comment by clebertsuconic** [comment]
I'm running the whole testsuite before we can merge this.. just in case.

**Comment by mtaylor** [comment]
@clebertsuconic Good idea.  Cheers.

**Pull request closed without merging**
