### PR TITLE
ARTEMIS-1766 - Persist LastValue queue config in bindings.

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Added Integration tests for the issue.
Add lastvalue to the queue bindings that get persisted.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@michaelandrepearce the failure on compatibility test seems real

**Comment by clebertsuconic** [comment]
hmmmm... I'm not so sure... hang on

**Comment by michaelandrepearce** [comment]
@clebertsuconic I think it’s unrelated. And simply pr build issue.

I ran tests all locally fine.

**Comment by clebertsuconic** [comment]
@michaelandrepearce yeah. unrelated.. I fixed the intermittent failure... will merge it soon.

if you're curious to see if it fixed.. rebase this PR and push -f.


I will merge this soon.

**Pull request closed without merging**
