### PR TITLE
ARTEMIS-866 - add functionality to allow live to vote for quorum on f…

### PR DESCRIPTION
**Pull request by andytaylor**
…ailure

Also allow the quorum size to be configurable.

https://issues.apache.org/jira/browse/ARTEMIS-866

### CODE REVIEW

**Comment by andytaylor** [comment]
tests fixed

**Comment by jbertram** [comment]
I'm still hitting a checkstyle issue when I do the PR check locally.

**Comment by jbertram** [comment]
Also, your commit message doesn't follow the 50/72 format.

**Comment by andytaylor** [comment]
cheers @jbertram Ive fixed both

**Pull request closed without merging**
