### PR TITLE
ARTEMIS-3041 Allow encrypted data source property values

### PR DESCRIPTION
**Pull request by brusdev**

### CODE REVIEW

**Comment by fvaleri** [comment]
It would probably make sense to do this only for the password key, as the documentation says: "Apache ActiveMQ Artemis can be configured to use 'masked' passwords in its configuration files."

**Comment by brusdev** [comment]
Many data source properties contain sensitive values, like the username and the value encryption for the data source properties is optional so I would not limit what properties the user can encrypt.

**Comment by fvaleri** [comment]
> Many data source properties contain sensitive values, like the username and the value encryption for the data source properties is optional so I would not limit what properties the user can encrypt.

Agree, but then we should also update the doc, adding a note about this.

**Comment by clebertsuconic** [comment]
@brusdev / @fvaleri I will merge this now.. feel free to follow up with another PR for doc changes if you guys decide to improve docs on this.

**Comment by brusdev** [comment]
@fvaleri I have just created the #3391 to improve the doc about JDBC connection pooling.

**Comment by fvaleri** [comment]
Thanks @brusdev , that's great.

**Pull request closed without merging**
