### PR TITLE
Remove redundant type arguments, add sevntu-checkstyle check for it

### PR DESCRIPTION
**Pull request by scop**
Hopefully with this check I don't need to keep submitting the redundant type args PR's any more :)

### CODE REVIEW

**Comment by scop** [comment]
The last commit is unrelated to the diamond operator, but depends on the sevntu addition so I thought I'd just bundle it here.

**Comment by clebertsuconic** [comment]
@scop  Since you are adding Seventu, can I ask you a favour?


I had this on the checkstyle: org.hornetq.checks.annotation.RequiredAnnotation,


Which I started as a PR on Seventu. I have written a PR for them, but I couldn't finish it because they had too many requirements, and I didn't have time to finish, so I think someone took over my contribution and finished into Seventu.


Can you check on replacing my RequiredAnnotations by the one on Seventu, which I believe my contribution has made into there? if you can't just let me know and I will find some time to do it later this week.

**Comment by clebertsuconic** [comment]
@scop  Here is my PR: https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/203

it was replaced by another pr:

https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/321

**Comment by clebertsuconic** [comment]
Oh.. wow.. you already did it.. awesome!

**Comment by bwzhang2011** [comment]
@clebertsuconic, sevntu checkstyle plugin address was wrong that we could not simply build it right for I could not access the url http://sevntu-checkstyle.github.io/sevntu.checkstyle/maven2. and it's better that the dependency for maven-checkstyle-plugin should be dsm-maven-plugin. so if it was replaced by as follows:
<groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-checkstyle-plugin</artifactId>
            <version>2.17</version>
            <dependencies>
               <dependency>
                  <groupId>com.github.sevntu-checkstyle</groupId>
                  <artifactId>dsm-maven-plugin</artifactId>
                  <version>2.1.4</version>
               </dependency>
            </dependencies>

and comment out the sevntu url . the 1.4 release could be built as expected.

**Comment by clebertsuconic** [comment]
Can you send a PR?

**Pull request closed without merging**
