### PR TITLE
Fix Issue #245

### PR DESCRIPTION
**Pull request by exabrial**

### CODE REVIEW

**Comment by mtaylor** [comment]
@exabrial Hi could you please add a bit more context to the commit message. 

@clebertsuconic I will leave this one with you since you have been involved in #245.

**Comment by clebertsuconic** [comment]
The commit message should be something like:

ARTEMIS-### Any textual explaining what's being done...



We don't simply rely on the Links from JIRA for instance...  the jira might be replaced some day.. and when someone is looking from git logs.. it gets impracticable to look for changes and looking for regressions if we only used jira links.




If you can't do it I will treat this as a patch and rebase during merge... but you would probably lose ownership of your commit on the logs.

**Comment by mtaylor** [comment]
@exabrial Hi, any chance you could update the commit message and we'll get this merged.

Thanks

**Comment by exabrial** [comment]
I'm not completely sure it's correct actually... a better way would be go
make the connection class an interface, rather than a final class.

Also at Devoxx UK in two weeks I'm leading a workshop with the goal is to
get this working 100%. If any of you will be available, or present
physically, that'd be awesome!

**Comment by mtaylor** [comment]
@exabrial I'd be happy to help.  I can talk to you on IRC #activemq or on the dev list.

**Comment by mtaylor** [comment]
@exabrial I am going to close this PR based on our discussion.  We can reopen later if need be.

**Comment by mtaylor** [comment]
@exabrial Actually doesn't look like I have permissions to close this PR.  Could you please close it. 

Thanks

**Pull request closed without merging**
