### PR TITLE
ARTEMIS-4035 all consumers of federated queue drop if only one consum…

### PR DESCRIPTION
**Pull request by jbertram**
…er drops

### CODE REVIEW

**Review by gtully — APPROVED** [review]
nice test and fix!

**Comment by clebertsuconic** [comment]
@jbertram LGTM: if you could check the whole test suite before merging it though?

**Comment by jbertram** [comment]
@clebertsuconic, I just saw your comment after I merged. I'm running the full test-suite now. FWIW, I ran all the federations tests manually and they all passed.

**Comment by jbertram** [comment]
Full test-suite looks good. No related failures.

**Pull request closed without merging**
