### PR TITLE
Pass JNDI name in XARecoveryConfig

### PR DESCRIPTION
**Pull request by mtaylor**
Some TX managers require JNDI name for recovery purposes.  This patch
passes JNDI name in RA to RecoveryRegistry implementations via
XARecoveryConfig objects.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
I just think the parameter name jndiName is a too generic name.. it's not clear if that means the connectionFactory or the TM...


I would rename it to something else with its purpose.. such as tmRegistry, recoveryRegistry, etc...

**Comment by mtaylor** [comment]
@clebertsuconic I'll change this so it passes in a map of properties as discussed.

**Comment by clebertsuconic** [comment]
I'm looking at this.. please don't merge it

**Comment by clebertsuconic** [comment]
I thought about having everything just using BeanUtils, and converting properties to avoid these constants.. but on a second thought it was more hassle than worth.

I'm merging this... sorry for the confusion.. I wanted to improve things but in the end it would be a lot of work.

**Pull request closed without merging**
