### PR TITLE
ARTEMIS-2264 PurgeOnNoConsumers prevent removal of messages with replication

### PR DESCRIPTION
**Pull request by franz1981**

### CODE REVIEW

**Comment by franz1981** [comment]
I have left 2 commits until it will get reviewed, to simplify the code review
Given that is related to https://github.com/apache/activemq-artemis/pull/1818 is suppose that both @andytaylor and @clebertsuconic can take a look on this.
The CI seems fine with this one, there are no regressions dependent on it

**Comment by clebertsuconic** [comment]
Squash the test and the fix together?

**Comment by franz1981** [comment]
@clebertsuconic Sure! let me do it now

**Comment by michaelandrepearce** [comment]
@franz1981 seems a test failure.

  PagingStoreImplTest.testConcurrentDepage:370->testConcurrentPaging:492 » ActiveMQIllegalState

**Comment by franz1981** [comment]
@michaelandrepearce I've runs full CI and I've got the common intermittent failures as always but I will look to this one to check if is happening all the time

**Comment by clebertsuconic** [comment]
Franz.. rebase to kick in a new job?

I 've run this locally and no failures... 

I can merge it tomorrow

**Comment by franz1981** [comment]
@clebertsuconic This time seems to have worked fine :+1:

**Pull request closed without merging**
