### PR TITLE
ARTEMIS-119 Upgraded to Jetty 9.2.

### PR DESCRIPTION
**Pull request by johnament**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
The server doesn't start it for some reason:

I built the server, create the server, ran it and got an exception

```sh
cd artemis-distribution/target/apache-artemis-1.0.1-SNAPSHOT-bin/apache-artemis-1.0.1-SNAPSHOT/bin
./artemis create /tmp/myserver --user a --password a --allow-anonymous y
cd /tmp/myserver/bin
./artemis run
```

and I got this:
```
23:29:35,747 INFO  [org.apache.activemq.artemis.integration.bootstrap] AMQ101005: Using broker configuration: xml:/tmp/lixo/etc/bootstrap.xml
23:29:36,202 INFO  [org.apache.activemq.artemis.integration.bootstrap] AMQ101000: Starting ActiveMQ Artemis Server
23:29:36,235 INFO  [org.apache.activemq.artemis.core.server] AMQ221000: live Message Broker is starting with configuration Broker Configuration (clustered=false,journalDirectory=../data/journal,bindingsDirectory=../data/bindings,largeMessagesDirectory=../data/large-messages,pagingDirectory=../data/paging)
23:29:36,273 INFO  [org.apache.activemq.artemis.core.server] AMQ221013: Using NIO Journal
23:29:36,337 INFO  [org.apache.activemq.artemis.core.server] AMQ221043: Protocol module found: [artemis-server]. Adding protocol support for: CORE
23:29:36,343 INFO  [org.apache.activemq.artemis.core.server] AMQ221043: Protocol module found: [artemis-amqp-protocol]. Adding protocol support for: AMQP
23:29:36,357 INFO  [org.apache.activemq.artemis.core.server] AMQ221043: Protocol module found: [artemis-hornetq-protocol]. Adding protocol support for: HORNETQ
23:29:36,360 INFO  [org.apache.activemq.artemis.core.server] AMQ221043: Protocol module found: [artemis-openwire-protocol]. Adding protocol support for: OPENWIRE
23:29:36,489 INFO  [org.apache.activemq.artemis.core.server] AMQ221043: Protocol module found: [artemis-stomp-protocol]. Adding protocol support for: STOMP
23:29:36,995 INFO  [org.apache.activemq.artemis.core.server] AMQ221003: trying to deploy queue jms.queue.DLQ
23:29:37,064 INFO  [org.apache.activemq.artemis.core.server] AMQ221003: trying to deploy queue jms.queue.ExpiryQueue
23:29:37,193 INFO  [org.apache.activemq.artemis.core.server] AMQ221020: Started Acceptor at 0.0.0.0:61616 for protocols [CORE,AMQP,HORNETQ,STOMP,OPENWIRE]
23:29:37,197 INFO  [org.apache.activemq.artemis.core.server] AMQ221020: Started Acceptor at 0.0.0.0:5445 for protocols [HORNETQ,STOMP]
23:29:37,199 INFO  [org.apache.activemq.artemis.core.server] AMQ221020: Started Acceptor at 0.0.0.0:5672 for protocols [AMQP]
23:29:37,202 INFO  [org.apache.activemq.artemis.core.server] AMQ221020: Started Acceptor at 0.0.0.0:61613 for protocols [STOMP]
23:29:37,204 INFO  [org.apache.activemq.artemis.core.server] AMQ221007: Server is now live
23:29:37,204 INFO  [org.apache.activemq.artemis.core.server] AMQ221001: Apache ActiveMQ Artemis Message Broker version 1.0.1-SNAPSHOT [nodeID=ec9eebc2-0a69-11e5-8817-db258e48d4cb] 
Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/http/HttpSessionIdListener
	at org.eclipse.jetty.server.session.SessionHandler.<clinit>(SessionHandler.java:54)
	at org.eclipse.jetty.servlet.ServletContextHandler.newSessionHandler(ServletContextHandler.java:241)
	at org.eclipse.jetty.servlet.ServletContextHandler.getSessionHandler(ServletContextHandler.java:334)
	at org.eclipse.jetty.servlet.ServletContextHandler.relinkHandlers(ServletContextHandler.java:180)
	at org.eclipse.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:157)
	at org.eclipse.jetty.webapp.WebAppContext.<init>(WebAppContext.java:253)
	at org.eclipse.jetty.webapp.WebAppContext.<init>(WebAppContext.java:201)
	at org.apache.activemq.artemis.component.WebServerComponent.deployWar(WebServerComponent.java:100)
	at org.apache.activemq.artemis.component.WebServerComponent.configure(WebServerComponent.java:59)
	at org.apache.activemq.artemis.cli.commands.Run.execute(Run.java:76)
	at org.apache.activemq.artemis.cli.Artemis.main(Artemis.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.activemq.artemis.boot.Artemis.main(Artemis.java:116)
Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpSessionIdListener
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more
```

**Comment by johnament** [comment]
@clebertsuconic  ah -ha, that's the question I had on the mailing list as well.  I'll take a look this evening.

**Comment by johnament** [comment]
Ok, this is the best I can do.  Let me know your thoughts.  It looks like there is no geronimo spec jar for servlet 3.1 (which is what Jetty 9.2 is based on).  As a result I'm using Tomcat's API.

**Comment by johnament** [comment]
This is the output btw

```
Johns-MBP:bin johnament$ ./artemis create /tmp/myserver --user a --password a --allow-anonymous y
Creating ActiveMQ Artemis instance at: /Users/johnament/src/activemq-artemis/artemis-distribution/target/apache-artemis-1.0.1-SNAPSHOT-bin/apache-artemis-1.0.1-SNAPSHOT/bin/y

You can now start the broker by executing:  

   "/Users/johnament/src/activemq-artemis/artemis-distribution/target/apache-artemis-1.0.1-SNAPSHOT-bin/apache-artemis-1.0.1-SNAPSHOT/bin/y/bin/artemis" run

Or you can run the broker in the background using:

   "/Users/johnament/src/activemq-artemis/artemis-distribution/target/apache-artemis-1.0.1-SNAPSHOT-bin/apache-artemis-1.0.1-SNAPSHOT/bin/y/bin/artemis-service" start

Johns-MBP:bin johnament$ "/Users/johnament/src/activemq-artemis/artemis-distribution/target/apache-artemis-1.0.1-SNAPSHOT-bin/apache-artemis-1.0.1-SNAPSHOT/bin/y/bin/artemis" run
     _        _               _
    / \  ____| |_  ___ __  __(_) _____
   / _ \|  _ \ __|/ _ \  \/  | |/  __/
  / ___ \ | \/ |_/  __/ |\/| | |\___ \
 /_/   \_\|   \__\____|_|  |_|_|/___ /
 Apache ActiveMQ Artemis 1.0.1-SNAPSHOT


09:32:48,715 INFO  [org.apache.activemq.artemis.integration.bootstrap] AMQ101005: Using broker configuration: xml:/Users/johnament/src/activemq-artemis/artemis-distribution/target/apache-artemis-1.0.1-SNAPSHOT-bin/apache-artemis-1.0.1-SNAPSHOT/bin/y/etc/bootstrap.xml
09:32:49,197 INFO  [org.apache.activemq.artemis.integration.bootstrap] AMQ101000: Starting ActiveMQ Artemis Server
09:32:49,226 INFO  [org.apache.activemq.artemis.core.server] AMQ221000: live Message Broker is starting with configuration Broker Configuration (clustered=false,journalDirectory=../data/journal,bindingsDirectory=../data/bindings,largeMessagesDirectory=../data/large-messages,pagingDirectory=../data/paging)
09:32:49,256 INFO  [org.apache.activemq.artemis.core.server] AMQ221013: Using NIO Journal
09:32:49,304 INFO  [org.apache.activemq.artemis.core.server] AMQ221043: Protocol module found: [artemis-server]. Adding protocol support for: CORE
09:32:49,310 INFO  [org.apache.activemq.artemis.core.server] AMQ221043: Protocol module found: [artemis-amqp-protocol]. Adding protocol support for: AMQP
09:32:49,322 INFO  [org.apache.activemq.artemis.core.server] AMQ221043: Protocol module found: [artemis-hornetq-protocol]. Adding protocol support for: HORNETQ
09:32:49,325 INFO  [org.apache.activemq.artemis.core.server] AMQ221043: Protocol module found: [artemis-openwire-protocol]. Adding protocol support for: OPENWIRE
09:32:49,448 INFO  [org.apache.activemq.artemis.core.server] AMQ221043: Protocol module found: [artemis-stomp-protocol]. Adding protocol support for: STOMP
09:32:49,786 INFO  [org.apache.activemq.artemis.core.server] AMQ221003: trying to deploy queue jms.queue.DLQ
09:32:49,841 INFO  [org.apache.activemq.artemis.core.server] AMQ221003: trying to deploy queue jms.queue.ExpiryQueue
09:32:49,958 INFO  [org.apache.activemq.artemis.core.server] AMQ221020: Started Acceptor at 0.0.0.0:61616 for protocols [CORE,AMQP,HORNETQ,STOMP,OPENWIRE]
09:32:49,960 INFO  [org.apache.activemq.artemis.core.server] AMQ221020: Started Acceptor at 0.0.0.0:5445 for protocols [HORNETQ,STOMP]
09:32:49,962 INFO  [org.apache.activemq.artemis.core.server] AMQ221020: Started Acceptor at 0.0.0.0:5672 for protocols [AMQP]
09:32:49,964 INFO  [org.apache.activemq.artemis.core.server] AMQ221020: Started Acceptor at 0.0.0.0:61613 for protocols [STOMP]
09:32:49,965 INFO  [org.apache.activemq.artemis.core.server] AMQ221007: Server is now live
09:32:49,965 INFO  [org.apache.activemq.artemis.core.server] AMQ221001: Apache ActiveMQ Artemis Message Broker version 1.0.1-SNAPSHOT [nodeID=3152ec3a-0abe-11e5-8864-d7826e0e18e3] 
HTTP Server started at http://localhost:8161
```

Seems like there might be an error (mac only?) where the output folder is taking "y" instead of "/tmp/myserver"

**Comment by clebertsuconic** [comment]
the allow anonymous is a boolean property, and it's not possible to pass y / n.. it was a mistake...

The CLI then took the Y as an argument.

**Comment by johnament** [comment]
@clebertsuconic yep that was the issue.  Removed the y and its doing the right thing now.

**Comment by clebertsuconic** [comment]
Will get this merged.. thanks a Lot John

**Pull request closed without merging**
