### PR TITLE
Manage client objects

### PR DESCRIPTION
**Pull request by mtaylor**
This patch adds views for managing client objects from the console.  Filtering and paging is enabled.  There are still some improvements that can be made such as more optimising filters, more filtering operations and some code restructure.  However, this is already 3 huge commits, I'd like to get this in and improve iteratively on master.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
Everything looks great here.. only thing is the temporary destinations (think of request/response).

**Comment by michaelandrepearce** [comment]
Think you should leave out the re-theme for now (this should be separate PR), lots of CSS issues on position and alignment, and font sizing.

**Comment by mtaylor** [comment]
Pulled out the retheme.  Will open a separate PR.  @michaelandrepearce  pointed out an issue with the producer address filter.  Will fix that up now.

**Comment by mtaylor** [comment]
Fixed the filter on producer address.

**Comment by michaelandrepearce** [comment]
+1, as discussed further bits can be in follow up PR's

**Comment by clebertsuconic** [comment]
@andytwylor this was Merged with a bug I mentioned earlier.

**Comment by clebertsuconic** [comment]
@andytaylor

**Comment by andytaylor** [comment]
@clebertsuconic I dont see mention of a bug?

**Comment by mtaylor** [comment]
@andytaylor I think what @clebertsuconic is referring to is this comment: 

"only thing is the temporary destinations (think of request/response)."

I had with @clebertsuconic who mentioned there may be a leak with addProducer() when using temporary destinations.  i.e. the producer may not be removed.  @andytaylor This something you could look at?

**Comment by clebertsuconic** [comment]
It wasn't a bug till you Merged it... now temporary queues are not so temporary ;)

You need to listen for temp queue removes and remove the producer upon temporary queue removal.  


No need to open a JIRA for that.  Just use this one.  



But we can't release with that.  It is a reason for -1

**Comment by mtaylor** [comment]
@clebertsuconic I will fix it before we release.

**Comment by mtaylor** [comment]
@clebertsuconic I had a quick scout over the code.  Can you elaborate a little.  I think you are referrign to the add/removeProducers since this is the only new object that was added.  Right now this is only used in two places.  In CORE on session create (the producer is added to the newly created session) and in AMQP on linkAttach/Detach.  Is there a place where add occurs but remove does not?

**Comment by clebertsuconic** [comment]
@mtaylor if I use the session to send on multiple addresses, aren't you creating more producers?

**Comment by mtaylor** [comment]
No.  This is a 1st step simple implementation.  For the CORE protocol a producer is simply represented as the defaultAddress on the session and nothing more.  In subsequent versions I intend to add a producer object to the CORE protocol.  But that requires significant change that goes beyond this PR.

**Comment by clebertsuconic** [comment]
@mtaylor  I see.. it's fine then.. sorry for the red herring.. I thought it was creating a leakage.

in case you implement new producers for new packets coming... then you would need to cleanup temporary queues.

**Pull request merged**
