### PR TITLE
ARTEMIS-1904 Jmx Management Security Tests

### PR DESCRIPTION
**Pull request by gaohoward**
* Added tests for jmx security
* Removed ArtemisRMIServerSocketFactory as it does nothing special
  (instead use default factory from jdk)

### CODE REVIEW

**Comment by gaohoward** [comment]
@mtaylor ok, will do another jira. The code change is to remove the RMIServerSocketFactory because it does nothing special and it causes jmx client fail to connect (don't know why, perhaps we didn't implement it right).

**Comment by gaohoward** [comment]
@mtaylor I've created another jira (ARTEMIS-1916) and the PR
https://github.com/apache/activemq-artemis/pull/2128
I also updated this PR. This PR should be merged after ARTEMIS-1916 (otherwise the test 
is failing).

**Comment by gaohoward** [comment]
@mtaylor worked with Andy and figured out ARTEMIS-1916 is not valid (PR will be discarded). I've fixed the test and it should be ready for review now.

**Comment by gaohoward** [comment]
@mtaylor I've added some ssl test.

**Comment by michaelandrepearce** [comment]
@gaohoward I'm going to close this as its over a year old with no activity, and has merge conflicts. please feel free to reopen if you still need this and merge conflicts are resolved.

**Pull request closed without merging**
