### PR TITLE
ARTEMIS-758 - List/Object message sent by OpenWire JMS client can't b…

### PR DESCRIPTION
**Pull request by andytaylor**
…e consumed with other clients

https://issues.apache.org/jira/browse/ARTEMIS-758

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@andytaylor this actually broke a TestConversion test.

Wouldn't this break compatiblity if something is already stored on the journal?

**Comment by andytaylor** [comment]
Ive fixed the test.

yes it would, Im not sure how we can address this but it needs fixing for cross protocol to work.

**Comment by tabish121** [comment]
Why are ObjectMessage being deserialized on the server when passing from OpenWire to AMQP would be my first question.

**Comment by andytaylor** [comment]
this is for proton-j so it can be wrapped in an amqpvalue before delivery

**Comment by clebertsuconic** [comment]
If not fixable, I would add release notes to export / import data between the releases if you are storing ObjectMessages that were sent by the affected protocols.

**Comment by tabish121** [comment]
A JMS Message sent for OpenWire / Core or wherever should contain a Binary message body and that value can just be placed directly into a Data value as the original Binary without need to decode it.  As an extra nicety you can throw in the 'application/x-java-serialized-object' content type value and then for things like Qpid JMS that understand that you'd get an ObjectMessage out on the client's consumer and treat the same as any other JMS client getting an ObjectMessage by calling getObject and hoping you had the right classes on the Classpath

**Comment by andytaylor** [comment]
@tabish121 Artemis is doing pretty much the same as ActiveMQ was until you're refactoring around proton-j. We should probably try to do the same but this should suffice until then

**Comment by andytaylor** [comment]
fixed checkstyle errors

**Comment by mtaylor** [comment]
The issue aiui is that the CORE object message encoding adds some additional data to the serialized byte stream received from the client, it prepends the byte with the length of the binary, I presume this was used in the past when reading the binary back from the Journal.   The problem with just dumping the byte stream as we were doing previously, is that there's a different encoding for CORE vs OpenWire.  This small changes ensures that both encodings are the same.  

Another way to approach this would have been to add some extra meta-data to the message describing it's content as @tabish121 mentioned with the "'application/x-java-serialized-object" type or something similar.  I think we can do that as part of the larger task of removing the translations.  Right now though, this small change fixes the cross protocol issue.

**Comment by clebertsuconic** [comment]
I will merge this now as I will change checkstyle

**Pull request closed without merging**
