### PR TITLE
Add page decoding test for large message …

### PR DESCRIPTION
**Pull request by soul2zimate**
…with no persistence

### CODE REVIEW

**Comment by clebertsuconic** [comment]
You shouldn’t reference an external JiRA on a commit.

**Comment by soul2zimate** [comment]
I updated commit message and PR title.

**Comment by soul2zimate** [comment]
It was from downstream change, I removed the cherry-pick from commit message and PR description.

**Comment by franz1981** [comment]
@soul2zimate I see that there are yet references to downstream repos on the description of the PR, please remove them

**Comment by soul2zimate** [comment]
OK, all downstream references are removed.

**Comment by michaelandrepearce** [comment]
@soul2zimate looks like PR build failed, but this i believe is one of the "tempremental" tests we have in the suite, so unrelated to this change, could you do a forced update/push to trigger another build just so we have one green build before merge.

**Comment by soul2zimate** [comment]
it all passed now.

**Pull request closed without merging**
