### PR TITLE
ARTEMIS-480 BridgeReconnectTest.testDeliveringCountOnBridgeConnection…

### PR DESCRIPTION
**Pull request by iweiss**
…Failure fails due to racing condition

Signed-off-by: Ingo Weiss <ingo@redhat.com>

### CODE REVIEW

**Comment by clebertsuconic** [comment]
can you please amend your commit and remove the comment about the sign of?

You already have your git commit authorship.

**Comment by iweiss** [comment]
Should be OK now

**Comment by clebertsuconic** [comment]
actually.. it's messy...

you should have ammended the commit and push -f y our repo.. you have 4 commits for this including a merge branch commit

**Comment by clebertsuconic** [comment]
Leave it with me, I will fix it during merge

**Comment by clebertsuconic** [comment]
I don't think the change is right anyways...

incDelivering is called only after handled...

The testcase is playing with cancellations and crashes. Perhaps there's a situation where the decDelivering should be called (after some specific crash or something).. but that would be a corner case.

Having this fix here might fix the testcase but break other production cases. Needs an overall thinking

**Comment by iweiss** [comment]
Done. 1 commit. Sorry about the trouble.

**Comment by iweiss** [comment]
retest this please

**Comment by iweiss** [comment]
Something's off with the latest Jenkins validation. It seems to have finished and succeeded.

**Comment by clebertsuconic** [comment]
please rebase your branch and push -f after rebased.. there's 2 merge committs on your branch what would be quite bad if someone merged this by accident.

**Comment by clebertsuconic** [comment]
I actually did it myself through an intermediate branch... nice job on finding this one.. thanks!

**Pull request closed without merging**
