### PR TITLE
ARTEMIS-200 Message Compression Support

### PR DESCRIPTION
**Pull request by gaohoward**

### CODE REVIEW

**Comment by gaohoward** [comment]
ok. I'll close it and work on it tomorrow. 
The test is MessageCompressionTest. The compression/decompression all happens at client side.

**Comment by clebertsuconic** [comment]
@gaohoward  you didn't need to close the PR, you could just have rebased it.. and we would merge it when it's done.

**Comment by gaohoward** [comment]
ah sorry clebert. I'll reopen this. What I'm planning to add is:
1. when deliver the message to non-openwire clients, the broker will decompose it as if it's a normal message.
2. writing some inter-protocol message tests as you suggested.

**Comment by gaohoward** [comment]
Please don't merge until I finish. Thanks

**Comment by clebertsuconic** [comment]
1. I don't think you can do that.. the message is usually converted to regular format as the message is received on the server. You will have to uncompress the message during conversion.
2. I suspect this would fail with these changes.

**Comment by gaohoward** [comment]
You are right clebert, I found it'd better be decompressed into regular messages before going into core, otherwise the core will have to change a lot to handle it properly. 
So far I have openwire-core test almost pass (one type of messages is failing due to some bug, I'm looking into it now). Then I'll write openwire-amqp, openwire-stomp and openwire-mqtt tests.

**Comment by clebertsuconic** [comment]
You just need to test it once.. between openwire<->core...   the others should be right by transitivity... you just need to test between openwire compressed and core

**Comment by gaohoward** [comment]
ok got it. Thanks.

**Comment by gaohoward** [comment]
Hi clebert, it's strange the protonTest failed in this build. I don't think my changes affect that. My local build is all fine. Anyway can you take a look of my new code changes?

Thanks

**Comment by clebertsuconic** [comment]
I will do it after the next release cut.. on which case you will need to rebase your PR

**Comment by gaohoward** [comment]
ok.

**Comment by clebertsuconic** [comment]
@gaohoward  can you rebase your branch after the release? 
I have run the fast tests on your branch and it was ok.. it's probably an intermittent failure on ProtonTest non related to your commit...


But I also need you to rebase since all the changes.. that will kick another test.. I will merge this tomorrow...



Please.. let me merge this.. I want to take a look at something.

**Comment by gaohoward** [comment]
ok, thanks clebert.

**Comment by clebertsuconic** [comment]
I'm running a few tests with your commit, if everything is ok, I will merge it tomorrow morning with a rebase.

**Comment by gaohoward** [comment]
ok

**Pull request merged**
