### PR TITLE
ARTEMIS-2291 Added test for ClassCastException on JMSBridgeImpl::stop

### PR DESCRIPTION
**Pull request by franz1981**

### CODE REVIEW

**Comment by franz1981** [comment]
@clebertsuconic @jbertram 
I'm not very happy about this test, because I've modified the running environment for different classes of tests.
I'm concerned about JMSBridgeTest, because regardless my recent changes on JMS Bridge I see different failures...are those valid tests?

**Comment by michaelandrepearce** [comment]
@franz1981  what's occurring on this one, you working on it, or is it dead and we can close for now?

**Comment by michaelandrepearce** [comment]
@franz1981 I'm closing this its really old and you never confirmed you're still working on it.

**Comment by michaelandrepearce** [comment]
feel free to re-open if you disagree.

**Pull request closed without merging**
