### PR TITLE
ARTEMIS-4962 mitigate NPE in FilterImpl

### PR DESCRIPTION
**Pull request by jbertram**

### CODE REVIEW

**Comment by gemmellr** [comment]
Change seemed ok but needed testing. I pushed another commit adding one, see what you think.

**Comment by gemmellr** [comment]
OK, my crime against spacing should hopefully be resolved now.

**Comment by jbertram** [comment]
You want me to squash these commits or just merge them as-is?

**Comment by gemmellr** [comment]
I'm fine either way, I just left it separate so it was easy to spot.

**Pull request merged**
