### PR TITLE
ARTEMIS-2052 Fixing initial credit negotiation

### PR DESCRIPTION
**Pull request by clebertsuconic**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@cshannon your last negotiation commit broke the CI. this should fix it. Can you look at it?

**Comment by cshannon** [comment]
It looks like one of tests I added in ConsumerWindowSizeTest broker....testConsumerWindowSizeAddressSettingsDifferentAddressAndQueueName

**Comment by cshannon** [comment]
The issue is here: https://github.com/apache/activemq-artemis/blob/106e71bdf4f1cf7ddf0dfc37ce6bab76d5c00dad/tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/client/ConsumerWindowSizeTest.java#L1457

That line should now change to: assertTrue(Wait.waitFor(() -> cons.getAvailableCredits().get() == consumer.getClientWindowSize() * 2, 5000, 500));

And that will fix it

**Comment by cshannon** [comment]
@clebertsuconic - besides the test fix it looks good to me, thanks for fixing it

**Pull request merged**
