### PR TITLE
fix some eclipse raw types warnings

### PR DESCRIPTION
**Pull request by grandinj**
in the process improving the type signature of getPrincipalsInRole, which was returning a Set<RolePrincipal>, but was adding things from createGroupPrincipal to the set, and createGroupPrincipal can return an object that only implements Principal, not RolePrincipal.

### CODE REVIEW

**Comment by grandinj** [comment]
Note that I already have an Apache committer license thingy on file (I was a maintainer on Apache Pivot)

**Comment by gaohoward** [comment]
looks fine.

**Comment by michaelandrepearce** [comment]
@grandinj looks fine to me also, could you just do a forced push on your PR to make the PR build kick off again, seems the PR build didn't complete. Also whilst at it, could you either create a JIRA and put a JIRA number in the commit title, or add NO-JIRA to it, im fine with either as this is more about just code formatting.

**Comment by grandinj** [comment]
hmm, I've updated the commit title, 
and I've done a forced update (after doing a merge and realising I was on the wrong track), but it doesn't look like that triggered a build?

**Comment by michaelandrepearce** [comment]
@grandinj i think the PR build issues are resolved, sorry if its a pain, could you just force update to make it trigger again?

**Comment by grandinj** [comment]
really sorry, but I've already blown away my environment, might as well just close this, not that important

**Pull request closed without merging**
