### PR TITLE
ARTEMIS-2095 - Typed Properties ThreadSafety

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Add Concurrency Test to expose concurrency errors seen in logs.
Add Fix to ensure TypedProperties to ensure threadsafety
Add forEach and forEachKey to allow for provide a thread safe way of iterating through keys and values, without needing to duplicate the collection.
Add getMapNames method to remove code duplication and to ensure thread safe

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
@franz1981 so it looks like stampedlock unless using optimistic read, (which we cant in this case), doesn't play nice with dual socket's, i guess something with all of last year cpu security issues.

Anyhow heres alternative fix to address concurrency issues.

**Comment by jbertram** [comment]
Looks like this needs to be rebased now since another PR was merged which also changes `artemis-protocols/artemis-amqp-protocol/src/main/java/org/apache/activemq/artemis/protocol/amqp/converter/AmqpCoreConverter.java`.

**Comment by michaelandrepearce** [comment]
grrrrrr..... (makes that change makes cherry picking fun)

**Comment by michaelandrepearce** [comment]
Whilst its fresh, i made the cherry pick ready here: https://github.com/apache/activemq-artemis/pull/2333

**Comment by michaelandrepearce** [comment]
@jbertram have you pr'd your fix for the packet issue? I couldnt find it in the commits

**Pull request merged**
