### PR TITLE
ARTEMIS-1655 TransportConfiguration - only encode non-null values

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Check for null, to avoid encoding issue, this is seen on failover.

### CODE REVIEW

**Comment by franz1981** [comment]
@michaelandrepearce If it ok I will going to merge it or you do it by yourself?

**Comment by michaelandrepearce** [comment]
@franz1981 if you want to have the honor I’m more than happy letting you merge :)

**Comment by franz1981** [comment]
@michaelandrepearce As soon as the checks will pass (if jenkins behave normally!!) I will merge it :+1:

**Comment by michaelandrepearce** [comment]
@franz1981 can you just wait actually, ive jsut seen something, i want to recheck.

**Pull request closed without merging**
