### PR TITLE
ARTEMIS-4913 provide more details on error callbacks

### PR DESCRIPTION
**Pull request by jbertram**

### CODE REVIEW

**Comment by tabish121** [comment]
This one needs some touch ups now as it has come conflicts

**Comment by jbertram** [comment]
@tabish121, conflicts resolved.

**Comment by gemmellr** [comment]
Some off the changes add file names to the error messages...can those message ever make it out to a client? Might not want to be passing filenames if it could?

**Comment by tabish121** [comment]
> Some of the changes add file names to the error messages...can those message ever make it out to a client? Might not want to be passing filenames if it could?

It looks like some of the existing loggers already do add filenames for a quick scan.

**Comment by jbertram** [comment]
I don't see any places where callbacks are sending these error messages back to clients. It's all for server-side logging as far as I can tell.

**Pull request merged**
