### PR TITLE
ARTEMIS-1985: Switch from XA_RDONLY to XA_OK as return value for prepare transaction via OpenWire

### PR DESCRIPTION
**Pull request by graben**
@clebertsuconic : Feedback for possible test cases needed (https://issues.apache.org/jira/browse/ARTEMIS-1985)

### CODE REVIEW

**Comment by graben** [comment]
@clebertsuconic : Friendly reminder :-)

**Comment by clebertsuconic** [comment]
@graben I wasn't sure what to do with this since there's no test.. I have no idea how to validate it yet.

do you have any parallels to compare what would be the proper return.

I know it's hard to test this since it needs a TM.. etc...

**Comment by graben** [comment]
Yes, I commented in Jira that either via core protocol (Artemis) and ActiveMQ are returning XA_OK. Actually all events only get prepared and therefor data loss. My test case (simple program) only needs a few lines for the tm. I'm using geronimo tm which is easy to init.

**Comment by clebertsuconic** [comment]
ok.. merging .. thanks for clarifying.. I have hard a hard time following so many emails :)

**Comment by clebertsuconic** [comment]
pulled it into 2.6.x

**Pull request closed without merging**
