### PR TITLE
NO-JIRA fixing master

### PR DESCRIPTION
**Pull request by michaelandrepearce**

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
This is a fix, as PR build is failing ever since https://github.com/apache/activemq-artemis/pull/1683 got merged.

**Comment by jdanekrh** [comment]
The test was broken in 2013 by @jbertram 's commit https://github.com/hornetq/hornetq/pull/1879 for Jira https://issues.jboss.org/browse/HORNETQ-1411.

The relevant diff is (abbreviated)

```diff
-   private final long timeout;
+   private long timeout = HornetQDefaultConfiguration.getDefaultGroupingHandlerTimeout();
[...]
+   public GroupingHandlerConfiguration()
    {
-      this.type = type;
-      this.name = name;
-      this.address = address;
-      this.timeout = timeout;
-      if (System.getProperty(GROUP_TIMEOUT_PROP_NAME) != null)
-      {
-         this.groupTimeout = Long.parseLong(System.getProperty(GROUP_TIMEOUT_PROP_NAME));
-      }
-      else
-      {
-         this.groupTimeout = groupTimeout;
-      }
-
-      if (System.getProperty(REAPER_PERIOD_PROP_NAME) != null)
-      {
-         this.reaperPeriod = Long.parseLong(System.getProperty(REAPER_PERIOD_PROP_NAME));
-      }
-      else
-      {
-         this.reaperPeriod = reaperPeriod;
-      }
    }
```

**Comment by jdanekrh** [comment]
The test seems to have been never running (never was annotated with `@Test`, maybe previous test runner did not require it?) and nobody complained when it was broken so long ago, apparently.

I propose deleting the `SystemPropertyOverrideTest#testSystemPropertyOverride` test.

**Comment by michaelandrepearce** [comment]
@jdanekrh Clebert later fixed and re-enabled.

**Comment by jdanekrh** [comment]
Thanks, I've pulled most recent changes and now I see the fix in place.

Weird that there are some special parameters that can be configured through system properties, while most cannot... I guess somebody had reason when asking for it.

**Pull request merged**
