### PR TITLE
ARTEMIS-1467 example showing the recommended approach for migrating

### PR DESCRIPTION
**Pull request by stanlyDoge**
example showing the recommended approach for migrating messages from ActiveMQ to Artemis

### CODE REVIEW

**Comment by clebertsuconic** [comment]
you could also use export, import?

**Comment by jbertram** [comment]
I believe Clebert is referring to [this tool](https://github.com/apache/activemq-cli-tools) which can be used to export from 5.x and then the resulting XML file can be imported via the Artemis CLI.  Using these tools might be a lot simpler than the method outlined in the current PR as it can be used for all messages in all queues simultaneously rather than having to create a bridge for each queue.

**Comment by mtaylor** [comment]
@jbertram @clebertsuconic After looking at that tool it appears it's for KahaDB store only.  If this is the recommended tool going forward then I guess we need to add support for other stores such as LevelDB and JDBC.  Alternatively we could use a bridge to drain ActiveMQ 5.x into Artemis?

**Comment by tabish121** [comment]
LevelDB has been deprecated for quite some time and is not officially supported in 5.x releases any longer so I wouldn't waste time on that one.

**Comment by jbertram** [comment]
Using a bridge is a valid way to move messages between brokers so I'll go ahead and merge this one.  If we want to add another example using the export/import CLI tools later that's certainly valid as well.

**Comment by clebertsuconic** [comment]
@jbertram I didn't want to call that "The recommended approach"...

The CLI is much easier.. say you had 1000 destinations.. you would have to write a tool to write the bridges

**Comment by mtaylor** [comment]
@clebertsuconic +1.  Let's change the JIRA title.  The commit has already landed but actually the doc doesn't mention anything about recommended.

**Comment by mtaylor** [comment]
@stanlyDoge ^^

**Comment by mtaylor** [comment]
Also the example version is wrong.  It should be aligned to the parent pom version.  @stanlyDoge can you follow up please.

**Comment by jbertram** [comment]
I updated the commit message and the JIRA to clarify that this is simple **an** approach, not necessarily the recommended approach.

**Pull request closed without merging**
