### PR TITLE
ARTEMIS-702 JMS 2 spec violation for receiveBody

### PR DESCRIPTION
**Pull request by jbertram**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
I'm running a few tests.

**Comment by clebertsuconic** [comment]
This change is breaking a lot of tests I have. We can speak offline.

**Comment by clebertsuconic** [comment]
This is introducing some sort of leak. tests won't complete.

**Comment by johnament** [comment]
@clebertsuconic I'm assuming all the tests you're running are in the code base right?

**Comment by clebertsuconic** [comment]
I was running some manual tests. 

There are some tests on wildfly that I ran after updating Artemis.

**Comment by clebertsuconic** [comment]
also ran the testsuite.

**Pull request closed without merging**
