### PR TITLE
[ENTMQBR-1043] Error AMQ119034 when listing messages as JSON

### PR DESCRIPTION
**Pull request by iweiss**
Issue: https://issues.jboss.org/browse/ENTMQBR-1043

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@iweiss you're supposed to have an artemis jira instead.

**Comment by clebertsuconic** [comment]
@iweiss  you didn't need to close it.. you could have just renamed the commit.. push -f.. rename the PR.

**Comment by iweiss** [comment]
@clebertsuconic I know, but I prefer to clear things up properly :)

**Comment by iweiss** [comment]
This became https://github.com/apache/activemq-artemis/pull/1914.

**Pull request closed without merging**
