### PR TITLE
Individualizing logger.traces on server

### PR DESCRIPTION
**Pull request by clebertsuconic**

### CODE REVIEW

**Comment by mtaylor** [comment]
@clebertsuconic I see what you are trying to achieve here.  But, the JIT compiler would likely remove any string creation and method calls after it realises that the branch is never reached.  Do you have any benchmark/test you are using to see if this makes any form of performance increase?  I think it's worth investigating before we start polluting the code with all these, if(isTrace) statements.

**Comment by clebertsuconic** [comment]
@mtaylor  I haven't changed anything in that regard...


the if (isTrace) is something we have done since the ancient days... all I did was to individualize the loggers:


if you called log.trace("a" + "b" + integerSomething");

the string will be concatenated.. sent down to log.trace to only be reject in case it was not traced.


In some cases we do quite a lot of traces.. at a very down level.. so that would definitely be relevant.


It is really costly... but as I said.. I didn't change anything.. we were already checking if (isTrace) some way or the other here.

**Comment by mtaylor** [comment]
@clebertsuconic I see you're not actually adding isTrace here.  Just refactoring what is already there.  I made the assumption due to our previous conversation.  I'll merge this, I just wonder if this pattern is still relevant with cool stuff the JIT compiler can now do.  It might be worth testing/benchmarking before wrapping all our log statements.  I'll merge this as is.  Thanks.

**Comment by clebertsuconic** [comment]
@mtaylor  I have done some changes after talking to jamezp

**Pull request merged**
