### PR TITLE
ARTEMIS-1276 fix JmsSendReceiveWithMessageExpirationTest

### PR DESCRIPTION
**Pull request by jdanekrh**
The JmsSendReceiveWithMessageExpirationTest#testConsumeExpiredQueueAndDlq test used to fail with

> JmsQueueCompositeSendReceiveTest>CombinationTestSupport.runBare:144->CombinationTestSupport.runBare:138->testSendReceive:86->JmsSendReceiveTestSupport.testSendReceive:
> 115->JmsSendReceiveTestSupport.assertMessagesAreReceived:156->JmsSendReceiveTestSupport.assertMessagesReceivedAreValid:176 Invalid number of messages received
> expected:<100> but was:<0>

After the changes in this PR, it is now failing with

    junit.framework.AssertionFailedError: got dlq messages 
    Expected :99
    Actual   :90

I can get it to pass if I disable prefetch, that is, I also change

```
diff --git a/tests/activemq5-unit-tests/src/test/java/org/apache/activemq/JmsSendReceiveWithMessageExpirationTest.java b/tests/activemq5-unit-tests/src/test/java/org/apache/activemq/JmsSendReceiveWithMessageExpirationTest.java
index dffd72296..3ff305810 100644
--- a/tests/activemq5-unit-tests/src/test/java/org/apache/activemq/JmsSendReceiveWithMessageExpirationTest.java
+++ b/tests/activemq5-unit-tests/src/test/java/org/apache/activemq/JmsSendReceiveWithMessageExpirationTest.java
@@ -126,7 +126,7 @@ public class JmsSendReceiveWithMessageExpirationTest extends TestSupport {
 
       Connection consumerConnection = createConnection();
       ActiveMQPrefetchPolicy prefetchPolicy = new ActiveMQPrefetchPolicy();
-      prefetchPolicy.setAll(10);
+      prefetchPolicy.setAll(0);
       ((ActiveMQConnection) consumerConnection).setPrefetchPolicy(prefetchPolicy);
       Session consumerSession = consumerConnection.createSession(false, Session.CLIENT_ACKNOWLEDGE);
       MessageConsumer consumer = consumerSession.createConsumer(consumerDestination);
```

I do not understand why prefetch breaks the test, and I do not know how to begin investigating this effectively...

### CODE REVIEW

**Comment by clebertsuconic** [comment]
it's probably an issue on the test.

should I merge this already?

**Comment by jdanekrh** [comment]
> it's probably an issue on the test.

I was not sure. The same test is passing with ActiveMQ 5.

**Comment by clebertsuconic** [comment]
the test would take the consideration the messages only expire on client on activemq5 while it's on server & client on artemis. I had seen some other tests failing because of that.. wrong assertions.

**Comment by jdanekrh** [comment]
> messages only expire on client on activemq5 while it's on server & client on artemis

Did you mean expire on _server_ on activemq5? If it expired on client, how would it then get to DLQ queue on server?

---

I think get it now. When the test receives for the first time (first `for` loop), the client gets first 10 messages sent, which are those with short expiration time. One of them is delivered ok, the 9 remaining expire on the client while it is in sleep(). That means these 9 never get into the DLQ, because for that they would have to expire on the server. Which explains the `actual: 90, expected: 99` result when it is then receiving from DLQ.

I did not know about this difference between 5 and Artemis.

From user point of view, the fact that prefetch changes behavior (and is not just performance optimization) and that it can cause what can be thought of as a message loss (these 9 messages have irrevocably disappeared, right?) could be considered a bug, I think.

I guess there is nothing to be done about it here, so removing [wip].

**Comment by clebertsuconic** [comment]
>>> If it expired on client, how would it then get to DLQ queue on server?

There's a special protocol on OpenWire to tell the server the message expired. On Artemis we would just reject the message and let the server deal with it again.

Having said that, perhaps there's something wrong on treating that message..so it's worth to check if it's a bug on that area.. or just a test issue.

I didn't look into the details specifically to this test BTW: I was just mentioning that I had cases like this where I had to tweak the test because of that semantic change.

**Comment by jdanekrh** [comment]
Right. Yeah, I think this one is actual OpenWire handling bug in Artemis. If the message expires while it is being prefetched on client, server drops it and never tries to expire it.

i may even have a fix, but this message lifecycle is quite complicated, so it is likely I am missing something...

```diff
--- a/artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQConsumer.java
+++ b/artemis-protocols/artemis-openwire-protocol/src/main/java/org/apache/activemq/artemis/core/protocol/openwire/amq/AMQConsumer.java
@@ -298,8 +298,9 @@ public class AMQConsumer {
          }
       }
       if (ack.isExpiredAck()) {
-         //adjust delivering count for expired messages
-         this.serverConsumer.getQueue().decDelivering(ackList.size());
+         for (MessageReference ref : ackList) {
+            ref.getQueue().expire(ref);
+         }
       }
    }
```

**Comment by clebertsuconic** [comment]
@jdanekrh if it's a bug on these acks, then lets kep this test the way it is then... or ammend this PR with this fix you mentioned instead. I think it's right.. we just need to run the whole testsuite on openwire and integration-tests.

**Comment by jdanekrh** [comment]
I'd prefer to put the fix into a new PR, if you don't mind. I think there is already enough things in this one already.

**Comment by clebertsuconic** [comment]
@jdanekrh sure, but I'm wondering if this test should be left alone. perhaps just fixing that would be enough to fix this test?

**Comment by jdanekrh** [comment]
The only change to test is adding line `commonSettings.setExpiryAddress(dla);` in broker creation. That causes the test to progress further (passes assert) and then the test tries to cast `Broker` it got from calling `getRegionBroker` to `RegionBroker`, so that had to be implemented (using mockito). And then it looks at statistics (messages in flight) so then I had to write a wrapper/fake/whatever-it-should-be-called for that.

**Pull request closed without merging**
