### PR TITLE
ARTEMIS-1781 Connector parameters not backward compatible

### PR DESCRIPTION
**Pull request by TomasHofman**
https://issues.apache.org/jira/browse/ARTEMIS-1781
https://issues.jboss.org/browse/ENTMQBR-1034

Fixing backward compatibility with HornetQ:
* Translate transport parameters to dash notation instead of camel-case when talking to legacy clients.
* Do not add passwordCodec parameter unless maskPassword is true.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
It would be nice to have a compatibility test added.

**Comment by TomasHofman** [comment]
@clebertsuconic could you point me to where you keep similar tests? So far I have a deal with EAP QE that they would create it for EAP.

**Comment by clebertsuconic** [comment]
@TomasHofman look under master/tests/compatiblity-tests


There are a bunch of tests where we mix different versions using classLoading and groovy to avoid syntax dependency on specific versions...


Talk to me offline (you know where to find me) if you have issues on writing one.. or if you can't for any other reason.

**Comment by clebertsuconic** [comment]
@TomasHofman  Kudos.. really nice...

i have done some tweaking though.. I'm removing TransportConstantsV2 and adding those properties directly on the Utility.. the TransportConstantsV2 name would be confusing and people would think that's the newest version to be used...

I have also split your commit into 2.. one for the tests and one for the fix... but I kept you the authorship.


I'm merging these myself as I don't see a point on going back and forth asking you to make these chagnes as I have them already...

I will apologize in advance as I'm pushing I change I made into your commit (removing the V2 class) but the github would be simpler if I amended my change into yours.. consider it like I have asked you to make the change and it's been done..


I'm merging it now.. but please check if you see anything wrong after I merged it.

**Comment by clebertsuconic** [comment]
the only reason I splitted into two commits is because it would be simpler to verify the fix.

Again.. thanks a lot for this.

**Pull request closed without merging**
