### PR TITLE
ARTEMIS-2376 Remove guava from artemis-common feature

### PR DESCRIPTION
**Pull request by graben**

### CODE REVIEW

**Comment by graben** [comment]
Hi @clebertsuconic,
may you have a look on this?
Thx Benjamin

**Comment by jbonofre** [comment]
I can take a look.

**Comment by graben** [comment]
@jbonofre Merci :)

**Comment by clebertsuconic** [comment]
@jbonofre  / @graben  this is an area that my co-worker, @brusdev  recently touched

**Comment by brusdev** [comment]
@graben why do you remove guava bundle dependency from artemis-common?

**Comment by brusdev** [comment]
@graben why do you remove guava bundle dependency from artemis-common?

**Comment by graben** [comment]
@brusdev : Because it isn't used/needed anymore and therefore reduces maintenance in custom Karaf distribution if several guava versions are bundled. Actual used version 18 is quite old and has known security issues!

**Comment by jbonofre** [comment]
If Guava is not used, it makes sense to remove it (I will double check). Furthermore, Guava 18 is old and contains CVE issue.

**Comment by clebertsuconic** [comment]
I can't merge it right away as my workspace is messed up.. but I will do it shortly.

**Pull request closed without merging**
