### PR TITLE
[ARTEMIS-3700]: Provinding a JakartaEE 10 implementation.

### PR DESCRIPTION
**Pull request by ehsavoie**
* Upgrading the API to Jakarta Messaging 3.1.0
* Updating the metadata to 3.1.0

Jira: https://issues.apache.org/jira/browse/ARTEMIS-3700

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@ehsavoie it seems the API Is not available on maven.

Can you rebase and push -f so this gets executed again?

**Comment by ehsavoie** [comment]
@clebertsuconic it is not available until the official release (next week should be ok)

**Comment by ehsavoie** [comment]
thanks @gemmellr :)

**Comment by ehsavoie** [comment]
Well there was not conflict wit the current main so i didn't rebase :)  but i didn't know how to relaunch the CI.

**Comment by gemmellr** [comment]
> Well there was not conflict wit the current main so i didn't rebase :) 

PR commits always get rebased for artemis so its best if you do so its up to date.

> but i didn't know how to relaunch the CI.

By pushing an update :)

**Comment by clebertsuconic** [comment]
@ehsavoie easiest way:

git pull --rebase upstream main
git push origin <your-branch-name>  -f


if you did not have an update from main (still rebase):


git commit --amend
git push origin -f


that will update the commit ID and make the build to re-launch

**Comment by gemmellr** [comment]
I didnt (dont have write access set up), Emmanuel had pushed when commenting about previously not.

**Comment by clebertsuconic** [comment]
@gemmellr Ohhh.. I thought he was asking to relaunch the jobs... sorry I misunderstood what he meant.. I was fast reading all my emails and I misunderstood it.. my bad.

**Pull request merged**
