### PR TITLE
ARTEMIS-2125 Tabs preference changes to display columns not persistent through page refresh

### PR DESCRIPTION
**Pull request by franz1981**

### CODE REVIEW

**Comment by franz1981** [comment]
@tadayosi Please take a look if it is similar to what you have done on queues...and thanks for the PR :+1:

**Comment by tadayosi** [comment]
Thanks @franz1981. This looks great!

**Comment by michaelandrepearce** [comment]
Lgtm

**Comment by andytaylor** [comment]
looks good I will merge.

**Comment by franz1981** [comment]
@andytaylor thanks!! I will cherry-pick into 2.6-x too :+1:

**Pull request merged**
