### PR TITLE
ARTEMIS-1606 - Change AddressInfo RoutingType Set to use EnumSet

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Change all use from Set`< RoutingType >` to `EnumSet<RoutingType>`
Deprecating any old exposed interfaces but keeping for back compatibility.
Address info to avoid iterator on getRoutingType hotpath, like wise can be avoided where single RoutingType is passed in.

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
@franz1981 ping.

**Comment by franz1981** [comment]
@michaelandrepearce 
Looking at the changes via Github it seems clean and effective and I admit I'm a fan of using the "right" collection when needed, but I want to use some time tomorrow to check the code locally too and run some CI tests on it: similar to `SimpleString` changes I prefer to be 100% that isn't impacting negatively with hidden behaviours

**Comment by michaelandrepearce** [comment]
@franz1981 you happy for this to merge?

**Comment by franz1981** [comment]
@michaelandrepearce I'm looking at it locally right now :+1:

**Comment by cshannon** [comment]
This looks good to me too

**Comment by jbertram** [comment]
Any metrics to quantify the benefit and justify this change?

**Comment by michaelandrepearce** [comment]
Sure, using JMH to measure performance of the two AddressInfo Implementations.

Benchmark                            Mode  Cnt          Score        Error  Units
MyBenchmark.testEnumSetAddressInfo  thrpt  200  198607467.630 ± 507344.268  ops/s
MyBenchmark.testHashSetAddressInfo  thrpt  200   22849376.205 ± 216480.582  ops/s

This is simulating what happens in the hotpath of sending a message in doSend within ServerSessionImpl. Which is creating an AddressInfo and then getRoutingType.

As you note the throughput is an order of magnitude of 8x.


Also from a java memory footprint this is far better.

AddressInfo using HashSet  with one routing type -> 208 bytes
AddressInfo using HashSet with two routing types -> 240 bytes

AddressInfo using EnumSet with one routing type -> 72 bytes
AddressInfo using EnumSet with two routing types -> 72 bytes

**Comment by jbertram** [comment]
Thanks, @michaelandrepearce. Nice results!

**Comment by franz1981** [comment]
Very good results! A lil OT but seems that we really start need  a JMH folder with all the benchs on Artemis eh? :P

**Comment by michaelandrepearce** [comment]
@franz1981 i was waiting on you, to give a thumbs up before i merged, is that a thumbs up?

**Comment by franz1981** [comment]
@michaelandrepearce I'm running a test before and after, but first can you try add ".jvmArgs("-XX:+UseG1GC")" and `.forks(2)` to your benchmark?

**Comment by franz1981** [comment]
These are the flamegraph of a couple of profiled tests, one on master:
image
Where the violet bars are the `AddressInfo::new` and the `AddressInfo::getRoutingType` (+ iterator) while with this PR:
image
There isn't anymore any cost associated with `AddressInfo`: for me is a thumbs up!
Althouh it seems negligible (at a first look) the impact of this change has changed the garbage produced and the CPU time required to call `doSend`: indeed the latencies are better too.
Well done :100:

**Comment by michaelandrepearce** [comment]
Great thanks, ill merge then.

**Pull request closed without merging**
