### PR TITLE
Fix for ARTEMIS-362

### PR DESCRIPTION
**Pull request by l-dobrev**
Fix for https://issues.apache.org/jira/browse/ARTEMIS-362

### CODE REVIEW

**Comment by clebertsuconic** [comment]
I would like to see a description on the commit about what is being changed...

It's fairly common having to do a git log to figure out when things got broken... and having to open the JIRA to see what happened is not very practical.


I can change the commit description before merging though if you don't mind... but if you can ammend with a description such as 

___
ARTEMIS-362 Only sending UDP packets bytes as needed

You can use the next lines to explain things.. etc...
_____


Looking at the website (JIRA on this case) should be an extra step to eventually look for discussions.

**Comment by l-dobrev** [comment]
Amended.
How's that?

**Comment by clebertsuconic** [comment]
much better.. thanks

**Comment by clebertsuconic** [comment]
It seems nice and clear to be merged.. but I am running the entire testsuite on my box before merging this.. .just to be safe.

**Pull request closed without merging**
