### PR TITLE
ARTEMIS-1675 Adding --safe option on print-data

### PR DESCRIPTION
**Pull request by clebertsuconic**
This is good when you are a customer and an artemis engineer (e.g. me) asks your journal print-data but you can't do it because that would expose your user's data. If you do artemis data print --safe, that will only expose the journal structure without exposing user's data and eliminate any liability between the engineer and users.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@michaelandrepearce I think you would like this one. I talked to you in person about it.

**Comment by jbertram** [comment]
Checkstyle violation in CoreMessage - extra space before the final semicolon.

**Comment by clebertsuconic** [comment]
@jbertram i fixed while I merged it

**Comment by clebertsuconic** [comment]
damn.. I think I had closed this...


I will fix this.

**Pull request closed without merging**
