### PR TITLE
ARTEMIS-657 Fixing JORAM AMQP Tests

### PR DESCRIPTION
**Pull request by clebertsuconic**

### CODE REVIEW

**Comment by grs** [comment]
My apologies for breaking this!

**Comment by clebertsuconic** [comment]
@grs no worries.  Dev is about that :)

I just wanted to check if you agree with this Change I made. Or if you know a better fix.

**Comment by grs** [comment]
To be perfectly honest, I don't really understand the change. (Or why it caused other tests to fail, since prior to my change the body would have simply not been encoded at all).

I get the bit that catches the exception through, which may be what fixes the test? What is the reader index stuff for?

**Comment by clebertsuconic** [comment]
@grs some tests from JORAM are apparently sending empty bodies.. what caused the issue.

I need to only perform this conversion on management operations which is what you wanted.

**Comment by grs** [comment]
Ok, I think I understand now. You are only attempting the conversion if the source message does not have the property set and additionally are catching any failure to read the body buffer as a string and resetting the buffer after any read attempt. That all makes sense to me.

**Comment by clebertsuconic** [comment]
It still failing though.

**Comment by clebertsuconic** [comment]
I had one wrong change on provider.properties.... rebased / pusehd -f... next build should have a fix.

**Pull request merged**
