### PR TITLE
ARTEMIS-735 Refactoring of JUnit Tests in artemis-rest

### PR DESCRIPTION
**Pull request by bennetelli**
The JMS class in the artemis-rest project seems to be unused.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
can you do the following commands:


```sh
git remote add upstream https://github.com/apache/activemq-artemis.git
git pull --rebase upstream master
git push origin -f
```


you should also mention the JIRA you created for refactoring on rest.


There are a couple of reviews I want to comment, but these merges you have here are reallly messed up, if you do the commands I asked these will get fixed.

**Comment by clebertsuconic** [comment]
You should make JIRA to be part of the commits... the PR name will get lost once merged.

do this:


git rebase -i HEAD~2



edit the name of these two commits and include the jira.



git push origin -f



(I don't mean to be teaching you git.. if you know these commands it's just a way to communicate, easier in git than english :) )

**Comment by clebertsuconic** [comment]
I see what you did, you changed the title of the PR. you have to change the title of the committs.. look at my previous comment.

**Comment by bennetelli** [comment]
typically I don't do those things with git. Squashing commits and working with github pull request is new to me as well. Will do it better in future. I promise ;) Thanks for your help :-) Will fix it the next days.

**Comment by jbertram** [comment]
Any update on this PR?  It not only needs to be squashed, but the commit message needs to be amended to follow the 50/72 pattern discussed in the [Hacking Guide](https://github.com/apache/activemq-artemis/blob/master/docs/hacking-guide/en/maintainers.md#commit-messages).

**Comment by bennetelli** [comment]
will take a look at this pr at thursday.

**Comment by clebertsuconic** [comment]
I fixed it myself with some git-fu while I merged it (amends and stuff)

**Comment by clebertsuconic** [comment]
I did this now since I'm about to make a release and wanted to finish most of what I could.

**Comment by bennetelli** [comment]
thanks clebert.

**Pull request closed without merging**
