### PR TITLE
ARTEMIS-129 License header should be a normal comment

### PR DESCRIPTION
**Pull request by thiagokronig**
To reproduce this commit, apply the following replace regex rule:

    search regex: /\*\*\n \* Licensed
    replace: /\*\n \* Licensed

Only .java and the following files should be modified:

    artemis-selector/src/main/javacc/HyphenatedParser.jj
    artemis-selector/src/main/javacc/StrictParser.jj
    artemis-website/src/main/resources/styles/impact/css/pygmentize.css
    artemis-website/src/main/resources/styles/impact/css/site.css

### CODE REVIEW

**Comment by clebertsuconic** [comment]
Nice one! thanks

I will wait the PR build to finish first before we can merge this

**Comment by thiagokronig** [comment]
Please, review it with some regexes and greps.

**Comment by clebertsuconic** [comment]
I will amend your commit with a comment:

s/Only .java and the following files should be modified/These files had to be modified manually

**Comment by thiagokronig** [comment]
Feel free to do so!

**Pull request closed without merging**
