### PR TITLE
ARTEMIS-1815 adding exclusive-queue example

### PR DESCRIPTION
**Pull request by pgfox**
To highlight the new exclusive queue functionality, add "exclusive-queue" example. see contained examples/features/standard/exclusive-queue/readme.md for more details.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
please, wait #2026 to be merged...

@pgfox I will need you to rebase once I merge #2026... I will let you know.

**Comment by clebertsuconic** [comment]
@pgfox please, update run-examples.sh under artemis-distribution/src/tests/script

**Comment by clebertsuconic** [comment]
@pgfox  please rebase, also add the new example under run-examples under artemis-distribution/src/test/script

**Comment by clebertsuconic** [comment]
I amended your commits before merging... 

examples are now checked for checkstyle also now :)

**Comment by pgfox** [comment]
@clebertsuconic , Thanks Clebert.

**Pull request closed without merging**
