### PR TITLE
ARTEMIS-3093 Ordering on multiple consumers

### PR DESCRIPTION
**Pull request by clebertsuconic**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
I am fixing and running tests... please, do not merge this yet.

**Comment by michaelandrepearce** [comment]
Im getting a bit of de ja vu here. Didnt alot of these changes being removed you added for something similar with ordering before?

**Comment by clebertsuconic** [comment]
We did, yeah...

What I'm doing now, is I'm always using addSorted on close / rollback.

While scheduling will still use addHead... so we won't need scheduling argument on addSorted...

I did some cleanup then on the API around it.

Back then I thought we should have kept core as it was. but I see this change on core would be better as well.

**Comment by clebertsuconic** [comment]
I will minimize the changes though... I will keep the scheduling for now

**Comment by clebertsuconic** [comment]
fixed it!

**Comment by michaelandrepearce** [comment]
Ah ok. So basically youre no longer making distinction between amqp and other clients and applying the same logic regardless. Gotcha nice. +1

**Comment by clebertsuconic** [comment]
I will wait the test results on a 3 hours run I have with the whole test suite before I merge this.

**Pull request closed without merging**
