### PR TITLE
ARTEMIS-3280 Netty Pool micrometer metric plugin

### PR DESCRIPTION
**Pull request by franz1981**
https://issues.apache.org/jira/browse/ARTEMIS-3280

### CODE REVIEW

**Comment by franz1981** [comment]
This PR is including the many tiny details exposed by the Netty metrics, but common users will probably just need `netty.pooled.used.memory` of type `direct` and `heap`

**Comment by franz1981** [comment]
@jbertram Do you think it worths to expose `netty.pooled.used.memory` with JMX as well? maybe in a separate PR?

**Review by jbertram — APPROVED** [review]

**Comment by jbertram** [comment]
@franz1981, for the sake of flexibility it would be good to support these metrics via JMX as well. JMX is still heavily used, and many users have existing infrastructure for it.

**Comment by jbertram** [comment]
Are there any Netty docs that we could link to from our docs that explain what these metrics are in more detail?

**Comment by franz1981** [comment]
@jbertram 
> Are there any Netty docs that we could link to from our docs that explain what these metrics are in more detail?
yess, on https://netty.io/4.1/api/io/netty/buffer/PooledByteBufAllocatorMetric.html

**Comment by michaelpearce-gain** [comment]
I would agree anything metrics wise, we should always seek to ensure its in JMX as then its also visible in admin console.

**Comment by jbertram** [comment]
I went ahead and merged this. We can add corresponding JMX metrics in another PR. Nice work, @franz1981!

**Pull request closed without merging**
