### PR TITLE
ARTEMIS-3402 Split Brain detection should reject bad member updates

### PR DESCRIPTION
**Pull request by franz1981**
https://issues.apache.org/jira/browse/ARTEMIS-3402

### CODE REVIEW

**Comment by franz1981** [comment]
@clebertsuconic @brusdev  that's a conservative version of the fix (still lack a test): I still don't understand
```java
         memberInput.setLive(connector);
```
code path that's going to be taken if the proposed live is `null`

**Comment by clebertsuconic** [comment]
If you tested (running the test suite) LGTM.

I feel like I missed the return on the code.

thanks for the fix.

**Comment by franz1981** [comment]
@clebertsuconic CI seems fine with this, although I've left the 
```
memberInput.setLive(connector);
```
and I would like to understand what's its purpose

**Comment by franz1981** [comment]
This is read to be reviewed now :+1:

**Comment by franz1981** [comment]
Given the comment on https://github.com/apache/activemq-artemis/pull/3672#issuecomment-887184813 I'm going to merge it after few hours: the CI is already happy with it

**Comment by clebertsuconic** [comment]
I don't remember the exact conditions I have seen on DNSSwitchTest. That was to fix the condition bought by the split brain.


I would have to debug again to give you some understanding. You could add some log.debug into that and view the information there.


as I said I'm happy with this if tests are good. Make sure you run DNSSwitchTest a couple of times manually on your laptop please.

**Pull request closed without merging**
