### PR TITLE
a few fixes

### PR DESCRIPTION
**Pull request by clebertsuconic**

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
@clebertsuconic failures look related to this PR that was merged https://github.com/apache/activemq-artemis/pull/1449

**Comment by clebertsuconic** [comment]
@michaelandrepearce I think those are env

**Comment by clebertsuconic** [comment]
do not merge this yet please

**Comment by michaelandrepearce** [comment]
@clebertsuconic agreed, since the big restart of jenkins that occured this morning, it seems to have cleared out.

**Comment by clebertsuconic** [comment]
ready to be merged.. I'm doing it myself

**Pull request closed without merging**
