### PR TITLE
Avoid array copy on STOMP encode

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by scop** [comment]
Added a few similar ones on decode side. Test suite passes for me.

**Comment by clebertsuconic** [comment]
I have merged this, but beware that I squashed your two commits into just one since they both had the same message.

**Comment by scop** [comment]
Ok, but note that the commit messages were not the same (one was encode, the other decode, and one had "some" in plural):

1) Avoid array copy on STOMP encode
2) Avoid some array copies on STOMP decode

**Comment by clebertsuconic** [comment]
Oh... ok.. too late now :) already merged!

But this will be good enough

**Pull request closed without merging**
