### PR TITLE
ARTEMIS-1436 update CLI StatQueue and console to allow greater_than/less_than

### PR DESCRIPTION
**Pull request by pgfox**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
This change warrants a JIRA with an improvement status. (it's not a feature per se... so this alone shouldn't bump the release requires into 1.5.. but it's definitely nice to have a JIRA.

Can you amend it?

**Comment by pgfox** [comment]
sure, will do that, thanks @clebertsuconic

**Comment by mtaylor** [comment]
@pgfox Nice work on this, and the previous commit.  Could you please update the console to expose the new greater/less than feature too please.  It'd be nice to see this feature also exposed in the console.

**Comment by pgfox** [comment]
@mtaylor sure, will give that go.

**Comment by pgfox** [comment]
add the greater_than/less_than only the filter objects of *.js that have numeric values to filter by

**Pull request closed without merging**
