### PR TITLE
ARTEMIS-1163 Refactory  to polimorphic creation connection factory.

### PR DESCRIPTION
**Pull request by klausboeing**
Small refactoring to make the code simpler and easier to maintain.

### CODE REVIEW

**Comment by jbertram** [comment]
Couple of things...

- I think this warrants a JIRA. Please open a JIRA at https://issues.apache.org/jira/browse/ARTEMIS with a summary of the issue. Then reference the JIRA in your commit message as described in the [Hacking Guide](https://github.com/apache/activemq-artemis/blob/master/docs/hacking-guide/en/code.md#commitMessageDetails).
- The PR build failed because you have not added @Overrides to the proper methods. See [the Maven log](https://builds.apache.org/job/ActiveMQ-Artemis-PR-Build/2993/console) of the PR build for more details.

**Comment by klausboeing** [comment]
@jbertram I made the adjustments as needed.

How will the ARTEMIS-1163 ticket be processed?

Thanks for listening.

**Comment by clebertsuconic** [comment]
Nice PR though.   Just need to make sure checkstyke is passing.

**Comment by jbertram** [comment]
@klausboeing, I'm not exactly sure what you're asking. Once the PR is merged I'll close the JIRA.

At this point you need to squash the two commits together into a single commit.

**Comment by klausboeing** [comment]
@jbertram Exactly this point I would like to know. Thank you.

**Comment by clebertsuconic** [comment]
YOu have a bit of a mess on your PR right now. you could ammend all your committs into one.. You have the initial one, then a rever, another revert (that I had some trouble rebasing)... that is.. a mess..


I could figure out how to fix it.. I will run some tests and merge it..


Tip: git rebase -i HEAD~4

git push origin <branch-name> -f

**Pull request closed without merging**
