### PR TITLE
[ARTEMIS-506] PagingTest#testDeletePhysicalPages fails

### PR DESCRIPTION
**Pull request by gaol**
Jira: https://issues.apache.org/jira/browse/ARTEMIS-506

### CODE REVIEW

**Comment by gaol** [comment]
The CI build was aborted because of execution timeout, could someone please restart the test?

**Comment by clebertsuconic** [comment]
I'm running the whole testsuite first.

**Comment by clebertsuconic** [comment]
Please don't merge this.. let me the one merging this as I'm doing tests.

**Comment by gaol** [comment]
@clebertsuconic any news?

**Comment by clebertsuconic** [comment]
It seems this will break paging.. it's fixing a test but breaking the implementation...


I couldn't get to the bottom of it as I'm working into another possible paging issue, hence I left it in the back burners while I'm looking at this other one. (I could then find something related here)

**Comment by gaol** [comment]
Would you please tell which test it breaks if any?

This test actually reveals a failure in paging IMHO:

When `PageSubscriptionImpl.cleanupEntries(boolean)`  is called in PagingStore's executor, and one page is considered completed, then a `PAGE_CURSOR_COMPLETE` record is appended to message journal for this page in a transactional operation.

Normally, the page will be deleted after the transaction is committed by the cleanup process(`PageCursorProviderImpl.cleanup()`), then a `DeleteRecord` record is appended to the message journal for this page. Sometimes, the page won't get deleted when the PagingStore is stopped during the cleanup process. But it is fine too because the server's restart will clean up the page anyway.

Failure happens on conditions:

 * The completed page is not deleted by the cleanup process, and the `PAGE_CURSOR_COMPLETE` record survives.
 * The completed page is deleted manually after the server is stopped
 * Server is restarted, the `PAGE_CURSOR_COMPLETE` record still survivals, because there is no such page file in the paging store, and the clean up process does nothing about it.
 * Client sends many messages to the server so that the server starts to page messages to paging store, and the new page file has the same page number(like page number: 120 in this test failure) with the survival `completed` page above.

In such conditions, the new page file will be considered completed, which leads to the messages in this page file won't get consumed. It is kind of missing messages.

The fix in this PR tries to append the `DeleteRecord` record for the associated `PAGE_CURSOR_COMPLETE` record when a message is stored in a paging file and clear the `completed` flag in the `PageSubscriptionImpl.PageCursorInfo`. I think at this moment, the page should **NOT** be considered `completed`, and the completed flag should be cleared if any. I am a little confused why it breaks the implementation?

This is my first try on Artemis issue, there must be many misunderstandings, it will be very appreciated if you can give me any light on that. Thank you. :-)

**Comment by clebertsuconic** [comment]
Let me work on this in 2 days? I need to finish something else on paging before I can merge that.

**Comment by gaol** [comment]
Yes, sure. :-)

**Comment by mtaylor** [comment]
@clebertsuconic any update on this?

**Comment by clebertsuconic** [comment]
This is exactly the issue I was working against 👍  I wish I had read your PR more properly.. 

I actually did but I didn't realize it was the same issue until I hit it.


Can you evaluate my latest changes and close this? upon restart I check if there is a page complete, and I then move towards the next page. we shouldn't ever add to a page once completed.

**Comment by clebertsuconic** [comment]
@gaol  Can you review my latest changes on paging, and this can probably be closed?

**Comment by gaol** [comment]
@clebertsuconic I think the 3 lines starts from: [PageSubscriptionImpl#reloadPageCompletion()](https://github.com/apache/activemq-artemis/commit/3e2adf123b96c3dfade3d1584ea0ddf65a876941#diff-0f3a0fc675330f6da3b510a9428b6470R196) in your last changes fixed the issue.

I thought there maybe something to do within this method but not realized that the PagingStore can be used that way. :+1: 

I think this PR can be closed now.

**Pull request closed without merging**
