### PR TITLE
ARTEMIS-1346 Add initial Management Console Documentation

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Added some initial documentation

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
@clebertsuconic this is to go with the new console, I'm sure there lots more to add, but thinking it can be an initial with the first release of it.

**Comment by clebertsuconic** [comment]
@mtaylor / @michaelandrepearce  i Know Martyn is changing the console as we speak.
Shoudn't we wait his stuff before taking these pictures? just to avoid rework on these? it's almost done.

Or you guys would rather merge this now and fix it later?

**Comment by andytaylor** [comment]
Also, the console has a help.md that can be accessed in the console, could we add this there as well, maybe pull it in during the build?

**Comment by mtaylor** [comment]
I'll have a PR very soon.  If we could hold out on this for a little longer we can get some up to date pictures :).

**Comment by mtaylor** [comment]
Or take a look at my branch https://github.com/mtaylor/activemq-artemis/tree/ConsoleClientObjects

**Comment by michaelandrepearce** [comment]
I redirected/iframed the help to the actual Artemis documents

**Comment by michaelandrepearce** [comment]
Thus why adding this to the Artemis documents

**Comment by michaelandrepearce** [comment]
@mtaylor Will build your branch and take a screen shot

**Comment by michaelandrepearce** [comment]
Don't merge this yet. Will wait for the console changes to finally merge to take final screen shots.

**Comment by michaelandrepearce** [comment]
@clebertsuconic @mtaylor updated screenshot to current PR build. so this should be good now.

**Comment by michaelandrepearce** [comment]
Updated images with last update to logo, plus new plugin feature

**Pull request closed without merging**
