### PR TITLE
[ARTEMIS-1527] - [Artemis Testsuite] ActiveMQMessageHandlerTest#testS…

### PR DESCRIPTION
**Pull request by JiriOndrusek**
…erverShutdownAndReconnect fails

Issue: https://issues.apache.org/jira/browse/ARTEMIS-1527

### CODE REVIEW

**Comment by clebertsuconic** [comment]
The failover is blocking because client applications would fail and would require to block.. it's customer's code.

I reckon we could do asynchronously for MDBs or message listeners. so, how do you differentiate the two here?


I suspect Failover (FailoverTest and others on the testsuite) wouldn't work.


Also.. at least you should make this change on master.. it's a significant refactoring to make something like this to work properly. Failover itself was a pain.. making this level.. even more difficult.

**Comment by mtaylor** [comment]
@clebertsuconic The problem here is that any thread that blocks indefinitely takes up resources in the Thread pool.  If you have several threads trying reconnect, the ThreadPool may be exhausted and can not be used to perform any other tasks.  My opinion here is that no task we add to the ThreadPool should block indefinitely, for retry here we should attempt to connect, if it fails schedule another attempt connect call, and give up the thread.  Jiri's made a start on that, but we may need to flesh out some of the details.  There's a similar problem with LargeMessage receive().

**Comment by JiriOndrusek** [comment]
Thank you for your responses.

@clebertsuconic you are right, with this change FailoverTest is failing

I'll try to find solution for FailoverTest to succeed.
(it will take me some time to debug and understand it)

@clebertsuconic @mtaylor I'm opened to any suggestions, as there are a lot of aspects, about which I don't know/understand.

**Comment by JiriOndrusek** [comment]
Replaced with https://github.com/apache/activemq-artemis/pull/1761

**Pull request closed without merging**
