### PR TITLE
ARTEMIS-2602 Improve Journal loading heap usage

### PR DESCRIPTION
**Pull request by franz1981**

### CODE REVIEW

**Comment by franz1981** [comment]
I don't know why I cannot require the review from @wy96f, but I would like to ask for it :)

**Comment by franz1981** [comment]
@clebertsuconic @michaelandrepearce `LongHashSet` is a porting of https://github.com/real-logic/agrona/blob/master/agrona/src/main/java/org/agrona/collections/IntHashSet.java (and the tests too). Please recommend me the better way to deal this this :)

**Comment by michaelpearce-gain** [comment]
@franz1981 i would add the lib as a library as its avaiable as a fair small jar in maven with not much dependency, the main reasons we didnt do that with the bookeeper one was it wasn;t nicely seperated code, also we had to make some fixes

**Comment by franz1981** [comment]
@michaelpearce-gain the fact is that `LongHashMap` doesn't exists on Agrona: I've made it by myself...

**Comment by michaelandrepearce** [comment]
ah ok, gotcha i missed its not a copy, but a modifcation to use long. tbh lgtm then. as long as theres maybe a small comment in the code giving reference to original source of the idea, e.g. give credit due

**Comment by michaelandrepearce** [comment]
btw do you have any nice pretty graphs to go with this PR showing the before and after on the heap......

**Comment by franz1981** [comment]
@michaelandrepearce 
I'm producing a journal to show the improvement :)
I like the "nice pretty part" :)

**Comment by clebertsuconic** [comment]
LGTM

**Comment by clebertsuconic** [comment]
It wasn't clear it wasn't ready to me.. .please send another commit with further improvments

**Pull request closed without merging**
