### PR TITLE
ARTEMIS-1479 Set validated user in all messages

### PR DESCRIPTION
**Pull request by cburlinchon**

### CODE REVIEW

**Comment by tabish121** [comment]
There doesn't seem to be a JIRA issue associated with this, nor are there tests, or even text explaining why the change is needed.  Would be good to add those.

**Comment by cburlinchon** [comment]
Hi,
When sending large message I've hit this:
java.lang.IllegalArgumentException: Missing validated user from the Artemis message

Seems we don't setValidatedUserID when going through the slowPacketHandler in ServerSessionPacketHandler. I've raised a jira, let me know if you think it is a bug. I'll create some tests in meantime

**Comment by jbertram** [comment]
@cburlinchon, per my email to the dev list earlier this week, I plan on doing a release soon so if you want this in there please update the PR ASAP.

**Comment by cburlinchon** [comment]
To reproduce: run LargeMessageExample.java with populate-validated-user set to true(I've toggled this in artemis-configuration.xsd). It hangs on Receiving message for me

**Comment by clebertsuconic** [comment]
@cburlinchon nice one.. thanks a lot.. merging it

**Comment by clebertsuconic** [comment]
there is an issue on checkstyle.. also you are using a static block on the test...

I have fixed this with checking out a branch.. amending, and I'm merging the fixes as yours just for the sake of being easier than going back and forth comments... take a look though after I merged it.. thanks

**Pull request closed without merging**
