### PR TITLE
ARTEMIS-4617 upgrade JLine to 3.24.1

### PR DESCRIPTION
**Pull request by jbertram**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
when you run the the CLI after upgrading here, you get this:

```
clebertsuconic@MacBook-Pro bin % ./artemis
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jline.terminal.impl.exec.ExecTerminalProvider$ReflectionRedirectPipeCreator (file:/Users/clebertsuconic/work/apache/activemq-artemis/artemis-distribution/target/apache-artemis-2.33.0-SNAPSHOT-bin/apache-artemis-2.33.0-SNAPSHOT/lib/jline-3.24.1.jar) to constructor java.lang.ProcessBuilder$RedirectPipeImpl()
WARNING: Please consider reporting this to the maintainers of org.jline.terminal.impl.exec.ExecTerminalProvider$ReflectionRedirectPipeCreator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
     _        _               _

**Comment by clebertsuconic** [comment]
I would leave this one out TBH

**Comment by clebertsuconic** [comment]
@jbertram I opened https://github.com/jline/jline3/issues/937

**Comment by gnodet** [comment]
> when you run the the CLI after upgrading here, you get this:
> 
> ```
> clebertsuconic@MacBook-Pro bin % ./artemis
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.jline.terminal.impl.exec.ExecTerminalProvider$ReflectionRedirectPipeCreator (file:/Users/clebertsuconic/work/apache/activemq-artemis/artemis-distribution/target/apache-artemis-2.33.0-SNAPSHOT-bin/apache-artemis-2.33.0-SNAPSHOT/lib/jline-3.24.1.jar) to constructor java.lang.ProcessBuilder$RedirectPipeImpl()
> WARNING: Please consider reporting this to the maintainers of org.jline.terminal.impl.exec.ExecTerminalProvider$ReflectionRedirectPipeCreator
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
>      _        _               _
> ```

To get rid of this warning, it should be possible to define the system property `org.jline.terminal.exec.redirectPipeCreationMode` and give it the value `native`.  This should use a native method instead of reflection and should avoid this warning.

**Comment by jbertram** [comment]
@clebertsuconic, after all the other upgrades I rebased and when I build and test locally I don't see those warnings. This is what I see:
```
$ ./artemis 
     _        _               _
    / \  ____| |_  ___ __  __(_) _____
   / _ \|  _ \ __|/ _ \  \/  | |/  __/
  / ___ \ | \/ |_/  __/ |\/| | |\___ \
 /_/   \_\|   \__\____|_|  |_|_|/___ /
 Apache ActiveMQ Artemis 2.33.0-SNAPSHOT


For a list of commands, type help or press <TAB>:
Type exit or press <CTRL-D> to leave the session:
Apache ActiveMQ Artemis 2.33.0-SNAPSHOT >
```

**Comment by clebertsuconic** [comment]
@jbertram I'm handling the dependency between maven and jline to allow upgrading to latest.

**Comment by clebertsuconic** [comment]
@jbertram this is superseded by https://github.com/apache/activemq-artemis/pull/4800

**Pull request closed without merging**
