### PR TITLE
ARTEMIS-1179: Add Optional Client JMS Destination Cache

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Add topic and queue cache maps in Session.
Add configuration to use cache or not with defaulting to false, which keeps existing behaviour as the default.
Add documentation.

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
build is yellow, and says success , not sure why its marked failed.

**Comment by jbertram** [comment]
Clear the caches when the session is closed?

**Comment by michaelandrepearce** [comment]
When a session is closed it's thrown away right, and you make a new session. Would that not be redundant?

**Comment by michaelandrepearce** [comment]
As in we don't hold any remote resource (which typically close methods are for, so if no longer referenced GC would clear it out

**Comment by jbertram** [comment]
What you say makes sense, but I don't have faith in all users to always do things that make sense. I have no doubt that there are users out there who close sessions but still hold a reference to them somewhere.  It's good practice to clear things like caches when they are no longer functionally valid.

**Comment by michaelandrepearce** [comment]
@jbertram fair enough, just added clearing of them at the end of close().

**Comment by michaelandrepearce** [comment]
build output is success, and build is orange as in this build was successful.

**Comment by michaelandrepearce** [comment]
oh yeay sevntu not available again....

[ERROR] Unresolveable build extension: Plugin org.apache.felix:maven-bundle-plugin:3.3.0 or one of its dependencies could not be resolved: Could not find artifact org.apache.felix:maven-bundle-plugin:jar:3.3.0 in sevntu-maven (http://sevntu-checkstyle.github.io/sevntu.checkstyle/maven2) @ 

On a serious note, it seem this tool in the repo, isn't reliable, this isn't the first time I've seen this issue or others have. How much real value is it adding?

**Comment by michaelandrepearce** [comment]
just pushed a commit comment change to make it rebuild to see if sevntu wants to sort itself.

**Comment by clebertsuconic** [comment]
Last time I checked there was a test failure on the unit tests.. something easy to be fixed.

**Comment by clebertsuconic** [comment]
Yep... org.apache.activemq.artemis.tests.unit.ra.ConnectionFactoryPropertiesTest.testCompareConnectionFactoryAndResourceAdapterProperties

**Comment by michaelandrepearce** [comment]
see it now you point it out, annoying as build shows end output as success when watching console

https://builds.apache.org/job/ActiveMQ-Artemis-PR-Build/3081/console
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14:13 min
[INFO] Finished at: 2017-05-24T19:11:19+00:00
[INFO] Final Memory: 433M/6315M
[INFO] ------------------------------------------------------------------------

**Comment by clebertsuconic** [comment]
The build was successful.. with test failures...  :)

otherwise the complete testsuite would never be successful. We try to fix all of them.. but we have always had a few failures on the whole build.

**Comment by clebertsuconic** [comment]
the criteria for a pass on the PR checks is build success with no test failures on the minimal tests we ellected for here (fast-tests)

**Comment by michaelandrepearce** [comment]
For RA the property has use, as it doesn't have the same behaviour as the connection factory so updated the test to reflect that.

**Comment by michaelandrepearce** [comment]
actually hold that thought, whilst i don't expect there to be the same issue (aka Spring etc doing stuff), i can add it, so will add the support incase some framework does the same with RA.

**Comment by michaelandrepearce** [comment]
@clebertsuconic all added and all looking good now with build :) thanks for the tip.

**Comment by clebertsuconic** [comment]
@michaelandrepearce about seventu:

A few years ago I wrote this:

https://github.com/hornetq/hornetq-checkstyle-checks

later one I tried submitting this to maven checkstyle, but then I was told that sevntu was the labs to go... so I tried submitting it there. it was so much of work to do that I gave up but someone there took on my idea and developed the same thing there....


That's basically to enforce name on parameters, otherwise jenkins will show all the tests without any context:

```java
   @Parameterized.Parameters(name = "group={0}, command={1}, need-instance={2}")
   public static Collection getParameters() {
```



Now if the repo keeps going out.. perhaps we should ditch it... best would be to ask them to have it on maven repo.

**Comment by michaelandrepearce** [comment]
Indeed it's quite easy to get an account to publish on to central just a simple jira ticket, so they should be willing to publish there. 

If they're don't then I would suggest removal. And worst case if really is useful is being the specific checktyle checks back in (as you had with hornet)

**Comment by clebertsuconic** [comment]
https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/321

**Comment by clebertsuconic** [comment]
https://groups.google.com/forum/#!topic/sevntu-checkstyle/YibCclEYexs

**Comment by michaelandrepearce** [comment]
cool, thanks for pushing it.

fyi, i think we found your presentation on youtube :)  https://www.youtube.com/watch?v=qF1Op1ZNBAk

**Comment by clebertsuconic** [comment]
@michaelandrepearce ouch.. I was trying to hide from it :)

**Pull request closed without merging**
