### PR TITLE
ARTEMIS-936 - make amqp transformers configurable and default to native

### PR DESCRIPTION
**Pull request by andytaylor**
https://issues.apache.org/jira/browse/ARTEMIS-936

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@andytaylor these failures on the PR check seem real.

**Comment by andytaylor** [comment]
fixed

**Comment by gemmellr** [comment]
The new documentation seems a little confusing given all the mentions of JMS, which is often only indirectly related to what the transformers are doing, with cross-protocol conversion really being what is affected. Folks not using JMS clients are also going to be affected by transformer changes, and folks using AMQP JMS clients wont be affected in the way the documentation might seem to suggest (e.g they wont suddenly receive a BytesMessage just because the broker used one internally in its native transformer to carry the AMQP bytes of a TextMessage they had sent to the broker).

The example of configuring a 'jms' transformer actually gives configuration for a 'native' one.

**Comment by andytaylor** [comment]
I took this documentation from ActiveMQ and its only really related to the JMS client, we could probably add more details about other cross protocol transformations, MQTT for instance.  you are correct folks just using AMQP won't be effected but if they use AMQP to JMS they will.

I'll fix the example

**Comment by andytaylor** [comment]
example fixed

**Comment by andytaylor** [comment]
actually leave this PR for now

**Comment by jbertram** [comment]
Any news on this PR?

**Comment by clebertsuconic** [comment]
@jbertram this will probably be closed without merging... it won't be needed with what I'm doing...


AMQP Messages are always raw on my branch.. they only get converted when crossing protocols.

**Comment by clebertsuconic** [comment]
@andytaylor native converters are gone on my branch. We will not require conversions any more... can you close this one? it's moot now.

**Pull request closed without merging**
