### PR TITLE
ARTEMIS-3716 move e2e tests to e2e-tests module

### PR DESCRIPTION
**Pull request by tlbueno**
Move all tests which are related to end-to-end testing from smoke-tests module to a new e2e-tests module.

These e2e tests are those which are dependent of ContainerService class. ContainerService class uses artemis inside a container by using the testcontainers library and for that reason these tests are usually a quite slow and tecnically they are not a smoke test. 

The new e2e-tests module is part of tests module but it is not enabled by default and to get executed it requires the e2e-tests profile specification on maven command.

### CODE REVIEW

**Comment by jbertram** [comment]
IMO this needs a Jira. At the very least it needs a rebase to pick up 67c9df195d4897059de219d677d9a256f5d3a267 which should allow the build checks to finish normally.

Also, please update the commit message to follow the recommendations from the [hacking guide](https://github.com/apache/activemq-artemis/blob/main/docs/hacking-guide/en/maintainers.md#commit-messages).

Thanks!

**Comment by tlbueno** [comment]
> IMO this needs a Jira. At the very least it needs a rebase to pick up [67c9df1](https://github.com/apache/activemq-artemis/commit/67c9df195d4897059de219d677d9a256f5d3a267) which should allow the build checks to finish normally.
> 
> Also, please update the commit message to follow the recommendations from the [hacking guide](https://github.com/apache/activemq-artemis/blob/main/docs/hacking-guide/en/maintainers.md#commit-messages).
> 
> Thanks!

@jbertram, 

Thank you for the suggestions! I opened a jira, updated the PR title and the commit message title to match the recommendation.

**Comment by clebertsuconic** [comment]
@tlbueno the e2e-tests should only run if you enable the profile -De2e-tests.. the fast tests are failing on the PR check


I want to make sure there are no compilation or check-stye issues introduced.. but we should not run the e2e-tests on the GitHub actions.

**Comment by tlbueno** [comment]
> @tlbueno the e2e-tests should only run if you enable the profile -De2e-tests.. the fast tests are failing on the PR check
> 
> I want to make sure there are no compilation or check-stye issues introduced.. but we should not run the e2e-tests on the GitHub actions.

@clebertsuconic now I think it is correct. The e2e-tests are getting built (compiled/verified) but not executed unless the -Pe2e-tests is provided.

**Pull request closed without merging**
