### PR TITLE
ARTEMIS-374 support schedule messages on LVQ

### PR DESCRIPTION
**Pull request by jbertram**

### CODE REVIEW

**Comment by jbertram** [comment]
I need some way to differentiate messages that are put on the head of the queue by the scheduler and those that aren't because they need to be treated differently (notice the new 'if' block in addHead()).  A message property seemed the simplest way to do that, but I'm open to other possibilities.  Do you have any suggestions here?

**Comment by clebertsuconic** [comment]
Look at Reference.getDeliveryTime(). it will be set to 0 during the Scheduling handler. It seems that's what you need, no need for any other property.

if (getDeliveryTime()==0).. go directly to the head.. same as if it had your property (I think)


I don't see a need for a new property

**Comment by jbertram** [comment]
I'm not following.  From what I can tell in addHead() (where I need to do the check) Rreference.getScheduledDeliveryTime() will always return 0 so there's no way to differentiate scheduled messages from non-scheduled messages by using this property.  Can you clarify your suggestion?

**Comment by clebertsuconic** [comment]
@jbertram it's set during routing on PostOfficeImpl.
it should be set by the time you get there.

**Pull request merged**
