### PR TITLE
[ARTEMIS-1629] Set connection.clientID before executing ...

### PR DESCRIPTION
**Pull request by jostbg**
connection#validateUser

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
Can there be a test case to a) show why this needs to be changed, b) avoid any future regression.

**Comment by jostbg** [comment]
@michaelandrepearce @jbertram  I added a test case to the JIRA that outlines the issue but I have no idea how to get it into the same form that is used in the stomp test cases in the integration-tests project. There seems to obvious way how to use a different SecurityManager when extending StompTestBase class.

**Comment by jbertram** [comment]
@jostbg, you can extend StompTestBase and override the createServer() method.  Look at the implementation of createServer() in StompTestBase to get an idea how to create/configure the server.  The method `org.apache.activemq.artemis.core.server.ActiveMQServers#newActiveMQServer(org.apache.activemq.artemis.core.config.Configuration, javax.management.MBeanServer, org.apache.activemq.artemis.spi.core.security.ActiveMQSecurityManager, boolean)` will likely come in handy for you when creating your server.

**Comment by jostbg** [comment]
@michaelandrepearce @jbertram Is that kind of test what you are having in mind?

**Comment by jbertram** [comment]
@jostbg, that's what I was looking for.  Although I would expect the commits to be squashed together.

**Comment by jostbg** [comment]
@jbertram Ok, done.

**Comment by michaelandrepearce** [comment]
@jostbg thanks for the test :) +1.

**Pull request closed without merging**
