### PR TITLE
Added Initial MQTT Protocol Support

### PR DESCRIPTION
**Pull request by mtaylor**
Creates a new MQTT protocol module.  

There is currently no support (at least tested support) for using MQTT to/from other protocols.

There are a number of outstanding items of work outlined in TODO/FIXME in the PR.  These will be transferred to JIRA when/if the code is accepted.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
Great Work!

Since this is a big task, I would like to have as many people reviewing this... Input is appreciated from anyone!

**Comment by clebertsuconic** [comment]
The only two big pieces I'm missing here are:

- examples (Make an example that could be used as a micro benchmark)

- Docs...


The examples can probably wait as you would need to do it under the new framework, on which case you would need to sync with @jbertram....


The docs... can you write something simple? We are about to release and I wouldn't want to go without docs for this. Mention this is early stage and we are welcoming feedback on the docs.

**Comment by mtaylor** [comment]
@clebertsuconic Am I able to follow up with some separate documentation rather than iterating over this PR?

**Comment by andytaylor** [comment]
Ive reviewed the code with Martyn and I'm happy for this to be merged.

**Comment by mtaylor** [comment]
@clebertsuconic I've added some comments to the tests and uncommented tests with @ignore where possible.

**Comment by clebertsuconic** [comment]
@mtaylor  sure.. we can do this on a separate PR. 
But given the progress we could release any time between 2 and 4 weeks.

**Comment by mtaylor** [comment]
@clebertsuconic I'll aim to get documentation and an example done before then.  Thanks.

**Comment by mtaylor** [comment]
@clebertsuconic Sure, I'll ensure to contribute an example and documentation before then.

**Pull request merged**
