### PR TITLE
introduce ClientIDCallback to allow JAAS login module to retrieve Client ID

### PR DESCRIPTION
**Pull request by amarkevich**
Currently there is no way to get client ID in custom login module. Its required for some MQTT cases when username is not used.

### CODE REVIEW

**Comment by jbertram** [comment]
Couple of things:

- You need a Jira for this change.
- You need to squash all your commits.
- Your commit message should conform to the pattern outlined in the [Hacking Guide](https://github.com/apache/activemq-artemis/blob/main/docs/hacking-guide/en/code.md#commitMessageDetails).

**Comment by brusdev** [comment]
What is the JAAS login module that requires the ClientIDCallback?

**Comment by amarkevich** [comment]
> What is the JAAS login module that requires the ClientIDCallback?

In my particular case custom JAAS login module contains implementation specific logic but Client ID is required to handle the case

**Review by gtully — COMMENTED** [review]
looks good. nice tidy up in there. thanks for the contribution. I would include a test, there is no existing unit test but it would benefit from a JaasCallbackHandlerTest to protect this addition since there is on login module that exercises it.

**Comment by amarkevich** [comment]
@gtully added JaasCallbackHandlerTest

**Pull request merged**
