### PR TITLE
ARTEMIS-229 validate user and role with address

### PR DESCRIPTION
**Pull request by jscheid**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
Looks good... I am not sure I like the name ActiveMQSecurityManager2 though...

But I am failing to find a better one. I thought about 
- ActiveMQSecurityManagerExt
- ActiveMQSecurityManagerAddress
- ActiveMQSecurityManagerV2   (this one probably makes it a better sense... the V makes it clear it's a versioning thing, and we would deprecate the previous one)

**Comment by jscheid** [comment]
It was inspired by http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/Collections2.html

But I don't care what it's called, let me know what name you'd prefer and I'm happy to change it.

**Comment by jmesnil** [comment]
fwiw, Eclipse has the best document about evolving Java API and they use the `2` version: https://wiki.eclipse.org/Evolving_Java-based_APIs_3#.222.22_Convention

**Comment by clebertsuconic** [comment]
ok, looks like that's the standard way then.. I was being Old Fashioned :)

will merge this soon

**Pull request merged**
