### PR TITLE
ARTEMIS-3523: Expose replay through AddressControl

### PR DESCRIPTION
**Pull request by nbrendah**
I have tried to refactor the ActiveMQServer method replay(address, .....)  on the ActiveMQServerControl such it should just call server.replay(this.address, .....)

**Issue link**  https://issues.apache.org/jira/browse/ARTEMIS-3524

cc @clebertsuconic

### CODE REVIEW

**Comment by nbrendah** [comment]
Thank you @clebertsuconic for taking time to look at this.
I have added updated the PR to match the suggestions and comments above.  If you get some free time, i request for a review.

Thanks for the good work

**Comment by nbrendah** [comment]
@clebertsuconic 
I honestly cant thank you enough, but i appreciate the time you have invested in this.  
I have added more changes.  
I hope its fine now.  
Have a good night.

**Comment by clebertsuconic** [comment]
@nbrendah congratulations.. you got your first PR merged into Artemis :)


I had one small tweak that I almost squashed into your changes... I decided to keep it separated so you could see the small changes I had to apply...

your task is now complete for the outreachy.org program... please, submit your completion and if you have any questions contact me

but feel free to keep contributing to us if you like :)

**Comment by nbrendah** [comment]
Thank you @clebertsuconic for all the assistance and help on this.  
I have seen the tweaks you did https://github.com/apache/activemq-artemis/commit/fdc0cc591c9ab9dea22a9b65cef6c53ea0263222

I would wish to continue contributing Artemis. Actually, i had even created https://github.com/apache/activemq-artemis/pull/3805 to learn more.  Maybe, if you get some free time, I request you to have a look.  

I think time i am not going to be too much of a slow learner :laughing: 

Thank you so much

**Pull request closed without merging**
