### PR TITLE
Fix possible leaks in LDAP tests

### PR DESCRIPTION
**Pull request by jbertram**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@jbertram 

I will merge it, but if I added this following line in one of these tests:

```java
   @Rule
   public ThreadLeakCheckRule leakCheckRule = new ThreadLeakCheckRule();

```


The test will have leaked threads from some executor:


```
LEAKING THREADS
=============================================================================
Thread Thread[NioProcessor-1,5,main] is still alive with the following stackTrace:
sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
org.apache.mina.transport.socket.nio.NioProcessor.select(NioProcessor.java:69)
org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:961)
org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)
=============================================================================
Thread Thread[pool-4-thread-1,5,main] is still alive with the following stackTrace:
sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
org.apache.mina.filter.executor.UnorderedThreadPoolExecutor$Worker.fetchTask(UnorderedThreadPoolExecutor.java:461)
org.apache.mina.filter.executor.UnorderedThreadPoolExecutor$Worker.run(UnorderedThreadPoolExecutor.java:413)
java.lang.Thread.run(Thread.java:745)
=============================================================================
Thread Thread[Thread-1,5,main] is still alive with the following stackTrace:
java.net.SocketInputStream.socketRead0(Native Method)
java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
java.net.SocketInputStream.read(SocketInputStream.java:170)
java.net.SocketInputStream.read(SocketInputStream.java:141)
java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
java.io.BufferedInputStream.read(BufferedInputStream.java:345)
com.sun.jndi.ldap.Connection.run(Connection.java:860)
java.lang.Thread.run(Thread.java:745)

```

**Comment by clebertsuconic** [comment]
actually since this is only affecting tests (not any production code) it's better until the release is out (tomorrow) to merge it.

I know Martyn will be respining the release. So better to wait, as we have the tests run.. and everything.

**Comment by jbertram** [comment]
The issue with the threads is that org.apache.directory.server.core.integ.FrameworkRunner which is being used for @RunWith is managing the LDAP server and I believe by the time the thread check executes the LDAP server hasn't been shutdown completely.  If we want to keep the thread checker then I think we'll have to find another way to manage the LDAP server.

**Comment by mtaylor** [comment]
@jbertram @clebertsuconic I've had issues with the thread checker when using JDBC.  Often the driver will create some background thread that manages dead connections, clean up etc... and is closed down on VM shutdown.  For these cases I add the thread name to the allowed threads.  I would do the same here.

**Comment by clebertsuconic** [comment]
@jbertram there are methods on the thread-leack-checker to add known thread names as well.

**Pull request closed without merging**
