### PR TITLE
ARTEMIS-1532 Enable tests which are unintentionally skipped by Surefire 

### PR DESCRIPTION
**Pull request by jdanekrh**
This is not ready to be merged, because `HAAutomaticBackupSharedStoreTest` and `testSystemPropertyOverride` are failing after these changes.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
Are you sure it was unintentional ?

I’m not on a computer now. But I remember a few tests that were commented out instead of removed to be checked later and we never got back to them.

**Comment by jdanekrh** [comment]
Well, I might've guessed the intent wrong in one or two cases, I guess.

If I thought it is unintentional, I've either renamed the class (so that Surefire would pick it) or added the @Test annotation.

If I thought it is intentional, I've added @Ignored annotation instead of whichever other method was used to disable that test.

**Comment by michaelandrepearce** [comment]
@mtaylor @clebertsuconic could we fix this up, seems this got merged with PR build broken, and since PR is constantly failing with this test testSystemPropertyOverride

**Comment by michaelandrepearce** [comment]
Have sent in https://github.com/apache/activemq-artemis/pull/1737 to fix this

**Pull request closed without merging**
