### PR TITLE
ARTEMIS-3168 - add PrincipalConversionLoginModule feature

### PR DESCRIPTION
**Pull request by gtully**

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
Looks like a nice feature but not 100% how to use. It be great if an example was added.

**Comment by gtully** [comment]
what configuration doc section are you thinking about? 
It is covered in the JAAS login module section in security.md and the test demonstrates configuration.

Fair point on the example. 
I came across this need when playing with org.keycloak.adapters.jaas.DirectAccessGrantsLoginModule
Let me try and wrangle that into an example and update this PR.

**Comment by gtully** [comment]
updated with an example that pulls it together using keycloak. I hope the readme.md is informative and reads well, feedback appreciated. Thanks in advance!

**Comment by gtully** [comment]
fixed up some check style and json excluded from rat check.

**Comment by gtully** [comment]
updated to only download keycloak on run

**Comment by gtully** [comment]
any other feedback, I would appreciate a read of the example readme.md - i tweaked a few typos just now.

**Pull request merged**
