### PR TITLE
[ARTEMIS-591] Wrong XAException return code when broker timeout is hit

### PR DESCRIPTION
**Pull request by bayern39**
https://issues.apache.org/jira/browse/ARTEMIS-591

### CODE REVIEW

**Comment by jbertram** [comment]
Can you add a test to your commit which verifies the proper exception code is returned in the case of a timeout?

**Comment by bayern39** [comment]
@jbertram  OK,i will do it

**Comment by clebertsuconic** [comment]
This fix is not valid anyways. There's no way to determine if the server has hit the timeout on the TX yet. It would all depend on the scanning at the server's.

**Comment by bayern39** [comment]
@clebertsuconic  yeah,as your say,at present ,RM scans  for old transactions and rollback any it finds,it is for global transactions.so i must add the judgement for local transation of itself timeout in RM,other than defaultimeout ,is it?

**Comment by bayern39** [comment]
@clebertsuconic  hi,at present,it scans for old transactions and rollback any it finds in RM,in the method    
"tx.hasTimedOut(now, defaultTimeoutSeconds)",i think it is not only scanning for defaultTimeout transactions,but  also has hi the timeout on the TX,because we can see the implementation of "hasTimedOut" ,if we had set the timeout of the TX,it would be hit in the ResourceManager.

`public boolean hasTimedOut(final long currentTime, final int defaultTimeout) {
      synchronized (timeoutLock) {
         boolean timedout;
         if (timeoutSeconds == -1) {
            timedout = getState() != Transaction.State.PREPARED && currentTime > createTime + defaultTimeout * 1000;
         }
         else {
            timedout = getState() != Transaction.State.PREPARED && currentTime > createTime + timeoutSeconds * 1000;
         }

         if (timedout) {
            markAsRollbackOnly(new ActiveMQException("TX Timeout"));
         }

         return timedout;
      }
   }
`

**Comment by bayern39** [comment]
@clebertsuconic  Hi clebert, i have considered your comment,what do you mean is that the RM can only   find the old transactions whose lifetime are older than the default transaction timeout by means of scanning the started transactions every transaction-timeout-scan-period time,so it can not find the time out transactions whose privacy attribute of  timeout  is not default transaction timeout in server and smaller than  default transaction timeout. So when the smaller time out transaction is over, the server can not find it  immediately ,it must await the RM scans it.Right? 

I have communicated with the origin issue reporter,the reason why he posed the issue is not as a trouble of specific Artemis behavior,the issue is about asking for Artemis being better compliant with XA specification in error code.So i am considering whether it is needed to change the  Artemis behavior , because the present solution seems have not influence.We can still configure the  transaction-timeout-scan-period  with small value to cope with self-defined timeout attribute.This is my point, maybe have some mistakes,What do you think about it?

**Comment by bayern39** [comment]
@clebertsuconic  Hi Clebert,as we know ,we use  the server scanning find the time out  tx,this is the solution to determine the server hit time out,So I can not understand your means as well,can you tell me more details?Thanks!

**Comment by clebertsuconic** [comment]
There's no way to determine here if the Rolledback was caused by a timed out.. or something else (like an error or something).

I had been involved on tests where I was dealing with errors during load. And I don't see how to distinguish between an error and a time out.


I'm also not sure what's the risk of

**Comment by clebertsuconic** [comment]
@bayern39  ^^

**Comment by clebertsuconic** [comment]
@bayern39  I merged this with an extra commit, with some changes I have made.. if you could review please.

**Comment by bayern39** [comment]
@clebertsuconic  OK,I will do it.

**Comment by clebertsuconic** [comment]
@bayern39 look at https://github.com/apache/activemq-artemis/pull/722 please, where I'm addressing the typos

**Pull request closed without merging**
