### PR TITLE
ARTEMIS-856 small fix to avoid re-distributor being assigned a group

### PR DESCRIPTION
**Pull request by michaelandrepearce**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
I think this needs a JIRA.. perhaps even a test?

**Comment by michaelandrepearce** [comment]
@clebertsuconic its just something spotted missing when we did work for jira 856 still not released, so as its related and not released still, have used that jira to keep it all associated.

**Comment by michaelandrepearce** [comment]
@clebertsuconic its just something spotted missing when we did work for jira 856 still not released, so as its related and not released still, have used that jira to keep it all associated.

**Comment by michaelandrepearce** [comment]
@clebertsuconic its just something spotted missing when we did work for jira 856 still not released, so as its related and not released still, have used that jira to keep it all associated.

**Pull request closed without merging**
