### PR TITLE
NO-JIRA stop PagingManager after RemotingService to let it finish send notifications

### PR DESCRIPTION
**Pull request by franz1981**
The `NotificationTest::testBINDING_ADDED` test was printing this stack trace (athough passing, most of the times):
```java
[main] 04:36:31,886 WARN  [org.apache.activemq.artemis.core.server] AMQ222230: Failed to send notification: java.lang.IllegalStateException: PagingStore(activemq.notifications) not initialized
	at org.apache.activemq.artemis.core.paging.impl.PagingStoreImpl.page(PagingStoreImpl.java:794) [:]
	at org.apache.activemq.artemis.core.persistence.impl.nullpm.NullStorageManager.addToPage(NullStorageManager.java:575) [:]
	at org.apache.activemq.artemis.core.postoffice.impl.PostOfficeImpl.processRoute(PostOfficeImpl.java:1433) [:]
	at org.apache.activemq.artemis.core.postoffice.impl.PostOfficeImpl.route(PostOfficeImpl.java:1132) [:]
	at org.apache.activemq.artemis.core.postoffice.impl.PostOfficeImpl.route(PostOfficeImpl.java:1025) [:]
	at org.apache.activemq.artemis.core.postoffice.impl.PostOfficeImpl.route(PostOfficeImpl.java:1001) [:]
	at org.apache.activemq.artemis.core.postoffice.impl.PostOfficeImpl.route(PostOfficeImpl.java:996) [:]
	at org.apache.activemq.artemis.core.server.management.impl.ManagementServiceImpl.sendNotification(ManagementServiceImpl.java:698) [:]
	at org.apache.activemq.artemis.core.remoting.impl.invm.InVMAcceptor.stop(InVMAcceptor.java:176) [:]
	at org.apache.activemq.artemis.core.server.ActiveMQComponent.asyncStop(ActiveMQComponent.java:26) [:]
	at org.apache.activemq.artemis.core.remoting.server.impl.RemotingServiceImpl.stop(RemotingServiceImpl.java:416) [:]
	at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.stop(ActiveMQServerImpl.java:1153) [:]
	at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.stop(ActiveMQServerImpl.java:1033) [:]
	at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.stop(ActiveMQServerImpl.java:878) [:]
	at org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl.stop(ActiveMQServerImpl.java:872) [:]
	at org.apache.activemq.artemis.tests.util.ActiveMQTestBase.stopComponentOutputExceptions(ActiveMQTestBase.java:2267) [artemis-server-2.12.0-SNAPSHOT-tests.jar:2.12.0-SNAPSHOT]
	at org.apache.activemq.artemis.tests.util.ActiveMQTestBase.tearDown(ActiveMQTestBase.java:319) [artemis-server-2.12.0-SNAPSHOT-tests.jar:2.12.0-SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) [:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) [rt.jar:1.8.0_66]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47) [junit-4.11.jar:]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.11.jar:]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44) [junit-4.11.jar:]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33) [junit-4.11.jar:]
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55) [junit-4.11.jar:]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48) [junit-4.11.jar:]
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55) [junit-4.11.jar:]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48) [junit-4.11.jar:]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48) [junit-4.11.jar:]
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55) [junit-4.11.jar:]
	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [junit-4.11.jar:]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271) [junit-4.11.jar:]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70) [junit-4.11.jar:]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50) [junit-4.11.jar:]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) [junit-4.11.jar:]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) [junit-4.11.jar:]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) [junit-4.11.jar:]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) [junit-4.11.jar:]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) [junit-4.11.jar:]
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55) [junit-4.11.jar:]
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55) [junit-4.11.jar:]
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55) [junit-4.11.jar:]
	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [junit-4.11.jar:]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309) [junit-4.11.jar:]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283) [surefire-junit4-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173) [surefire-junit4-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153) [surefire-junit4-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128) [surefire-junit4-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203) [surefire-booter-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155) [surefire-booter-2.18.1.jar:2.18.1]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103) [surefire-booter-2.18.1.jar:2.18.1]
```
It shows that InVM acceptors while stopping, tries to send a Notification, but, given that the PagingManager was already stopped, they were getting the notification send to fail.

### CODE REVIEW

**Comment by franz1981** [comment]
@clebertsuconic Maybe this could have other impacts and deserve its own JIRA although I haven't yet found a proper test that shows a proper bug due to it.

**Comment by clebertsuconic** [comment]
Semantically there was no issues other than the messages printed.. that's why no tests probably caught it.

it's a good fix, but if you wanted to validate a test, you would have to use the Logger interceptor?


I think the fix is good as it is here.

**Comment by clebertsuconic** [comment]
i'm writing tests.. if everything ok, I will merge it.

**Comment by clebertsuconic** [comment]
a lot of tests on replication are freezing.

**Comment by franz1981** [comment]
That's good: it means that we are:
1) assuming some order on components shutdown that I'm not honoring with my change
2) replication behaviour are wrongly relying on such ordering (maybe not flushing tasks?)
In both cases I think that is dangerous to commit this fix, but I would like to investigate what's going on anyway, maybe it can be improved by making explicit what we now assume implicitly...

**Comment by clebertsuconic** [comment]
something on activation probably. I don't know.

**Comment by clebertsuconic** [comment]
alternate fix at #3062

**Comment by michaelandrepearce** [comment]
jira for this pls.

**Comment by franz1981** [comment]
I can close this given that Cleb has found a better fix for this test suite failures

**Comment by michaelandrepearce** [comment]
@franz1981 in future even if a small bug fix, could i ask we are better at raising jira,s these are important bug fixes, that without jira wouldnt be visible in release notes.

**Comment by franz1981** [comment]
Agree :)

**Pull request closed without merging**
