### PR TITLE
ARTEMIS-1938 Update to Qpid JMS 0.33.0

### PR DESCRIPTION
**Pull request by tabish121**
Update to latest release of Qpid JMS

### CODE REVIEW

**Comment by clebertsuconic** [comment]
I don’t think we should pick components updates on 2.6.x.  Let me know if you have a reason to update it.

**Comment by tabish121** [comment]
I targeted the JIRA at 2.7.0 for that reason.

**Comment by clebertsuconic** [comment]
I was just double checking if it made sense or not.  Wasn’t implying you did. 


Thanks

**Comment by tabish121** [comment]
The only reason you might want to take it is that it contains several fixes for failover handling and artemis provides a Karaf feature for an AMQP client so your users could benefit from that, otherwise it has no impact on the broker as it is only used in testing otherwise.

**Comment by clebertsuconic** [comment]
Ohhhh. I didn’t look on the diff.  You usually update proton together and I thought you included it here.

**Comment by tabish121** [comment]
There are no updates to proton-j at this time, only client fixes

**Comment by clebertsuconic** [comment]
I need a vacation :). I’m starting to see things.

**Pull request merged**
