### PR TITLE
ARTEMIS-2197 Page deleted before transaction finishes

### PR DESCRIPTION
**Pull request by gaohoward**
When a receiving transaction is committed in a paging situation,
if a page happens to be completed and it will be deleted in a
transaction operation (PageCursorTx). The other tx operation
RefsOperation needs to access the page (in PageCache) to finish
its job. There is a chance that the PageCursorTx removes the
page before RefsOperation and it will cause the RefsOperation
failed to find a message in a page.

(cherry picked from b36dc37c152cabe3a0d9af178db043f842bfcdc0)
(cherry picked from 2bd8fa7c5dcfb2c29a5c5f61ff433bf161b1b86e) (Fix regression)

### CODE REVIEW

**Comment by gaohoward** [comment]
@clebertsuconic I've update the PR including the regression fix.

**Comment by gaohoward** [comment]
ok, I'll make it separate commits. thx

**Comment by gaohoward** [comment]
@clebertsuconic It's done.

**Comment by clebertsuconic** [comment]
@gaohoward can you close this. It's merged after a rebase (I fixed a test failure you had here).

Merge doesn't work well on 2.6.x.

**Pull request closed without merging**
