### PR TITLE
ARTEMIS-1731 Support offline validation

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Copy in https://www.w3.org/2005/08/xml.xsd so validation of broker.xml works offline.

### CODE REVIEW

**Comment by obfischer** [comment]
I wouldn't change the `schemaLocation` directly as it is actual a bad practice. Dependending on the XML processor catalog files should be used. In most cases the API of the XML processor allows you to handle such things in a cleaner way.

**Comment by michaelandrepearce** [comment]
Please feel free to submit and alternative approach

**Comment by clebertsuconic** [comment]
@michaelandrepearce I thought the right way to do this was through using the actual HTTP location. and have tools to cache it somehow.

In what scenario this is failing? on deploy on master, when running behing a firewal? or when using an external tool for this?

**Comment by jbertram** [comment]
From the [JIRA](https://issues.apache.org/jira/browse/ARTEMIS-1731), "...starting Artemis fails when the server running broker has no Internet access."

**Comment by clebertsuconic** [comment]
@jbertram  I see.. nice it was caught before the release...


I'm merging it...

@obfischer  if you have a better way and still solve this issue.. I'm open for it.

**Pull request closed without merging**
