### PR TITLE
ARTEMIS-1397 remove package private access to netty

### PR DESCRIPTION
**Pull request by ryeats**
Fixes #ARTEMIS-1397 
With this fix Artemis can now be clustered when running inside of karaf. Its not elegant solution but I don't see any other way around it.

### CODE REVIEW

**Comment by jbertram** [comment]
Can you explain a bit why this solution isn't elegant what would constitute an elegant solution in your opinion.  I'm not terribly familiar with Karaf/OSGi so maybe that's why I'm not following.

**Comment by ryeats** [comment]
Essentially this is copying netty inside the artemis-server-osgi jar because UnpooledUnsafeDirectByteBufWrapper needs package private access to some classes in netty. The downside is the manifests in those jars are ignored and we have to make sure the one in artemis-service-osgi satisfies all of netty's imports now. i.e. if we update Netty versions and they added a new dependency we will have to add an exclusion to our Import-Package or install an additional bundle. Frankly we should probably not be doing something that requires package private access to Netty but I realize its doing some cool stuff.  As for a more elegant solution I am not sure if this is feasible but possibly contributing a low level api to Netty so we don't need package private access.

**Comment by ryeats** [comment]
DO NOT MERGE
after more testing I discovered this fix causes a classloader issue in some cases need to figure out how to resolve it.

**Comment by ryeats** [comment]
Okay went another route which I think this is better, I refactored the copying the necessary code from Netty to perform the logic that was package private.

**Comment by michaelandrepearce** [comment]
If access is needed why not contribute to netty to get the access changed, rather than hacking it, in artemis

**Comment by clebertsuconic** [comment]
@michaelandrepearce It's not copying... @franz1981  had written a class extending a Netty Buffer, instead of using protected methods he named the package io.netty... I missed that TBH...


This change is more than welcomed.. merging it.

**Comment by clebertsuconic** [comment]
@ryeats thanks a lot!

**Pull request closed without merging**
