### PR TITLE
ARTEMIS-3804: make version number available to docs build

### PR DESCRIPTION
**Pull request by gemmellr**
Make the version number available to reference in the user manual, add it to the intro page

### CODE REVIEW

**Comment by clebertsuconic** [comment]
isn't that changing how we do release? we need now to build the release out of the scratch doc...

I usually just go to the user/en and type gitbook pdf, gitbook epub, gitbook build


and copy the files over.


now we will need to change the procedure a little bit, right?



perhaps this scratch build should be removed out of the release profile and always be ran?

**Comment by gemmellr** [comment]
I'm fine with it being profiled, it seems unecessary to build it every time...in fact I would like to move the javadoc bit into the profile since its a massive waste of time on each build.

**Comment by clebertsuconic** [comment]
I'm file with using a profile also.. Im just checking what we need to change on the Release... we will need to update the RELEASE.md as well. can you do that?

**Comment by gemmellr** [comment]
@clebertsuconic pushed an update for RELEASE.md ...like that?

**Comment by clebertsuconic** [comment]
thanks

**Pull request merged**
