### PR TITLE
ARTEMIS-737 - added JUnit rules for Artemis servers and clients

### PR DESCRIPTION
**Pull request by hqstevenson**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
This looks a great idea...


however.. there's no docs on how to use this. it would warrant a chapter on the user-docs..

and maybe examples on how to run tests with it?

**Comment by jbertram** [comment]
I think it would also be good to have a clear explanation of why this approach is superior to the approach already adopted in the test-suite.

Additional questions:

1. What expectation is there to adopt this style of testing?  Should all new tests use this style?
2. Do you plan on converting all existing test-cases to this style?  If not, I'd be concerned with having 2 methods of doing the same thing introducing confusion.

**Comment by clebertsuconic** [comment]
I guess this is intended for users to use on their tests?

What was the intention, to refactor Artemis' testsuite, or to provide rules for users running their own tests?

**Comment by johnament** [comment]
@clebertsuconic agreed.  This does look like an awesome idea though for end users trying to test with messaging systems.

**Comment by clebertsuconic** [comment]
@hqstevenson  are you getting notifications for these questions? either here or dev-list

**Comment by hqstevenson** [comment]
I fixed the check style issues, and I also added constructors to the EmbeddedXXXResource rules to allow configuring the servers with configuration files.

**Comment by clebertsuconic** [comment]
@hqstevenson the idea here is to provide final users the capability of running junit tests with a messaging server, right?


It would be nice to have at least an example on how to do this.. can you add at least one test as an example?

**Comment by hqstevenson** [comment]
I'd be happy to add an example, but I'm not sure exactly what you're looking for.  All of the unit tests show the basics of how you embed a sever into your test, and how you use the server afterwards.

Is there a specific type of test you'd like to see?

BTW - once this is released, I'm going to contribute a "example-camel-artemis" to the Camel project - that will show how to use the embedded resources with Camel.

**Comment by hqstevenson** [comment]
I just realized I didn't finish the javadoc for the XXXResource classes.  I intended to have basic usage information in the javadoc for each class.  I'll get that added and update the PR

**Comment by clebertsuconic** [comment]
@hqstevenson  I was looking more for a single example on how to use your annotations. Something we could add a chapter within the documentation.

**Comment by clebertsuconic** [comment]
@hqstevenson  I didn't mean an actual example.. just how someone would use this into their application. 

It looks great.. will merge this soon.

**Comment by clebertsuconic** [comment]
@hqstevenson I merged it with an extra commit, and removed the example.. and added a doc chapter...Please take a look... Feel free to change anything with another PR.

**Pull request closed without merging**
