### PR TITLE
mqtt connection validateUser add ClientIdValidateException

### PR DESCRIPTION
**Pull request by archlevel**
Signed-off-by: gongping.zhu <gongping.zhu@neucore.com>

### CODE REVIEW

**Comment by archlevel** [comment]
adjust ActiveMQServerMessagePlugin

add RemotingConnection param for beforeMessageRoute、afterMessageRoute

and @Deprecated zhe none RemotingConnection param beforeMessageRoute、afterMessageRoute method

**Comment by archlevel** [comment]
add RemotingConnection to afterMessageRoute beforeMessageRoute method;and sendWill will invoke

**Comment by archlevel** [comment]
overloading beforeMessageRoute 、afterMessageRoute default implement

**Comment by archlevel** [comment]
fixed checkstyle error

**Comment by archlevel** [comment]
new file add licenses

**Comment by jbertram** [comment]
Couple of things:

- All commits should be squashed into a single commit. You have multiple commits here that need to be squashed.
- Tests are required to ensure the new code works as expected and to mitigate regressions in the future. You don't have any tests.
- Commits need clear commit messages which indicate why the change is being made.
- You need a Jira for changes of this size, and the Jira needs to be part of the commit message.

**Comment by archlevel** [comment]
fixed code style

**Comment by archlevel** [comment]
fixed PostOfficeImpl to new ActiveMQServerMessagePlugin new Method

**Comment by archlevel** [comment]
fixed code style catch

**Comment by jbertram** [comment]
@archlevel, please address the issues outlined in my previous comment. Thanks!

**Comment by archlevel** [comment]
https://issues.apache.org/jira/browse/ARTEMIS-3913

**Comment by archlevel** [comment]
@jbertram https://issues.apache.org/jira/browse/ARTEMIS-3913

**Comment by jbertram** [comment]
@archlevel, I'm not sure why you keep pasting the same link. Can you address the 4 points I made in my previous comment?

**Pull request closed without merging**
