### PR TITLE
ARTEMIS-358 test case for topic disappearing on disconnect without unsub

### PR DESCRIPTION
**Pull request by scop**
Test case (not a fix) demonstrating the issue.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
it looks a non durable subscriber. The subscription should go away as expected, right? Or am I missing something?

**Comment by scop** [comment]
You seem to be missing that it's the *topic* (not subscription) that kind of goes away; trying to send to the topic starts to produce error messages.

**Comment by scop** [comment]
(Well, the subscription goes away too, but that's expected.)

**Comment by clebertsuconic** [comment]
I am merging the test

**Pull request closed without merging**
