### PR TITLE
Update version of netty4

### PR DESCRIPTION
**Pull request by paulgallagher75**

### CODE REVIEW

**Comment by mtaylor** [comment]
@paulgallagher75 Netty version upgrades have stung us in the past, so I'm going to run the full test suite against this before merging.  Thanks.

**Comment by tabish121** [comment]
Netty upstream is at 4.0.39.final with some thread safety fixes amongst others with 4.0.37.final being a bit dated at this point, recommend moving to the latest if making the jump.

**Comment by jbertram** [comment]
I think the Netty upgrade may have broken a bunch of the large-message tests.  See https://builds.apache.org/job/ActiveMQ-Artemis-Nightly-Regression-Test/582/.  I get failures in org.apache.activemq.artemis.tests.integration.client.LargeMessageCompressTest when I run locally as well, but if I put the Netty version back to 4.0.32.Final all the tests pass.

**Comment by jbertram** [comment]
I sent a PR to deal with the regression.  See https://github.com/apache/activemq-artemis/pull/655.

**Comment by tabish121** [comment]
Netty just turned around a hotfix release for issues in the 4.0.39.Final release, new version is 4.0.40.Final

**Pull request merged**
