### PR TITLE
ARTEMIS-4391 tests: rework AssertionLoggerHandler

### PR DESCRIPTION
**Pull request by amarkevich**

### CODE REVIEW

**Comment by amarkevich** [comment]
> was there any other reason why you did that?

First idea was to avoid Log2j plugin annotation magic - but during the implementation found a way to make a bunch of improvements

**Comment by clebertsuconic** [comment]
@amarkevich you renamed the PR.. you should Renae the commit:


git commit --amend
edit with the new name
git push origin -f


if you can't do it... I will do it myself.. but it's always best to keep your original commit.

**Comment by clebertsuconic** [comment]
a few tests failing on the assertion:

[Test and Examples / Test / 4 / org.apache.activemq.artemis.tests.integration.cluster.failover.quorum.PluggableQuorumReplicaTimeoutTest.testFailbackTimeout](https://main-jenkins-csb-amq-broker.apps.ocp-c1.prod.psi.redhat.com/job/activemq-artemis/job/activemq-artemis-pipeline/2929/testReport/junit/org.apache.activemq.artemis.tests.integration.cluster.failover.quorum/PluggableQuorumReplicaTimeoutTest/Test_and_Examples___Test___4___testFailbackTimeout/)
[Test and Examples / Test / 3 / org.apache.activemq.artemis.tests.integration.paging.GlobalPagingTest.testCommitOnSend[storeType=FILE]](https://main-jenkins-csb-amq-broker.apps.ocp-c1.prod.psi.redhat.com/job/activemq-artemis/job/activemq-artemis-pipeline/2929/testReport/junit/org.apache.activemq.artemis.tests.integration.paging/GlobalPagingTest/Test_and_Examples___Test___3___testCommitOnSend_storeType_FILE_/)
[Test and Examples / Test / 0 / org.apache.activemq.artemis.tests.integration.paging.MaxMessagesPagingTest.testFailMaxMessage](https://main-jenkins-csb-amq-broker.apps.ocp-c1.prod.psi.redhat.com/job/activemq-artemis/job/activemq-artemis-pipeline/2929/testReport/junit/org.apache.activemq.artemis.tests.integration.paging/MaxMessagesPagingTest/Test_and_Examples___Test___0___testFailMaxMessage/)
[Test and Examples / Test / 0 / org.apache.activemq.artemis.tests.integration.paging.MaxMessagesPagingTest.testFailMaxMessageGlobal](https://main-jenkins-csb-amq-broker.apps.ocp-c1.prod.psi.redhat.com/job/activemq-artemis/job/activemq-artemis-pipeline/2929/testReport/junit/org.apache.activemq.artemis.tests.integration.paging/MaxMessagesPagingTest/Test_and_Examples___Test___0___testFailMaxMessageGlobal/)

**Comment by clebertsuconic** [comment]
@amarkevich I will take a look shortly (this afternoon) but I would appreciate  if you happen to be able to check them

**Comment by clebertsuconic** [comment]
very nice contribution! tests are good now.

Thank you so much for this!

**Pull request merged**
