### PR TITLE
[ARTEMIS-1939]Remove space from parameter annotations name in ActiveMQServerControl

### PR DESCRIPTION
**Pull request by shailendra14k**
JIRA:- https://issues.apache.org/jira/browse/ARTEMIS-1939

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
Does this change the current exposed JMX endpoints?

**Comment by clebertsuconic** [comment]
it's just changing the parameter name.. why is this an issue?

**Comment by clebertsuconic** [comment]
I already saw it...
will merge it and bring it into 2.6.x

**Comment by michaelandrepearce** [comment]
@clebertsuconic its a point that if its changing a public exposed api which jmx is then is the change back compatible. As existing users will/could have code hooked in for monitoring or other reasons

**Comment by clebertsuconic** [comment]
@michaelandrepearce From my interpretation.. these are only used in querying arguments.. for the actual calls you just need to pass in arguments... so I did not see any issue with compatibility because of that.

We have a few tests within the testsuite and they are not affected. 

SO think it's safe!

**Comment by michaelandrepearce** [comment]
@clebertsuconic thanks.

**Pull request closed without merging**
