### PR TITLE
ARTEMIS-857 Add JMX endpoints to view and reset groups

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Expose method to return current mappings of groups to consumers
Expose methods to reset (remove) specific group mapping from groupID to Consumer
Expose methods to reset (remove) all group mappings

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
Just working through the low hanging fruit thats needed to unblock artemis to become activemq 6.
as per:
http://activemq.apache.org/activemq-artemis-roadmap.html

**Comment by gaohoward** [comment]
@michaelandrepearce The code is fine I think. It'll be nice you add some unittests (e.g. in QueueControlTest) to verify it works. Also I find that the "Group" in method names a bit confusing.
Would be using MessageGoup instead more clear? I'm not sure about that as I'm not a native speaker, just a personal opinion.

**Comment by michaelandrepearce** [comment]
At the core layer it’s called group eg that’s the name within core message, and other settings around this. 

I’ll add test though.

**Comment by michaelandrepearce** [comment]
Test case added to QueueControlTest

**Pull request closed without merging**
