### PR TITLE
ARTEMIS-4630 Validate if the pid is really from Artemis

### PR DESCRIPTION
**Pull request by angelogalvao**
Fix a typo in the orignial commit.

In rare cases the status is returning 'running' to a process
that is not Artemis. It was create a extra level of verification
by validating if the running process working directory is the
same of ${ARTEMIS_INSTANCE}.

### CODE REVIEW

**Comment by gemmellr** [comment]
I cherry-picked the fix and pushed it since the PR had conflicts.

**Comment by jbertram** [comment]
After further investigation I don't think this solution is valid. The problem is that `lsof -a -d cwd -p <pid>` will report the directory from which the `artemis-service` script _was executed_. However, this script can be invoked from *any* directory. Therefore, it's very easy to break the script with this change such that it actually starts the broker but reports that it didn't and then continues to report the wrong status.

I will revert these commits soon.

**Comment by gemmellr** [comment]
(I actually only cherry-picked the second commit earlier, I thought the first was the same as yesterdays.)

Reverting seems reasonable based on what you just said. FWIW past 'check the process' stuff I have seen tended to just add something as a marker to the command run originally, so it could be looked for later.

**Comment by jbertram** [comment]
These commits have been reverted.

@angelogalvao, I think if we want to address this problem we need to determine _how_ the wrong pid made it into `artemis.pid` in the first place.

**Pull request closed without merging**
