### PR TITLE
ARTEMIS-2149 Protecting message.sendBuffer from races encoding it

### PR DESCRIPTION
**Pull request by clebertsuconic**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@michaelandrepearce  can you review this one please.

**Comment by clebertsuconic** [comment]
This is now ready to be merged.. (I had a word WIP on the name here before);

**Comment by clebertsuconic** [comment]
@michaelandrepearce I will merge this now.. but if you could still review it after I merged it? we can send further commits.

**Comment by michaelandrepearce** [comment]
Another thing ive noticed is currently where validBuffer is changed its not protected its only volatile, so you could enter syncronized method do the validBuffer check, but then subsequently because the validBuffer isn't protected it could change, before you exit the synced method.

**Comment by michaelandrepearce** [comment]
@clebertsuconic did you see this?

**Comment by michaelandrepearce** [comment]
re validBuffer im just wondering to simply avoid any possible future issue.... all it takes is a year or two's time and we all forget about this and someone implements something...

**Comment by michaelandrepearce** [comment]
re 2.0.0 and 2.6.x i fully blame @franz198 , little speed deamon! ;) :)

**Comment by franz1981** [comment]
@michaelandrepearce Someone has summoned me? If you repeat my name 3 times I'll disappear (cit: Beetlejuice)

**Comment by clebertsuconic** [comment]
@michaelandrepearce I added a test to encode / decode in multi-thread. it should be enough.

**Pull request merged**
