### PR TITLE
Artemis 1373

### PR DESCRIPTION
**Pull request by gtully**
- Have the ldapLoginModule do role mapping for any artemis UserPrincipal present in the subject
 - support using kerberos to authenticate to ldap

### CODE REVIEW

**Comment by jbertram** [comment]
The code looks good to me, but I'd love to see some documentation updates to go along with this.

**Comment by gtully** [comment]
I will push the doc updates directly if that is ok

**Comment by jbertram** [comment]
It's really nice to have the documentation update on the same commit as the code update so it's easier to understand everything when looking back through the history.  However, if that's especially problematic for you then I'm fine with you pushing the doc update separately.

**Comment by clebertsuconic** [comment]
I will merge now.. @gtully can update docs later.

**Pull request closed without merging**
