### PR TITLE
ARTEMIS-286 Upgrade Netty to version 4.0.32.Final

### PR DESCRIPTION
**Pull request by oscerd**
Hi,

This PR is related to:
https://issues.apache.org/jira/browse/ARTEMIS-286

Andrea

### CODE REVIEW

**Comment by jbertram** [comment]
Two questions:

1) Is there a particular reason for this upgrade aside from simply keeping up with the latest release?

2) Can you link to the change-log or the release notes for this Netty version?

**Comment by oscerd** [comment]
Hi @jbertram 

1) No, there isn't a particular reason, just keeping up with latest release.

2) Here is the release notes: http://netty.io/news/2015/09/30/4-0-32-Final.html

Andrea

**Comment by oscerd** [comment]
I'd like starting contributing on this project, and usually I start from dependency upgrade, to understand how the project build works, what are the main modules and so on.

**Comment by clebertsuconic** [comment]
@oscerd let us know how we can help you on contributing. IRC @ freenode is a good channel to talk real time...  or the dev list

**Pull request closed without merging**
