### PR TITLE
ARTEMIS-830 Remove cyclic dependencies from artemis-jdbc-store

### PR DESCRIPTION
**Pull request by bennetelli**
Removes cyclic dependencies between classes and packages in the artemis-jdbc-store projetct by moving classes and methods to other locations and reducing the visibility of classes, fields and methods. Solving cyclic dependencies is important to keep the codebase maintainable. Scenarios where "everything uses everything" should be avoided.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
```
[INFO] --- maven-bundle-plugin:3.0.0:install (default-install) @ artemis-hqclient-protocol ---
[INFO] Starting audit...
/work/apache/six/artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/file/PostgresSequentialSequentialFileDriver.java:23:1: error: Redundant import from the same package - org.apache.activemq.artemis.jdbc.store.file.JDBCSequentialFile.
/work/apache/six/artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/file/PostgresSequentialSequentialFileDriver.java:24:1: error: Redundant import from the same package - org.apache.activemq.artemis.jdbc.store.file.JDBCSequentialFileFactoryDriver.
Audit done.
[INFO] There are 2 errors reported by Checkstyle 6.11.2 with /work/apache/six/artemis-jdbc-store/../etc/checkstyle.xml ruleset.
[ERROR] src/main/java/org/apache/activemq/artemis/jdbc/store/file/PostgresSequentialSequentialFileDriver.java:[23,1] (imports) RedundantImport: Redundant import from the same package - org.apache.activemq.artemis.jdbc.store.file.JDBCSequentialFile.
[ERROR] src/main/java/org/apache/activemq/artemis/jdbc/store/file/PostgresSequentialSequentialFileDriver.java:[24,1] (imports) RedundantImport: Redundant import from the same package - org.apache.activemq.artemis.jdbc.store.file.JDBCSequentialFileFactoryDriver.

```

**Comment by clebertsuconic** [comment]
do you mind closing this PR, it would be superseded by #872 where I already fixed the checkstyle and imported your commit there.

**Comment by bennetelli** [comment]
Okay.

**Comment by clebertsuconic** [comment]
Can you just close it?

I tried to close it myself and it didn't work.

**Comment by bennetelli** [comment]
closed.

**Pull request closed without merging**
