### PR TITLE
Improve CLI create option descriptions

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
Merged.. can you close it please due to github/apache issues integration

**Comment by clebertsuconic** [comment]
@scop  can you close it please?

**Comment by scop** [comment]
Sure, but I don't see the merge here yet either?

**Comment by clebertsuconic** [comment]
It's on the apache branch for sure. something is rotten on the github mirror.

**Comment by clebertsuconic** [comment]
@scop it's on the github fork as well, can you close it?

We will have to keep closing PRs manually until this integration is fixed. This is merged for sure

**Pull request merged**
