### PR TITLE
NO-JIRA Sort IDE build since AuditLoggerAddition

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Add release profile for javadoc sorting ide build issue since Audit Logger was added

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
As mentioned on its PR, since https://github.com/apache/activemq-artemis/pull/2579 was merged im constantly having to revert it, to make local build and working in my IDE (IntelliJ) as it was, as was causing generated files at root target project level which then don't compile. Maven was fine. Checking other modules which have loggers, it seems this is the one common element missing from the module where the new Audit Logger was added, and seems to do the trick. Noted it all builds fine from maven, its just an ide issue.

@gaohoward and @clebertsuconic if you could look at please. ta. Happy for alternative fix also, just this seems to work.

**Comment by clebertsuconic** [comment]
@michaelandrepearce I hope it's not too late to reach you on this... sorry for my delay

I have no issues on Idea. I have however from time to time to git clean -xdf and rebuild my workspace. But that's been an ongoing issue for me as I change branches all the time.


Can you rebuild your workspace before we decide on merging this please?

**Comment by michaelandrepearce** [comment]
Will do once i get a new laptop next week ;)

**Comment by michaelandrepearce** [comment]
@cl

**Pull request closed without merging**
