### PR TITLE
ARTEMIS-718 - AMQP type message bodies are being lost

### PR DESCRIPTION
**Pull request by andytaylor**
https://issues.apache.org/jira/browse/ARTEMIS-718

### CODE REVIEW

**Comment by andytaylor** [comment]
dont merge this yet

**Comment by clebertsuconic** [comment]
@andytaylor it looks good. Why not merge yet. tests are failing?

**Comment by andytaylor** [comment]
its fine to merge now

**Comment by mtaylor** [comment]
@andytaylor looks like this failed again.  Could you take a look

**Comment by clebertsuconic** [comment]
@mtaylor doesn't seem related to his changes

**Comment by clebertsuconic** [comment]
I'm running the testsuite manually. if all ok I will merge this.

**Pull request closed without merging**
