### PR TITLE
ARTEMIS-1622 Reduce memory footprint of QueueImpl

### PR DESCRIPTION
**Pull request by franz1981**
LinkedListImpl is turned into an optionally intrusive linked list by allowing message references to extend Node

### CODE REVIEW

**Comment by franz1981** [comment]
I've already run CI on it and it seems to be safe.
Just few numbers to justify it...
On master:
image

While with this PR:
image
800 MB vs 640 MB = 160 MB saved bytes 
Given the default broker settings for the JVM the math is:

- each `Node` instance is 32 bytes = 12 bytes obj header + 16 bytes of fields + 4 bytes of padding to have 8 byte alignment
- the original `MessageReferenceImpl` was 48 bytes, including a 12 bytes header
- this PR `MessageReferenceImpl` is 64 bytes = 48 bytes (of the original) + 16 bytes (of `Node`) + 0 bytes of padding (64 is already 8 bytes aligned)

We're saving 4 bytes of padding and 12 bytes of Object header from `Node` = 16 bytes for each message entry.
If we have 10_000_000 messages we're saving 160 Megabytes.

IMO there are few other checks to be performed and need anyone that knows how the original LinkedListImpl works, but the change is easy to be reverted: I've already checked that there aren't evident memory leaks, but any feedback is appreciated :+1:

**Comment by michaelandrepearce** [comment]
@franz1981 why did we need to loose the generics on Node? it now means theres a cast on get, and alot of un-needed change IMO.

if it was due to the extension now made here: 

PagedReferenceImpl extends LinkedListImpl.Node 

this could have been: PagedReferenceImpl extends LinkedListImpl.Node<PagedReferenceImpl>

and like wise in MessageReferenceImpl

**Comment by michaelandrepearce** [comment]
Makes sense and agreed anyone using the list wouldn’t be exposed to the node

**Comment by franz1981** [comment]
@michaelandrepearce That's the best I could think to reduce the number of changes but honestly `MessageReferenceImpl` isn't *really* forced to use himself as a parameter

**Comment by michaelandrepearce** [comment]
@franz1981 looks good to me.

**Pull request closed without merging**
