### PR TITLE
ARTEMIS-146 Fix Queue auto-creation

### PR DESCRIPTION
**Pull request by gaohoward**

### CODE REVIEW

**Comment by gaohoward** [comment]
I don't think this has to do with any JMS queues and JMX objects. It's only for openwire. Why it is not valid?

**Comment by clebertsuconic** [comment]
First, you are changing semantics of a production of a production server because the test is not adapting... it's wrong.

Second, when a JMS Object is created it needs to also create JMS objects for the JMS Created Queue, that should happen through the JMS Manager. You are cutting this directly into a core-queue, it's also wrong.


Why can't you fix the test and add the JMS Manager?

**Comment by gaohoward** [comment]
OK I get your point. The reason I didn't want to bring in JMS manager is because openwire is not supposed to depends on JMS manager. It should depends only on the core server. Like jms manager, the openwire should only be a facade layer around core. isn't it?

**Comment by clebertsuconic** [comment]
I don't think so.  Openwire is a jms protocol. Hence it needs the jms manager

**Comment by clebertsuconic** [comment]
I am going to sleep now.  And I won't be able to look further before my morning.  Maybe I'm missing something.  


Maybe you could abstract the manager without changing production cases.  That's what concerns me.

**Comment by gaohoward** [comment]
ok, just back from the visa application center (it's been 5 hours waiting). Let's just bring in the JMS manager as you suggested. If anything goes wrong we can refactor it later.

**Comment by gaohoward** [comment]
Hi Clebert,
I updated the branch, can you take a look?

Thanks
Howard

**Comment by gaohoward** [comment]
:)

**Pull request merged**
