### PR TITLE
ARTEMIS-2655 support auto-creation w/FQQN & STOMP

### PR DESCRIPTION
**Pull request by jbertram**

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
How are we differentiating if it should be anycast or multicast queue?

**Comment by jbertram** [comment]
I added a blurb to [the documentation](https://github.com/apache/activemq-artemis/blob/master/docs/user-manual/en/stomp.md#routing-semantics) not too long ago describing how control routing semantics with STOMP.

As far as the code goes, a `RoutingType` is passed to the `autoCreateDestinationIfPossible` method which is based on the frame's header or destination prefix. If that is `null` then it uses the default value specified in the address-settings.

**Comment by michaelandrepearce** [comment]
Thanks.

**Comment by michaelpearce-gain** [comment]
i think you can merge @jbertram its been 2 weeks an no other comments

**Pull request closed without merging**
