### PR TITLE
ARTEMIS-1783 Remove need for guava in client

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Refactor away from Guava memorize based on Guava Supplier to using java.util.Supplier and our own memorizer code.

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
@clebertsuconic @jbertram alternative to https://github.com/apache/activemq-artemis/pull/2081 so we don't have to increase client side dependencies.

**Comment by franz1981** [comment]
@michaelandrepearce It looks fine to me: i haven't considered the client side deps on the past PR, sorry!

**Comment by michaelandrepearce** [comment]
@franz1981 thanks for checking, will wait for @clebertsuconic and @jbertram to review also before we merge.

**Comment by jbertram** [comment]
I like it better than my solution. +1

**Comment by clebertsuconic** [comment]
@michaelandrepearce We will have guava on artemis.commons... we would need to find a solution for those collections as well.

**Comment by clebertsuconic** [comment]
or just live with guava.

**Comment by michaelandrepearce** [comment]
So guava was added client side only due to this change right. I think server side has had guava for a time. Concern I think is more about client dependencies not so much server side right?

**Comment by michaelandrepearce** [comment]
@clebertsuconic removed guava entirely, and replaced either with Java Function equivalents (majority) or added a few extra bits in Artemis utils.

**Comment by clebertsuconic** [comment]
@michaelandrepearce nice one... we only need guava now for the CLI.. but that won't affect any runtime.. which is great!

**Comment by michaelandrepearce** [comment]
@clebertsuconic where is it in the CLI, i must have not noticed, if you can point me to it,  ill try see what we can do there.

**Comment by clebertsuconic** [comment]
@michaelandrepearce io.airlift itself is using it.

I don't consider a big deal. this is not leaking to the server.

**Pull request closed without merging**
