### PR TITLE
ARTEMIS-3584 show multiple representations of the payload on "Browse Queue"

### PR DESCRIPTION
**Pull request by erwindon**
see https://issues.apache.org/jira/browse/ARTEMIS-3584

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@erwindon are you finishing this PR? it's been a draft for 27 days now.

**Comment by erwindon** [comment]
@clebertsuconic yes, this is still on my list. already have nice results, see https://issues.apache.org/jira/browse/ARTEMIS-3584. I'll do a rebase now and probably work in the Christmas holiday on it.

**Comment by clebertsuconic** [comment]
@erwindon no worries.. I was just checking if this was getting ready before the release tomorrow...


We can do another one next year

**Comment by jbertram** [comment]
@erwindon, this one has been open awhile, but I see you added a few commits a couple weeks ago. Are you still working on this?

**Comment by erwindon** [comment]
@jbertram 
This is moving slower than expected and I've made no progress in a year on this.
The todo-list is in [ARTEMIS-3584](https://issues.apache.org/jira/browse/ARTEMIS-3584).
I'm still interested in finishing this.
I'll close this PR and the related issue and work on this in the background instead.

**Comment by jbertram** [comment]
@erwindon, thanks for following up!

**Pull request closed without merging**
