### PR TITLE
NO-JIRA artemis.data system property 

### PR DESCRIPTION
**Pull request by cenitfish**
Within the artemis.xml the locations for storing the data can be configured (paging-directory, bindings-directory, journal-directory, large-messages-directory). Would it be possible to additionally support the system property artemis.data? The configuration would then be much easier.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
Sure we can do that. 

But artemis.instance was meant for that already.  What would be the use case?

**Comment by clebertsuconic** [comment]
this is just renaming karat.data property as artemis.data right?

I just realized that the context of your change is OSGI only?

**Comment by cenitfish** [comment]
Simply renaming karaf.data to artemis.data would also suffice for our purposes. In the meantime I tried the system property artemis.instance, but without success.

**Comment by cenitfish** [comment]
And yes we work with Apache Karaf OSGi environment.

**Comment by clebertsuconic** [comment]
ok.. fine with me...

Can you create a JIRA, and then:

```
git commit -a --amend
```

edit your NO-JIRA with the JIRA

```
git push -f
```

?

**Comment by cenitfish** [comment]
I did and thank you!

**Comment by michaelpearce-gain** [comment]
JIRA?

**Comment by michaelpearce-gain** [comment]
Ok ignore my last comment i see commit is with Jira, maybe just update the PR name too ;) as this is what i picked up on quickly reviewing backlog of  PR's i havent put my eyes on.

**Pull request closed without merging**
