### PR TITLE
ARTEMIS-1787 Openwire message should not contain internal property

### PR DESCRIPTION
**Pull request by stanlyDoge**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
same thing I asked on the JIRA. Why it shouldn't? why only on noLocal?

trying to get some context on the why it should not be included...


it would be nice to include such thing on the commit description please.

**Comment by stanlyDoge** [comment]
This PR is partly reverting https://github.com/apache/activemq-artemis/pull/1734

AFAIK including some internal properties break JMS API specification.

**Comment by michaelandrepearce** [comment]
As noted effort should go to native openwire message support #1793. Can we close this.

**Comment by michaelandrepearce** [comment]
Im closing this, as no update since may last year, or any update since last call out 6 days ago.

**Pull request closed without merging**
