### PR TITLE
ARTEMIS-2025 Ensure correct calculation of message body size

### PR DESCRIPTION
**Pull request by mtaylor**

### CODE REVIEW

**Comment by mtaylor** [comment]
@clebertsuconic It's called on receiveBody() so potentially once per message.  I will look for an alternate approach.

**Comment by mtaylor** [comment]
@clebertsuconic done.

**Comment by clebertsuconic** [comment]
The Failure on your PR check is because you missed calling checkEncode(). It's currently private but we can open it to protected.


but don't worry.. I will amend the change as yours and merge it.

BTW: It's Sunday.. and we're working here :)

**Comment by mtaylor** [comment]
@clebertsuconic cheers

**Comment by clebertsuconic** [comment]
@mtaylor this test is failing after this:
org.apache.activemq.artemis.tests.integration.jms.jms2client.BodyTest.testBodyConversion

**Comment by michaelandrepearce** [comment]
@clebertsuconic @mtaylor seems also   
MessageBodyTest.testBytesMessage is broker due to this change, and any PR build is failing now.

**Pull request closed without merging**
