### PR TITLE
ARTEMIS-1805 fix for broker operations in hawtio

### PR DESCRIPTION
**Pull request by stanlyDoge**
There are few operations, which causes an error while selected in hawtio console under broker/operations. Adding @Operation annotation to these methods fixes an error, but methods are exposed and I am not 100% sure that is correct. I also unified capitalized first letter of methods description.

### CODE REVIEW

**Comment by gaohoward** [comment]
@stanlyDoge I didn't see that the two methods (sendQueueInfo.. and updateDuplicate...) in ActiveMQServerControl are used anywhere. Could simple deleting them from the interface solve the hawtio error?

**Comment by stanlyDoge** [comment]
@gaohoward Done.

**Comment by gaohoward** [comment]
@stanlyDoge you got to remove @Override annotations from ActiveMQServerControlImpl also.

**Comment by stanlyDoge** [comment]
@gaohoward Done.

**Pull request closed without merging**
