### PR TITLE
ARTEMIS-1206 SetClientID from Core ConnectionFactory is not unique

### PR DESCRIPTION
**Pull request by clebertsuconic**

### CODE REVIEW

**Comment by tabish121** [comment]
Seems a bit odd that core JMS client functionality is being tested in the AMQP integration tests package, I'd suggest that the AMQP tests belong here and tests for the core JMS client belong in whatever area that client is already being tested in, otherwise it is hard to later on find the core client coverage tests.

**Comment by clebertsuconic** [comment]
duh, you're right.. ammending

**Comment by clebertsuconic** [comment]
@tabish121 done

**Comment by clebertsuconic** [comment]
^^^ This is why PRs are good... everyone is entitled to make something stoopid.. this gives another chance to be caught 👍

**Comment by tabish121** [comment]
Test Qpid JMS based version of the test is actually also not necessary as what you are testing there is that the broker is respecting the AMQP JMS Mapping defined SOLE_CONTAINER capability which is already tested here: https://github.com/apache/activemq-artemis/blob/master/tests/integration-tests/src/test/java/org/apache/activemq/artemis/tests/integration/amqp/AmqpInboundConnectionTest.java#L201

The JMS client tests its own implementation of the setClientID etc methods.

**Comment by clebertsuconic** [comment]
The test you showed doesn't seem to be using it throught the connection factory property. I don't think it hurts a small extra test.

**Comment by clebertsuconic** [comment]
will have to fix the JORAM tests...

**Comment by clebertsuconic** [comment]
@tabish121  fixed JORAM... your other test is not validating the same property through the CF. I would leave it there just in case.. it's a fairly simple test.. it doesn't hurt.

**Comment by tabish121** [comment]
It is indeed validating the same property, that property is the SOLE_CONTAINER capability that is sent in the open frame to indicate the uniqueness of the client ID as being required.

What you are testing is the Qpid JMS client specific implementation of the setClientID and how it controls when the open frame is sent.  What you aren't testing in the new test is the affect of not specifying a client ID and also the behavior of setClientID through the Connection or no client ID being set and calling connection start.

So if you feel you need this particular test case then for completeness I'd argue you test all variations of client ID / no client ID and ConnectionFactory vs Connection setClientID.

**Comment by clebertsuconic** [comment]
@tabish121 I'm just adding the same case where it failed on core JMS. Just wanted to make sure the property from the Connection Factory is also applied to the connection the same way. I think that's a valid test.. it didn't fail but I don't see a reason to remove it.

**Comment by gemmellr** [comment]
I don't think Tim is saying its not valid so much as it is essentially just a client test in this situation (and one of several that could exist), with the brokers required AMQP behaviour already verified by more explicit testing around the related SOLE_CONTAINER capability that the AMQP JMS client uses to achieve its desired behaviour, making it unclear why you would really add it to the brokers test suite when from the brokers perspective its basically just increasing the length of the test suite. I'd say the same personally.

**Comment by clebertsuconic** [comment]
@tabish121 @gemmellr fair enough.. test removed.

**Pull request closed without merging**
