### PR TITLE
ARTEMIS-1874 fix NPE setting object property

### PR DESCRIPTION
**Pull request by rpelisse**
Upstream Issue: https://issues.apache.org/jira/browse/ARTEMIS-1874
Issue: https://issues.jboss.org/browse/JBEAP-15516
No upstream PR required, changes already in master

This is just a backport of the fix into the 1.x branch. I've setup the PR just to make the backport easy for devs, if you prefer to cherry-pick this fix later on yourself, feel free to simply close this PR! (or ask me to do it).

### CODE REVIEW

**Comment by rpelisse** [comment]
The CI run failed due to some "connection refused". It looks unrelated to my changes, but please let me know if you think otherwise!

**Comment by clebertsuconic** [comment]
@rpelisse what is the commit ID upstream? can you use cherry-pick -x (or amend the commit with the full hash?)


example from another commit:

```
commit 19998d310f143ad5370683db42c63f64b43ee338
Author: Justin Bertram <jbertram@apache.org>
Date:   Wed Sep 26 14:27:14 2018 -0500

    ARTEMIS-2098 potential NPE when decoding protocol
    
    (cherry picked from commit c72bf53cb178d2d9d310f3f369c0cbdb22e6f50c)


```

**Comment by clebertsuconic** [comment]
@rpelisse we have started using cherry-pick -x on the other branches to make it easier to find correlations between the branches.

**Comment by rpelisse** [comment]
But of course! Just done so (and thanks for the tip, never noticed this -x option, it's pretty neat).

**Pull request merged**
