### PR TITLE
ARTEMIS-4331 bumped jgroups version

### PR DESCRIPTION
**Pull request by erwindon**
see https://issues.apache.org/jira/browse/ARTEMIS-4331

### CODE REVIEW

**Comment by jbertram** [comment]
I'm setting this to draft until JGroups 5.2.15 is actually available.

**Comment by erwindon** [comment]
I've updated the version designation.
Sorry, I was a bit confused about the release status as the story from jgroups was already marked with that release number.
(and you answered the question on how to proceed, thx)

**Comment by erwindon** [comment]
Jgroups 5.2.15.Final has been published.
But also its successor 5.2.16.Final is already there.
I've updated the PR to use 5.2.16.Final.

**Comment by erwindon** [comment]
checks failing with "Unable to resolve wrap_file__home_runner_.m2_repository_org_jgroups_jgroups_5.2.16.Final_jgroups-5.2.16.Final.jar/0.0.0: missing requirement[...]"
so seems related
back to local development...

**Comment by erwindon** [comment]
Artemis build procedure works fine for current jgroups version 5.2.0.
jgroups 5.2.1 does not exist.
Artemis build procedure works fine for jgroups version 5.2.2.
jgroups 5.2.3 does not exist.
Artemis build procedure with jgroups 5.2.4+ fails in 'artemis-features'.

rebase did not change anything about that.

@jbertram 
unfortunately, I have to give up here as this is unknown territory...

**Comment by jbertram** [comment]
I took a look at this, and I couldn't figure it out either. I _suspect_ there's something going awry with the inclusion of Byteman as a `compile` dependency rather than a `test` dependency. See https://github.com/belaban/JGroups/commit/69af029ee35f259ea3323552455ed411545e3c3e.

Generally speaking I dislike the `artemis-features` module because this isn't the first time it's tripped me up. I know there are folks out there who use the Karaf integration, but it seems like a rather small set of users to deal with this head-ache although I readily admit the head-ache is probably most due to my ignorance of how it works.

**Comment by gemmellr** [comment]
I put together a new PR: https://github.com/apache/activemq-artemis/pull/4550

**Pull request closed without merging**
