### PR TITLE
ARTEMIS-201 warn of potential OOME

### PR DESCRIPTION
**Pull request by jbertram**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@jbertram  think the following:

An user sets 100 destinations.. with 100M cache... the memory would be able to fit only 10 paged destinations..

The user has monitoring in place... whenever a consumer drops and page increases he will take action and restart the client...


that means... he would make sure he wouldn't get to the 100 paged message using monitoring tools...


That's a valid scenario.. with your messages users will assume they must have memory available at all times.

**Comment by jbertram** [comment]
Even though they have monitoring in place to avoid the OOME, the OOME is still possible if something were to malfunction with regards to the monitoring.  I think the WARN is still valid.  The broker has no way of knowing how it's actually going to be used.  It only knows how it has been configured.  Users can (and do) ignore WARN messages all the time when they know the messages don't apply to their use-case, but that doesn't mean the WARN messages aren't valid for lots of other use-cases.

**Comment by clebertsuconic** [comment]
My issue is not with showing a message.. it's with the message.    I think it should say something like.. You would run out of memory when you have more than X destinations in page mode.

Notice that you could have many shallow destinations that never receive more than a few messages a day... and users will get scared for that message....


it shouldn't even be a warning.. it could be an INFO!

**Comment by jbertram** [comment]
The scenario you outline (X addresses with Y max-size-bytes and Z heap-size that would require N addresses to go into paging mode before an OOME occurs) is just one possible scenario.  
The scenario I outlined previously is equally valid (1 address with Y max-size-bytes and Y/2 heap-size) and no paging would be involved before an OOME occurred so your suggested message wouldn't make sense.

As far as using getting scared of this WARN message when they have many shallow destinations that never receive enough messages to reach max-size-bytes I think they should be scared because their broker is in a vulnerable position.  If something goes wrong and they start getting increased message production then they'll go OOME due to their sub-optimal configuration.

Whether or not it should be a WARN or an INFO is debatable, IMO. Being vulnerable to an OOME if someone dumps a bunch of messages on the server seems fairly serious to me.

**Comment by clebertsuconic** [comment]
I'm not sure I agree with this, but I will merge it.

We could / should add a feature to start paging when a max global size is hit. We had such JIRA on hornetq but never completed it.

**Comment by clebertsuconic** [comment]
Can you at least say "when you have more than X destinations in page mode" on your log message?

X = Memory Size / Page MAX-Size... just as an approximation

**Comment by clebertsuconic** [comment]
on a second though it's not really needed. I will merge it

**Pull request closed without merging**
