### PR TITLE
ARTEMIS-1269 Simple Actor

### PR DESCRIPTION
**Pull request by clebertsuconic**
This is replacing an executor on ServerSessionPacketHandler
by a new actor.

This is to avoid creating a new runnable per packet received.

Instead of creating new Runnable, this will use a single static runnable
and the packet will be send by a message, which will be treated by a listener.

Look at ServerSessionPacketHandler on this commit for more information on how it works.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
There are a lot of possibilities for this...


Example: https://github.com/clebertsuconic/activemq-artemis/commit/116fb580a97514fac2a78598cc970d78717bb23d


I will have to figure out what's going on that it's not working.. but I will soon make this change.

**Comment by michaelandrepearce** [comment]
don't mean to be a pain, but why don't we use an existing framework, akka/vert.x? instead of making our own framework we will have to maintain?

**Comment by mtaylor** [comment]
@clebertsuconic I have two comments on this. 

Firstly, what is the goal of this patch.  Is the aim to reduce the GC overhead by reusing Runnables?  If so surely this could be done in a simpler fashion just be creating a Re-usable Runnable?

If the idea here is to "create a framework", I have to agree with Michael that we should be looking to reuse something that already exists.  There's quite a lot of movement towards using reactive patterns which is I believe what you are striving for here.  There are a few popular frameworks/libs for Java.  Have you looked at RxJava?

**Comment by clebertsuconic** [comment]
I don't  want to make a framework.  This is just to diminish GC on a few executors.  


Instead of creating a new runnable everybtime we pass in the data.

**Pull request merged**
