### PR TITLE
ARTEMIS-5050: misc improvements to 'Broker-to-Broker Connectivity' docs/index

### PR DESCRIPTION
**Pull request by gemmellr**

### CODE REVIEW

**Comment by jbertram** [comment]
Update `_book.adoc` as well to keep it in sync?

**Comment by gemmellr** [comment]
I forgot that existed :)

**Comment by gemmellr** [comment]
On first glance, I dont know that I can update it in quite the same way given it includes the files, and there is only 1 file (and splitting it doesnt necessarily make sense). Need to give it more thought tomorrow.

**Comment by gemmellr** [comment]
I pushed a change that moves the includes in _book.adoc around in the same overall sense as the index.adoc. Still not quite exactly the same but a lot closer.

**Comment by tabish121** [comment]
> I pushed a change that moves the includes in _book.adoc around in the same overall sense as the index.adoc. Still not quite exactly the same but a lot closer.

This looks to be about all you can do for that file, probably not time to split the broker connection docs apart but could do that if they grow to large in the future.

**Pull request merged**
