### PR TITLE
[ARTEMIS-684] Client connection are not balanced across cluster with any load balancing policy

### PR DESCRIPTION
**Pull request by bayern39**
https://issues.apache.org/jira/browse/ARTEMIS-684

### CODE REVIEW

**Comment by jbertram** [comment]
I'm not sure I agree with this change since it will impact existing load-balancing semantics which users may depend on.  Connection load-balancing is done per connection factory.  Connection factory objects are meant to be re-used so load-balancing on a per connection factory basis is reasonable.  It also gives users the flexibility of creating new connection factories in a single application and getting independent load-balancing from each.  With this change that will no longer be possible.

**Comment by bayern39** [comment]
@jbertram  Hi Justin,I have try another way fixed it!

**Comment by bayern39** [comment]
In fact,I think the no seed Random is better than it has.

**Comment by clebertsuconic** [comment]
I have sent another PR: #730 


Can you take a look please? Please close this one when that one is merged.


I'm not adding your example as I don't see much value for the distribution. (It's not even failing.. I would if the example failed).


Notice that I added a failing test validating the distribution issue.

**Comment by bayern39** [comment]
OK,I will do it.

**Comment by clebertsuconic** [comment]
@bayern39 if you actually agree with my change, you can probably close this one. 

Take a look at #730 and if you agree please close this one.


Also please review my changes in case I screwed up with something :)

**Pull request closed without merging**
