### PR TITLE
ARTEMIS-1391: Create a reproducer for this issue

### PR DESCRIPTION
**Pull request by ctron**
Signed-off-by: Jens Reimann <jreimann@redhat.com>

### CODE REVIEW

**Comment by clebertsuconic** [comment]
I wouldn't send a PR with just a test reproducer.. I would attach a patch to a JIRA instead.

**Comment by clebertsuconic** [comment]
it's probably ok though

**Comment by ctron** [comment]
I did talk to @mtaylor I understood that we would go that way.

I know you can't merge that right now, but we can wait for the fix to the made and then rebase and merge this PR.

**Comment by clebertsuconic** [comment]
@ctron  can you ammend the commit name then? 

like, adding test to reproduce the whatever case it was...


I don't like having to open JIRA when doing git log.. it's not practical.

**Comment by jbertram** [comment]
I sent PR #1539 to deal with this.  You can go ahead and close this one.

**Comment by ctron** [comment]
Thanks for fixing this!

**Pull request closed without merging**
