### PR TITLE
Fix MQTT build

### PR DESCRIPTION
**Pull request by scop**
putIfAbsent() is a ConcurrentHashMap method.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
I see, this would fail with JDK 1.7, and pass with 1.8... I'm merging

**Comment by gemmellr** [comment]
I'd suggest using the ConcurrentMap interface for the declarations rather than using the ConcurrentHashMap type directly, otherwise you can introduce scenarios where binaries produced from source compiled with JDK 8 targetting JDK7 won't actually work on JDK7 even though it is legal source and would work if compiled using JDK7.

**Comment by clebertsuconic** [comment]
@gemmellr I actually thought it was using ConcurrentMap, I read it wrongly... I will change it

**Comment by scop** [comment]
Makes sense, but the change @clebertsuconic made was to another field, not the one I changed, which shows that there's a bunch of this pattern going in this file as well as in the overall tree. PR #93 deals with a number of them if you like to have declarations that way.

**Comment by clebertsuconic** [comment]
@scop ouch! :) Good catch!

**Pull request closed without merging**
