### PR TITLE
Fix OpenWire queue auto-creation failure

### PR DESCRIPTION
**Pull request by gaohoward**

### CODE REVIEW

**Comment by jbertram** [comment]
I pushed a pretty big commit late Friday so you should probably rebase.  I don't think you'll have any conflicts, but just to be safe...

**Comment by gaohoward** [comment]
@jbertram Just rebased.

**Comment by clebertsuconic** [comment]
@jbertram @mtaylor  this should go on the artemis-780 branch directly.. no PR needed.


@gaohoward  can you close this and send directly to the branch after talking to @jbertram  and @mtaylor ?

**Comment by jbertram** [comment]
I've already looked at it and pulled it onto my branch.  Will push upstream when I finish some other work.

**Comment by clebertsuconic** [comment]
@gaohoward  can you close it then?

**Comment by gaohoward** [comment]
sure will do

**Pull request closed without merging**
