### PR TITLE
Try to cope with systems without "which" for finding java

### PR DESCRIPTION
**Pull request by scop**
whence -p should work with zsh, type -p with bash and ksh.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
How to test this? just remove JAVA_HOME as a property?

**Comment by clebertsuconic** [comment]
this one warrants a JIRA I think. Can you add a JIRA, set it to 1.5.0 (I will move it back to 1.4.0). And set the JIRA-id as part of the commit.

**Comment by clebertsuconic** [comment]
@scop what's the best to way to test this? remove JAVA_HOME? I couldn't have much success.

**Comment by scop** [comment]
Ensure `JAVACMD` and `JAVA_HOME` are not set and `which` is not installed, that should do it.

**Comment by scop** [comment]
@clebertsuconic also, in my opinion the separate try to get a full path to the java executable and the related -x test is somewhat questionable. The full path is not actually needed for anything, artemis would work just fine when invoked with java from PATH, without a full path to it. And the JAVACMD=java fallback will pretty much never work with the test. I think it would actually make sense to remove those checks and just try to use java directly. The Windows cmd scripts already do that. I've submitted this alternative approach in #733

**Pull request closed without merging**
