### PR TITLE
ARTEMIS-1828 CLI option for queue's routing-type

### PR DESCRIPTION
**Pull request by rakstar**
Optionally specify a queue routing type when creating a broker. Example:
"create --queues myqueue,mytopic:multicast". Defaults to anycast if
unspecified.

### CODE REVIEW

**Comment by jbertram** [comment]
IMO this deserves a JIRA. I created https://issues.apache.org/jira/browse/ARTEMIS-1828. Can you change the commit message to include this JIRA, e.g.:

    ARTEMIS-1828 CLI option for queue's routing-type

When you rebase and push -f this will also trigger a rebuild which hopefully will pass without any spurious errors.

**Comment by clebertsuconic** [comment]
Is this compatible with previous usages? what happens if I don't specify the rounting type?

**Comment by rakstar** [comment]
@jbertram Thanks for creating the issue. I updated my commit message and pushed (twice because I didn't rebase the first time, sorry).

@clebertsuconic It is backward compatible as it defaults to anycast if unspecified. I indicate this in the CLI help as well.

Thanks!

**Comment by michaelandrepearce** [comment]
@rakstar Looks good, was about to merge this (sorry been a bit busy with broker fixes), unfortunately theres a merge conflict now, are you able to rebase / resolve?

**Comment by rakstar** [comment]
@michaelandrepearce Rebased and resolved. Thanks! :)

**Comment by michaelandrepearce** [comment]
@rakstar thanks for the contribution, and again thanks for the patience.

**Comment by rakstar** [comment]
@michaelandrepearce no problem at all. Thanks for accepting my patch! :)

**Pull request closed without merging**
