### PR TITLE
ARTEMIS-1722 Don't copy message bytes unless needed

### PR DESCRIPTION
**Pull request by tabish121**
Alternate patch that doesn't copy the message bytes unless doing a
redelivery or skipping delivery annotations in the original version of
the message.  Proton-J will copy the bytes provided to the Sender's send
method so a copy isn't necessary on most common sends.

### CODE REVIEW

**Comment by tabish121** [comment]
@franz1981 I've updated this PR with changes to the common path based on your suggestions to me over on my fork.  Thanks for the review and ideas, even better now.

**Comment by jbertram** [comment]
If we want this in 2.5 I think we should merge it today.

**Comment by tabish121** [comment]
Need @clebertsuconic to give it a look

**Comment by clebertsuconic** [comment]
@tabish121 I'm actually running tests... leave it with me

**Pull request closed without merging**
