### PR TITLE
Add default constructor for reflection

### PR DESCRIPTION
**Pull request by binout**
When you use `org.apache.activemq.artemis.core.protocol.hornetq.client.HornetQClientProtocolManagerFactory` as protocol-manager-factory, this class needs to be instantiated by reflection.

Caused by: java.lang.RuntimeException: Your class must have a constructor without arguments. If it is an inner class, it must be static! org.apache.activemq.artemis.core.protocol.hornetq.HQPropertiesConversionInterceptor
	at org.apache.activemq.artemis.utils.ClassloadingUtil.newInstanceFromClassLoader(ClassloadingUtil.java:50)
	at org.apache.activemq.artemis.core.client.impl.ServerLocatorImpl$6.run(ServerLocatorImpl.java:1776)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.activemq.artemis.core.client.impl.ServerLocatorImpl.feedInterceptors(ServerLocatorImpl.java:1771)
	at org.apache.activemq.artemis.core.client.impl.ServerLocatorImpl.setIncomingInterceptorList(ServerLocatorImpl.java:816)
	at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.setIncomingInterceptorList(ActiveMQConnectionFactory.java:642)
	... 27 more
Caused by: java.lang.InstantiationException: org.apache.activemq.artemis.core.protocol.hornetq.HQPropertiesConversionInterceptor
	at java.lang.Class.newInstance(Class.java:427)
	at org.apache.activemq.artemis.utils.ClassloadingUtil.newInstanceFromClassLoader(ClassloadingUtil.java:47)
	... 32 more
Caused by: java.lang.NoSuchMethodException: org.apache.activemq.artemis.core.protocol.hornetq.HQPropertiesConversionInterceptor.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 33 more

### CODE REVIEW

**Comment by binout** [comment]
Ok sorry for this "quick and dirty" PR ....
I will rework the background and the form

**Comment by jbertram** [comment]
No apologies necessary. PRs are welcome and appreciated. We just need to follow best practices to ensure the code-base stays in good shape.

**Comment by jbertram** [comment]
I can't merge this as-is...
* You didn't fix the commit message as noted previously.
* There's no test as noted previously.
* All commits need to be squashed so that there's only a single commit.

Looking at the code on the master branch I don't see how this could actually because the `HQPropertiesConversionInterceptor` is never instantiated via reflection.  Perhaps you should start a thread on the user list so we can discuss your use-case in more detail.

**Comment by binout** [comment]
Ok, i close and i will start a discuss about my problem : activemq with hornetq compatibility inside a Wildfly 10.1.0.Final.

**Comment by clebertsuconic** [comment]
It makes sense to have this change.  It's just some cleanup needed on the committs

**Pull request closed without merging**
