### PR TITLE
Executor in JournalImpl for append operations

### PR DESCRIPTION
**Pull request by barreiro**
This new executor on the journal allows the removal of synchronization in most cases. It can enable other optimizations in the future as well.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
lets defer merging this until the release is done.

quite a big change now at the last minute.. better to wait next release.

**Comment by mtaylor** [comment]
@clebertsuconic I think we can start looking at this now that we have 1.3.0 out the door.  Are you able review?  Thanks.

**Comment by clebertsuconic** [comment]
@mtaylor  I want to compare this against #590. Especially on a test that is being added. 

Franceso proposed a garbage free approach on the journal that makes sense.. and I want to make sure this wouldn't make it inviable.

**Comment by mtaylor** [comment]
@clebertsuconic NP just checking we haven't forgot about this.  Cheers

**Comment by mtaylor** [comment]
@clebertsuconic Any update on this?  Did you manage to complete the comparison you wanted to do?

**Comment by clebertsuconic** [comment]
@mtaylor there's a test failure I need to take care before can merge this.

**Comment by clebertsuconic** [comment]
@barreiro did you think of using an executor from the ThreadPool? (ExecutorFactory.createExecutor()) from ActiveMQServerImpl?

What about using the same executor for the bindings and journal? this is creating a single thread for each journal even at low rates.


The issue with the tests is because of the lack of flushing the executor for certain non transactional tests. (ValidateTransactionalHealth being one).

**Comment by clebertsuconic** [comment]
@barreiro  sorry it took me this long to get into this.. but lets close this one soon.

**Comment by clebertsuconic** [comment]
The failures on Paging is because the system currently doubles the size of the buffer, because the address name is not encoded as part of every message, while it is encoded during journal.append. Something I will have to address.

**Comment by clebertsuconic** [comment]
This will need a JIRA and a squash of the commit here as well.

**Comment by barreiro** [comment]
Rebased

**Comment by clebertsuconic** [comment]
@barreiro just a FYI: I'm working on this.

**Comment by clebertsuconic** [comment]
@barreiro I wil need a JIRA, can you raise one on Artemis

**Comment by clebertsuconic** [comment]
@barreiro can you close this one please, #872 will replace this PR.

**Comment by barreiro** [comment]
Superseded by #872

**Pull request closed without merging**
