### PR TITLE
[ARTEMIS-2863] Add support to pause dispatch when group rebalance

### PR DESCRIPTION
**Pull request by michaelandrepearce**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
can you rebase? you have a merge branch commit in there.

**Comment by clebertsuconic** [comment]
you actually rebased with a merge commit. you should fix your merge in there.. and have it flat please?

**Comment by michaelandrepearce** [comment]
> can you rebase? you have a merge branch commit in there.

@clebertsuconic i will, its still a wip thus the Do-not-merge label, i need to add test cases still and tidyup (e.g. remove unused imports accidentally added)

**Comment by michaelandrepearce** [comment]
@clebertsuconic ok, cleaned up, test added for the change, and docs updated, rebased and squashed

**Comment by clebertsuconic** [comment]
RedeployTest is failing on this PR.

I think there are other failures associated with this (I need to double check as I run a few PRs together before merging).

**Comment by clebertsuconic** [comment]
also, there's GroupingTest::testGroupRebalanceUsingAddressQueueParameters

**Comment by clebertsuconic** [comment]
full list of failing tests:


Test Name | Duration | Age
-- | -- | --
org.apache.activemq.artemis.tests.integration.jms.RedeployTest.testRedeployRemoveFilter | 2.3 sec | 1
org.apache.activemq.artemis.tests.integration.jms.RedeployTest.testRedeployFilter | 2.3 sec | 1
org.apache.activemq.artemis.tests.integration.jms.RedeployTest.testRedeployQueueDefaults | 37 ms | 1
org.apache.activemq.artemis.tests.integration.jms.client.AutoGroupingTest.testGroupRebalanceUsingAddressQueueParameters | 29 ms | 1
org.apache.activemq.artemis.tests.integration.jms.client.GroupIDTest.testGroupRebalanceUsingAddressQueueParameters | 26 ms | 1
org.apache.activemq.artemis.tests.integration.jms.client.GroupingTest.testGroupRebalanceUsingAddressQueueParameters | 34 ms | 1
org.apache.activemq.artemis.tests.integration.jms.client.GroupingTest.testGroupRebalance | 10 sec | 1
org.apache.activemq.artemis.tests.integration.management.ActiveMQServerControlTest.testCreateAndDestroyQueue_5[legacyCreateQueue=true] | 45 ms | 1
org.apache.activemq.artemis.tests.integration.persistence.ConfigChangeTest.testChangeQueueFilterOnRestart

**Comment by clebertsuconic** [comment]
@michaelandrepearce will you be able to look into this one?

**Comment by michaelandrepearce** [comment]
Yes. Just waiting go get free time. Worst case will look at weekend

**Comment by michaelandrepearce** [comment]
Two small typos .. all fixed.

image
image

**Comment by michaelandrepearce** [comment]
@clebertsuconic is thus gd to merge?

**Comment by clebertsuconic** [comment]
@michaelandrepearce It seems so.... test suite was good... however I want to double check one thing before I merge.

I saw some messages on the compatibility tests that could mean the tests silently fail (perhaps by a previous change.. I dunno). if I could check this tomorrow before I merge?

**Pull request closed without merging**
