### PR TITLE
ARTEMIS-1542 - AMQP message cluster-bridging fixi

### PR DESCRIPTION
**Pull request by toddbaert**
Fixing and issue where AMQP messages would lose their address when being sent accross a cluster-bridge.

### CODE REVIEW

**Comment by toddbaert** [comment]
@clebertsuconic  @michaelandrepearce 

in ClusterConnectionBridge.beforeForward(Message message, SimpleString forwardingAddress), we call super.beforeForward(message, null). The is why we lose the address. This code path is executed when broker1 forwards an AMQP message to broker2. This is why we will only see this in a cluster, when a producer sends a message to broker1 and a consumer is listening on broker2.

**Comment by clebertsuconic** [comment]
The address wasn’t set at the producer.  

The address would be reset at the target.

**Comment by toddbaert** [comment]
I am still seeing the issue. With the changes in this PR, the issue is resolved. Can you please look at the diff?

-      messageCopy = super.beforeForward(messageCopy, null);
+      messageCopy = super.beforeForward(messageCopy, forwardingAddress);

Why would we want to call super.beforeForward() with a null second arg? This is the source of the problem.

**Comment by clebertsuconic** [comment]
@toddbaert just for future reference, as I told you on #1701 I made a mistake a reverted your fix by accident. this PR is fixing my accidental revert...

it should be done now.. thanks for contributing!!! Opensource rocks!

**Comment by toddbaert** [comment]
@clambertus  :guitar: Opensource :guitar:  Thanks so much for your help! I've tested and all seems well now.

**Comment by clebertsuconic** [comment]
@toddbaert clambertus? :)

**Pull request closed without merging**
