### PR TITLE
ARTEMIS-2644 Include client id into non durable subscriber queue name

### PR DESCRIPTION
**Pull request by brusdev**

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
Guys this is a breaking change as no longer with use core naming enabled the naming patterns match with amqp. 

Also this merged very quickly for a non critical fix can we please ask for giving others time to review in future.

Can either this revert this or ensure amqp is alinged when amqp core naming is toggled

**Comment by jbertram** [comment]
@michaelandrepearce, feel free to revert.

**Comment by michaelandrepearce** [comment]
Will revert in the morning then.

**Comment by brusdev** [comment]
@michaelandrepearce @jbertram I'm going to create a new PR to avoid breaking change.

**Comment by michaelpearce-gain** [comment]
@brusdev will you have the PR today? If so ill hold off the revert, else will revert still, just so it doesnt leave master with the issue.

**Comment by brusdev** [comment]
@michaelandrepearce I'm working on it.

**Comment by michaelpearce-gain** [comment]
@brusdev looking at the jira, this implementation requires the client to set client id, which isnt always advisable. To meet the needs of the jira, 
other identifying information also be present, e.g. the user + hostname

**Comment by brusdev** [comment]
@michaelandrepearce I created the PR #3006 to fix the breaking change, ATM I'm using only the clientId if present. Can you review the PR, please?

**Comment by michaelpearce-gain** [comment]
i think we need to address both the issues, to not revert this,

**Pull request merged**
