### PR TITLE
ARTEMIS-888 - AMQP headers arent always set

### PR DESCRIPTION
**Pull request by andytaylor**
https://issues.apache.org/jira/browse/ARTEMIS-888

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@tabish121 can you take a look?

**Comment by tabish121** [comment]
This change seems to better address the underlying issue that was to be fixed, it does ignore the other fields in the Header which could be an issue if anyone were to apply the same types of checks for those being exactly preserved as opposed to their defaults being assumed.

**Comment by clebertsuconic** [comment]
@andytaylor there's a conflict now anyways after a merge I did for @jbertram .. can you fix it?

**Comment by andytaylor** [comment]
fixed

**Pull request merged**
