### PR TITLE
Update maven-checkstyle-plugin to 2.17, fix violations

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by mtaylor** [comment]
@scop You have 1 checkstyle violation.  Could you please update.  Thanks.

[ERROR] src/test/java/org/apache/activemq/artemis/tests/extras/byteman/HierarchicalObjectRepositoryTest.java:[76,7] (modifier) RedundantModifier: Redundant 'public' modifier.

**Comment by scop** [comment]
Done, plus a few similar ones in examples.

**Comment by clebertsuconic** [comment]
I would squash these commits and push -f on your branch
no need to have the checkstyles showing as committs after merge.


I could do it during merge though if you can't do it.

**Comment by clebertsuconic** [comment]
(I have done a comment earlier here that I removed.. please ignore me.. I got confused about what this was about)

**Pull request merged**
