### PR TITLE
ARTEMIS-1096 Changing Global Max Size's default

### PR DESCRIPTION
**Pull request by clebertsuconic**

### CODE REVIEW

**Comment by jbertram** [comment]
It might be good to explicitly log what is being used for the global-max-size (e.g. an INFO level) when using the default so users understand it's using Xmx/2.

**Comment by clebertsuconic** [comment]
that will flood the testsuite though :)

**Comment by jbertram** [comment]
I see your point, but we're already flooding it with silly (IMO) warns about not having dead-letter and expiry queues.

**Comment by clebertsuconic** [comment]
I need a mental break with a light task.. I will deal with the DLQ message as well.

perhaps we could have a static testMode propery somewhere that we disable only through the Run command?

**Comment by clebertsuconic** [comment]
or the opposite.. set it on our testsuite.

**Pull request closed without merging**
