### PR TITLE
ARTEMIS-2096 Adding a test 

### PR DESCRIPTION
**Pull request by gaohoward**
This test can verify an issue fixed by the commit:
7a463f038ae324f2c5c908321b2ebf03b5a8e303 (ARTEMIS-2096)
The issue was reported in:
https://issues.jboss.org/browse/ENTMQBR-2034
but not reported in Artemis.

### CODE REVIEW

**Comment by tabish121** [comment]
This isn't really a NO-JIRA commit if you are adding a test against a specific JIRA is it?  No reason I can see to put a NO-JIRA on this instead of just tagging against the JIRA that it is related to.

**Comment by gaohoward** [comment]
agreed I'll remove the NO-JIRA. thx.

**Comment by gaohoward** [comment]
ok will do.

**Comment by gaohoward** [comment]
@clebertsuconic I'll send a PR to 2.6.x but not cherry-pick from this. Because on 2.6.x the fix is by a different commit not the one I mentioned here.

**Comment by clebertsuconic** [comment]
@gaohoward this is actually ARTEMIS-2135, which I fixed in 2.6.x and added a test.
Also verified that @tabish121 ' s refactoring fixed it.. but the actual issue for this test is ARTEMIS-2135.

Which I had already fixed in 48e0fc8f42346d96bc809593a150e05a586787ee at 2.6.x.

**Pull request closed without merging**
