### PR TITLE
[ARTEMIS-3494]: ActiveMQClientProtocolManagerFactory shouldn't have a…

### PR DESCRIPTION
**Pull request by ehsavoie**
… private constructor.

* Removing the 'private' constructor
* Removing the use of a static getInstance

Issue: https://issues.apache.org/jira/browse/ARTEMIS-3494

### CODE REVIEW

**Comment by jbertram** [comment]
@ehsavoie, can you clarify why this change is necessary/beneficial?

**Comment by ehsavoie** [comment]
I was recreating an ActiveMQConnectionFactory from a 'previous' one but when setting the ProtocolManagerFactory it fails because the code underlying is using an empty constructor

**Review by brusdev — APPROVED** [review]
@ehsavoie thanks it LGTM +1

**Comment by gemmellr** [comment]
Seems unusual to explicitly render the static method unused in the Artemis codebase and then not modify it in some way (e.g deprecation, or removal). As is anyone could just choose to remove it as 'unused', though it sounds like you may have existing code that was relying on it. Its also now unused and untested for anyone else still relying on it.

**Pull request merged**
