### PR TITLE
Changing host to 0.0.0.0

### PR DESCRIPTION
**Pull request by clebertsuconic**
We are changing the default host to 0.0.0.0 per feedback from the community (activemq dev-list)

### CODE REVIEW

**Comment by mtaylor** [comment]
I really like what you have done here @clebertsuconic.  

Just a couple of minor things.

1. Could you please change the text to identify what type of user will be created, default, admin, initial etc...?  i.e. 

# Please enter [default,admin,initial] username ->
martyn

2. Can the password be hidden i.e.:

# Password ->
***********

3. Could you also add some instructions to the README that just explain what these options mean.

Thanks.

I've tested this on linux and windows and works fine.

Cheers
Martyn

**Comment by clebertsuconic** [comment]
This is not supposed to have a license header... it's just what's the inside option that will be placed

**Comment by jbertram** [comment]
I also think the password should be masked if possible and the docs should be updated.  

Also, it might be good for there to be some kind of simple explanation at the beginning of the set-up process.  Something like, "Please answer the following questions to complete the initial security configuration for the broker."

**Comment by mtaylor** [comment]
@clebertsuconic I checked the license guide here: http://www.apache.org/legal/src-headers.html

Given the nature of the file in question, a case could be made for it to come under this section:

WHAT FILES IN AN APACHE RELEASE DO NOT REQUIRE A LICENSE HEADER?
A file without any degree of creativity in either its literal elements or its structure is not protected by copyright law; therefore, such a file does not require a license header. If in doubt about the extent of the file's creativity, add the license header to the file.

For this reason I think you are safe in ignoring the license header on this file.  Particularly due to the difficulty in removing the header during the templating process.

**Comment by mtaylor** [comment]
+1 from me.  I will leave for @jbertram to +1 before merging,  Cheers.

**Comment by jbertram** [comment]
+1

**Pull request merged**
