### PR TITLE
ARTEMIS-2000: For ScaleDown set the RoutingType header property on th…

### PR DESCRIPTION
**Pull request by RoddieKieley**
…e message so if the address does not exist on the other end it will be created correctly.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
tests?

**Comment by clebertsuconic** [comment]
@RoddieKieley  any chance you can add a test?

**Comment by RoddieKieley** [comment]
@clebertsuconic Will do when possible.

**Comment by RoddieKieley** [comment]
@clebertsuconic I cherry picked an added test onto this branch based on master and as well cherry picked the main commit and that commit onto a 2.6.x based branch and opened up a separate [PR #2319](https://github.com/apache/activemq-artemis/pull/2319) to get it into 2.6.x. This seemed like a safe approach as the rebase from master to 2.6.x wasn't completely smooth.

**Comment by clebertsuconic** [comment]
We always use cherry pick -x on 2.6.x   


Let me merge master first.  And I will let you know.

**Pull request closed without merging**
