### PR TITLE
ARTEMIS-388 listen for activation failures

### PR DESCRIPTION
**Pull request by jbertram**

### CODE REVIEW

**Comment by mikehearn** [comment]
Looks good, but javadocs?

**Comment by clebertsuconic** [comment]
@mikehearn  good point actually :) :+1:

**Comment by jbertram** [comment]
@clebertsuconic, can you elaborate a bit more on that use-case?  I'm not following.  To what does a NettyAcceptor connect?

**Comment by clebertsuconic** [comment]
@jbertram  from the original JIRA, one of the issues was a netty acceptor not being activated because another process somewhere was already accessing it. I thought this was about also call a listener when the acceptor failed to init for instance.

I wasn't sure by just reading the diffs if that feature was implemented.

**Comment by jbertram** [comment]
@clebertsuconic, yes.  That's precisely the use-case I was targeting.  Note the test-case I added tests this explicitly.

**Comment by clebertsuconic** [comment]
Looks good, I will merge it.

@mikehearn if you can try it out... if you see anything please let us know.

**Pull request closed without merging**
