### PR TITLE
ARTEMIS-756 Introduced an example for CDI integration, added a README…

### PR DESCRIPTION
**Pull request by johnament**
… to explain how it works.

### CODE REVIEW

**Comment by johnament** [comment]
So there's a couple of things I don't like right now - need some input from you guys.

- The artemis maven plugin seems to need to redeclare dependencies.  Is there a way to do this in a profile?
- Do I need a `broker.xml` or can that be inherited somehow?

**Comment by johnament** [comment]
Ok, never mind on the plugin issue.  Thought about it a little more and moved the profiles a bit.  One odd thing, I get this in OWB but not Weld...

```
INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.461 s
[INFO] Finished at: 2016-10-21T21:28:32-04:00
[INFO] Final Memory: 51M/797M
[INFO] ------------------------------------------------------------------------
Oct 21, 2016 9:28:32 PM org.apache.activemq.artemis.jms.client.ActiveMQConnection finalize
WARN: AMQ122000: I''m closing a JMS connection you left open. Please make sure you close all JMS connections explicitly before letting them go out of scope! see stacktrace to find out where it was created
java.lang.Exception
	at org.apache.activemq.artemis.jms.client.ActiveMQConnection.<init>(ActiveMQConnection.java:167)
	at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createConnectionInternal(ActiveMQConnectionFactory.java:762)
	at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createContext(ActiveMQConnectionFactory.java:274)
	at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createContext(ActiveMQConnectionFactory.java:267)
	at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createContext(ActiveMQConnectionFactory.java:257)
	at org.apache.artemis.client.cdi.factory.ConnectionFactoryProvider.createJMSContext(ConnectionFactoryProvider.java:82)
```

**Comment by clebertsuconic** [comment]
That is the finalize closing the connection that was left open.

Is that a issue? do you have anything to be called when the osgi is going down and close the connection?

**Comment by clebertsuconic** [comment]
the maven plugin is supposed to be used elsewhere. it was the best way I could figure out at the time. We can change it if we find a better way.

**Comment by johnament** [comment]
No, the finalize method issue isn't something to be worried about I don't think, except that I also tried explicitly closing the connection and it didn't work.  So I'm not sure what connection is remaining open.  JMSContext's?

**Comment by johnament** [comment]
Also... you keep saying OSGi.  This is CDI.

**Comment by johnament** [comment]
I just re-kicked Jenkins.

**Comment by clebertsuconic** [comment]
@johnament I feel pretty dumb now :/ on the confusion... 

I will take a look on the Closing exception.

**Comment by clebertsuconic** [comment]
@johnament  I am thinking the CDI would be cool to be part of root, instead of integration.

Same as the example, it would be moved under ./standard.

**Comment by johnament** [comment]
I'm fine with moving the packages up since its just a client lib, not a true integration (as Clebert's described)

**Comment by clebertsuconic** [comment]
@johnament the example is using the same create plugin from maven. it will eventually replace broker.xml for the examples that need special configuration.


Looking at the example you wrote it doesn't need it. So I will remove it as I merge it.

**Pull request closed without merging**
