### PR TITLE
https://issues.apache.org/jira/browse/ARTEMIS-964

### PR DESCRIPTION
**Pull request by cshannon**
Moving XML conversion logic to a common XmlDataExporterUtil class so it
can be used elsewhere.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@cshannon it looks good...

just one minor thing.. I have been trying to keep the commit message understandable at the first line...


something like:

```
ARTEMIS-964 Moving XML Conversion to blablabla

https://issues.apache.org/jira/browse/ARTEMIS-964
more blablablablablal...
```


We have that on the hacking guide...



you are a committer, you could of course bypass the "rule" if you have a strong feeling for this format.. .but it's just that this is helpful when doing bisects and git logs... I have had to bisect before and reading stuff on the first line would be helpful.

**Comment by jbertram** [comment]
@clebertsuconic, I had a similar thought as you.

**Comment by cshannon** [comment]
I changed the commit message.

**Comment by jbertram** [comment]
Nice one!

**Comment by clebertsuconic** [comment]
@cshannon  👍

**Pull request merged**
