### PR TITLE
ARTEMIS-1357 TypedProperties encode/decode improvement

### PR DESCRIPTION
**Pull request by franz1981**
Several improvements are made on the encode/decode paths:

- fixed load factor on properties to avoid resizing/rehashing and reduce GC pressure
- cached BooleanValue/NullValue instances to reduce GC pressure
- used internal iteration throught lamda while encoding properties to reduce GC pressure and allows loop unrolling

### CODE REVIEW

**Comment by franz1981** [comment]
@tabish121 @clebertsuconic I need to run the full test suite, but it seems a change with no colleteral effects.
I've a couple of graphs showing the impact of the change:

MASTER:

image

AFTER THE CHANGE:

image

While now no resize() method is called at all, and the relative weight of most calls in the decode path are simply disappeared.

**Comment by tabish121** [comment]
Nice!  Looks like a reasonable change to me.

**Comment by clebertsuconic** [comment]
Nice one

**Comment by franz1981** [comment]
@clebertsuconic Please do not merge it, I've an additional thing to add on it

**Comment by clebertsuconic** [comment]
You know you will make core even faster with this right ?

**Comment by franz1981** [comment]
@clebertsuconic Yep, but I'm sure that similar optimizations (if not already present) could be added on the other protocols too...or there is not worth to improve it further?
I'm found these while testing other PRs I've done...

**Pull request closed without merging**
