### PR TITLE
[ARTEMIS-1171] Improve log readability around clustering

### PR DESCRIPTION
**Pull request by iweiss**
Issue: https://issues.apache.org/jira/browse/ARTEMIS-1171

### CODE REVIEW

**Comment by jbertram** [comment]
I'm a bit concerned about breaking up log statements across multiple lines as it reduces the effectiveness of tools like grep to search for particular bits of logging along with their context.  My recommendation would be to weed out the details in the logging statement that really aren't necessary.

**Comment by iweiss** [comment]
Although I agree, knowing what is necessary or not make this quite challenging since what is needed for one is not needed for someone else.

My main concern was the cascade of toString() calls that can pile up quite quickly as seen here.

**Comment by clebertsuconic** [comment]
@iweiss this has been reverted as this broke management.

it would need some work if you want it back.

**Comment by iweiss** [comment]
@clebertsuconic Understood. I will rework it in the coming days. Sorry for the trouble.

**Pull request closed without merging**
