### PR TITLE
Sorting issue with BeanUtils picking up set/get props in JNDI - WIP-DO NOT MERGE

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Apply fix so that when using JNDI via tomcat resource it works. 
Replace original extract of JNDIStorable taken from Qpid, and use ActiveMQ5's as fits better to address this issue. (which primary use case is users migrating from 5.x)
Refactored ActiveMQConnectionFactory to externalise and turn into reference by StringRefAddr's instead of custom RefAddr which isnt standard.
Refactored ActiveMQDestinations similar
Refactored ActiveMQDestination to remove redundent and duplicated name field and ensured getters still behave the same

### CODE REVIEW

**Comment by clebertsuconic** [comment]
Why close it ?

**Comment by michaelandrepearce** [comment]
Still needs work, eg need to add tests so it doesn’t get regressed in future etc, add some documentation like there is in 5.x. Also I’d like @spaction to check it fixes it for him incase it doesn’t and I need to do some further refractors

**Comment by michaelandrepearce** [comment]
*refactors

**Comment by michaelandrepearce** [comment]
Should I leave it open whilst I do that then? @clebertsuconic? Also do you think I should seperate documentation from the fix/improvement then?

**Comment by clebertsuconic** [comment]
@michaelandrepearce I thought you had given up.. :) 

also, the thing is.. if you close it... later you will need to open a new PR...
github doesn't do well when the head changed against your closed PR.. I haven't seen it working at least. (maybe the behaviour has changed).

If you want to close it now.. and open a new one later .. it's up to you.

**Comment by michaelandrepearce** [comment]
Haha no def not given up, :)

I'll open a new PR once it's been checked by the user that it works, ill work on docs and extra tests in mean time. I'll have to create a jira and amend commit text anyhow.

**Pull request closed without merging**
