### PR TITLE
ARTEMIS-1807 File-based Large Message encoding should use read-only mmap

### PR DESCRIPTION
**Pull request by franz1981**
It provides a LargeBodyEncoder using a read only mapped view of the large
message file to encode the data to be sent. It saves unecessary copies and
context switches while consuming the encoded data.

### CODE REVIEW

**Comment by franz1981** [comment]
@clebertsuconic Do not merge it yet, I have an exception on the test `BridgeTest.testBridgeWithVeryLargeMessage`

**Comment by franz1981** [comment]
@clebertsuconic I'm thinking to re-implement it by dividing the mmap in several mapped chunks instead of just 1 big one to help the OS to be able to map it when it is > Integer.MAX_VALUE

**Comment by franz1981** [comment]
`JournalStorageManager::addBytesToLargeMessage` is another point that need to be improved to avoid OOM and better performances too

**Comment by gaohoward** [comment]
I think using mapped file will get better performance over the NIO channel read. 
It would be better to have a unit test with it. @clebertsuconic wdyt?

**Comment by clebertsuconic** [comment]
@franz1981 I think so too.. but I would do it in the context of a refactoring in AMQP also. we need to properly implement large messages in AMQP.

**Comment by franz1981** [comment]
@gaohoward 

> I think using mapped file will get better performance over the NIO channel read.

@orpiske have some nice idea to test it for sure :P

> It would be better to have a unit test with it. @clebertsuconic wdyt?

@clebertsuconic @gaohoward 
If you 2 will vote for the chunked version I will squash the 2 commits and provide a unit test to cover this new implementation: ATM it is just using the tests related to large messages.

@clebertsuconic 
> I think so too.. but I would do it in the context of a refactoring in AMQP also

That means that the same large body encoder should be reused for it as well?

**Comment by michaelandrepearce** [comment]
@franz1981 can you provide a perf test before and after for normal usage of the mapped journal e.g. as the main journal. 

I ask as we have ended up using it for a specific use case internally, where we are using it for latency reasons, so i want to be sure theres no degrade for the current usage.

**Comment by franz1981** [comment]
@michaelandrepearce Good points: paging (the consuming side) , this PR and a mapped journal should contend the OS page cache , so it depends on the dirty/dirty background ratio and total system memory.
Probably should makes sense to allow this feature to be configurable (and paging as well) in order to avoid contention between them or just tune the OS according (tricky IMO). Wdyt?

**Comment by franz1981** [comment]
@michaelandrepearce
> we are using it for latency reasons
Nice!! Happy to hear that :):)  no datasync, no party! :)

**Comment by franz1981** [comment]
@michaelandrepearce I'm thinking with @orpiske which kind of test should make sense in order to emulate the correct use case to be stressed...
Please, can you share your throughts on that? 
I'm concerned about how much is OS configuration sensitive running those tests as well

**Comment by mtaylor** [comment]
@michaelandrepearce If you are using non large messages, and without paging, this should have 0 impact.  @franz1981 can you confirm.

**Comment by franz1981** [comment]
@mtaylor @michaelandrepearce  Yep and it isn't changing the way the mapped journal works: it uses a different code path from the journal, without changing the MappedSequentialFile in any of its parts.

I agree that I could provide relative measurements to show which impact it has vs the original version: with @orpiske probably we could start providing some relative numbers before merging anything. @orpiske wdyt?

**Comment by michaelandrepearce** [comment]
@mtaylor , ive had an offline discussion with @franz1981 he kindly went through in detail this change with me, know i better understand +1 from me.

**Comment by orpiske** [comment]
@franz1981 we can definitely work out some numbers for this!

**Comment by franz1981** [comment]
@michaelandrepearce @mtaylor @clebertsuconic @gaohoward Guys I was looking to the improvements made by this PR and....I found that there is a log of Journal activity with it! I mean....ASYNCIO ones...it makes sense? 
That activity seems the bottleneck on consumer side....

**Comment by franz1981** [comment]
I?m clising this in the meantime proper tests will be performed :)

**Pull request closed without merging**
