### PR TITLE
ARTEMIS-1342: Support Netty Native KQueue on macOS

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Add support for KQueue for when server or client runs on macOS. This is inline with the epoll support for linux

This currently is branched off https://github.com/apache/activemq-artemis/pull/1452, as such that PR needs to go first, then i will rebase.

As such don't merge this until that.

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
@clebertsuconic can someone look at H21 build agent it seems it has a disk permission issue. TimeUnitsTest is failing and all it is doing is making a file myfile.txt in a new temporary folder. This code is not changed.

**Comment by clebertsuconic** [comment]
@michaelandrepearce we would need to talk to infra.

**Comment by clebertsuconic** [comment]
don't worry about conflicts.. I used the merge-PR script and it rebased fine.

**Comment by michaelandrepearce** [comment]
@clebertsuconic I'm guessing thats something you or a committer or PMC can only do?

**Pull request closed without merging**
