### PR TITLE
ARTEMIS-1312 TimedBuffer doubled timeout with blocking flush

### PR DESCRIPTION
**Pull request by franz1981**
It fixes one of the TimedBuffer timing test using the correct math to perform the sleep on TimedBuffer

### CODE REVIEW

**Comment by franz1981** [comment]
@clebertsuconic  It is not waiting the first time: it is honoring the callback contract.
If is a blocking device or not the callbacks must be called after a flush and a flush can't take less than timeout value.

**Comment by clebertsuconic** [comment]
'It is not waiting the first time:'

This is not an issue, but it broke the test... 


'a flush can't take less than timeout value.'

What that means? it takes zero time in AIO.

**Comment by franz1981** [comment]
@clebertsuconic AFAIK in ASYNCIO the callback::done is called just after that the "real" flush operation is performed ([org_apache_activemq_artemis_jlibaio_LibaioContext::JNICALL Java_org_apache_activemq_artemis_jlibaio_LibaioContext_blockedPoll](https://github.com/franz1981/activemq-artemis/blob/5e5ac0f0575a89ea81bcedfce63e73949c14c11c/artemis-native/src/main/c/org_apache_activemq_artemis_jlibaio_LibaioContext.c#L630-L630) ) hence it can't take 0 time. Instead, the ``TimedBufferObserver::flushBuffer`` call can take ~0 time (with ASYNCIO)  but the callbacks won't be triggered until the real flush will' be performed, makes sense?

**Comment by franz1981** [comment]
@clebertsuconic To show it I've performed a test measuring with ASYNCIO (timeout 2000000 nanoseconds === 500 IOPS) how much time is needed for each callbacke to be triggered (ie called a done) and this is the result:

[
asyncio_callbacks_done
](url)
It shows that each callback::done tooks at least 2000000 nanoseconds before being called.

**Comment by clebertsuconic** [comment]
@franz1981 you are diverging here ;)

It's just the test that's wrong... but you can't add a sleep on flush. that's wrong and cheating the test.
If there's anything wrong it would hide the issue.

**Comment by franz1981** [comment]
@clebertsuconic I'm not diverging, I'm showing that the old version of the test was doing something that is not valid (aka calling the callbacks without waiting the proper flush time), that's why now that the timeout is honored, it was failing..

**Pull request closed without merging**
