### PR TITLE
added unit test for setting the user and password in the uri for tcp …

### PR DESCRIPTION
**Pull request by pgfox**
…transport, used in JNDI. 

Could not find an example in the existing unit tests.

### CODE REVIEW

**Comment by jbertram** [comment]
Thanks for the test!

For the sake of thoroughness it would be best if security was enabled on the test broker and the test ensured the credentials set in the URL actually resulted in an authenticated session.  If you don't think you can add that I'll go ahead and merge what you have and try to get to it later.

**Comment by pgfox** [comment]
@jbertram sure, I will give that a go

**Comment by pgfox** [comment]
@jbertram, 

as you suggested, enabled security on the test broker and add a role to ensure credentials passed with connection. Also enabled the default user to ensure existing tests passed without modification - I was trying to keep a small footprint. 

Thanks
Pat

**Comment by clebertsuconic** [comment]
@pgfox  you know you can also do new ActiveMQConnectionFactory(uri);, right?


Just asking.. maybe that's something we need to blog about it.. or maybe make it clearer on the docs.

**Pull request closed without merging**
