### PR TITLE
fixing Stomp::testSendWithHeartBeats

### PR DESCRIPTION
**Pull request by clebertsuconic**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
The test got broken at ebcf0c0080

@scop  Can you check my fix please testSendWithHeartBeats was hanging as it was receiving (<STOMP>NULL<STOMP>) instead of a just null package. (or something like that).. run the test without this fix and you would see.

**Comment by scop** [comment]
Actually I have another PR coming up which I believe would address this issue in a better way.

I suppose I haven't had enough coverage on my local test suite runs, I've done <code>mvn -Pdev test</code> at top level. I now did the same with <code>-Pfast-tests</code> but don't see the failure with that either. If I want to run the full set of say STOMP tests, what command in which dir would you recommend? What did you run in order to see the failure?

**Comment by clebertsuconic** [comment]
I've tested stomp/* using my IDE. Perhaps we should create a profile for the stomp testsuite? or refactor the tests under protocols/stomp? (that last part is a bit tricky due to the super classes).

**Comment by clebertsuconic** [comment]
@scop  so what you want to do, should I close this and wait your PR? or should I fix my PR (that failed here) and merge this?

**Comment by scop** [comment]
If you want the failure gone ASAP, go ahead and push your fix to it, I'll adapt mine later.

One the other hand I can get my PR submitted tonight provided I can get the test suite to run some sane way. I'm an Eclipse user and I guess I found the place where to run the desired test suites, problem is that when I do right-click "Run as" -> "JUnit test" for the stomp package in integration-tests I get a lot of errors about classes not found, some ExceptionInInitializerErrors due to <code>Caused by: java.lang.IllegalArgumentException: Invalid logger interface org.apache.activemq.artemis.tests.integration.IntegrationTestLogger (implementation not found in sun.misc.Launcher$AppClassLoader@409a44d6)</code> etc, so I suppose my setup needs some changes, unfortunately I'm not sure what...

**Comment by clebertsuconic** [comment]
We need to run a set of tests. 

I haven't used Eclipse in a while.. but I'm sure others did. (I have been using Intelij)

**Comment by clebertsuconic** [comment]
@scop I will send a commit to the master fixing the test, feel free to improve the fix... I need to get some build results.

**Comment by clebertsuconic** [comment]
@scop  build started at https://builds.apache.org/job/ActiveMQ-Artemis-Nightly-Regression-Test/202/

As I said, please feel free to improve the fix.

**Comment by scop** [comment]
After some ugly local hacks I got the tests to run. I see testSendAndReceiveWithHeartBeats hanging (did you mean that instead of testSendWithHeartBeats?), but I cannot seem to find a revision in which it would /not/ hang. It hangs for me also with your fix. I've backed down to commit 6a59443 but it too shows the same problems for me: the <code>while (frame != null)</code> never becomes false, the connection keeps receiving heartbeat frames forever after the ten message frames it correctly receives.

I'm afraid I'm at loss here.

**Comment by clebertsuconic** [comment]
@scop  TBH those were the reasons why I stopped using eclipse. Too hard to make it happen.

With Idea I just open a maven project and it works. 

I'm not saying it's impossible, but it's certainly harder. You should probably ask for help on the dev-list

**Comment by clebertsuconic** [comment]
or switch to idea ;)

**Comment by scop** [comment]
Maybe sometime. But just to confirm: does the fix you committed for this fix the hang for you?

Another thing about your fix: it reverts the duplicate content-length change from PR #86, for no apparent (at least to me) reason. Was that on purpose?

**Pull request closed without merging**
