### PR TITLE
ARTEMIS-904 - Remove cyclic dependencies from artemis-cli

### PR DESCRIPTION
**Pull request by bennetelli**
To ensure a maintainability in future I refactored the cli project and removed all cyclic dependencies between classes and packages by moving classes and packages near to their real responsibility and reduced access modifiers after it. (I can show you a "before and after" picture of the projects architecture from a package point of view if you want.)
I tried to move classes and methods only and reduced visibility of methods. Didn't change other stuff like unused methods and so on.

### CODE REVIEW

**Comment by bennetelli** [comment]
@clebertsuconic argh. Thought another branch would result in a separate pull request. Let me know if you have trouble with it :/

**Comment by johnament** [comment]
Looks like some checkstyle issues in the CLI module, if you could fix those up.

**Comment by johnament** [comment]
Also it looks like you have two PRs with the same changes now.  We should merge one.

**Comment by bennetelli** [comment]
Can't find any checkstyle warnings. Where are you looking for it? 
The Jenkins build failed because of an error in LDAP stuff which I didn't touch with my new markdown documentation.

**Comment by bennetelli** [comment]
sh**. Created the branch from my previous ARTEMIS-903 branch. Would be good if we could close the second one (ARTEMIS-904) and I will open a new PR later.

**Comment by johnament** [comment]
You'll need to close it.  Here's a link to the checkstyle issues https://builds.apache.org/job/ActiveMQ-Artemis-PR-Build/2113/consoleFull

**Pull request closed without merging**
