### PR TITLE
ARTEMIS-2458 Fix AMQP Transaction Rollback & Session Close Ordering 

### PR DESCRIPTION
**Pull request by michaelandrepearce**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@michaelandrepearce it's easier to ask.. did you happen to change to semantics on core (to also use addSorted?) or that's preserved.

I'm not sure yet.. I'm reading in more detail to figure out.. but your answer would help me go faster :)

**Comment by clebertsuconic** [comment]
@franz1981 I actually like the randomicity of the test in there. Just like our users, data is always random :)

**Comment by clebertsuconic** [comment]
WHOA: This is a LinkedList of PRs that is changing a LinkedList... :) Seriously! :)

I have made an optimization to the addSorted on LinkedList, fixed a few check-style mistakes I made, and I sent a new PR (hopefully final now).

This is replaced by #2807

**Comment by franz1981** [comment]
> @franz1981 I actually like the randomicity of the test in there. Just like our users, data is always random :)

Yep it is true, but it won'ìt help if the test start to fail, because we would like to make it fail 100% of the time and reproduce it locally too. Ok to make it random, but maybe it would be nice to report which random sequence has been used on test failure...

**Pull request closed without merging**
