### PR TITLE
Revert "ARTEMIS-2094 - Fix Configuration change loss when network Issue"

### PR DESCRIPTION
**Pull request by jbertram**
This reverts commit cce0e1927c258ce6f3c3c3cb0d90bad5337b7d12.

### CODE REVIEW

**Comment by jbertram** [comment]
The commit for ARTEMIS-2094 needs to be reverted because (as noted on the JIRA 10 days ago) it is breaking lots of tests.  For example, all the tests in `org.apache.activemq.artemis.tests.integration.cluster.failover.SecurityFailoverTest` are currently failing.  @michaelandrepearce, I'm fine if you want to send a PR to fix the problems with the original commit so that this one doesn't have to be merged.

**Comment by michaelandrepearce** [comment]
@jbertram is there an easy place to see all fails? reason i ask as i know we dont have apache build that does the entire suite which can take several hours and i assume you have a list to hand

FYI SecurityFailoverTest is a quick fix because its actually re-setting up the roles manually during failover deep within security hierarchy, but not updating the actual server config. But i want to ensure i fix all before i send a PR.

**Comment by jbertram** [comment]
@michaelandrepearce, unfortunately the build I have access to no longer has the history as too many builds have been run since then.  Push your changes to your GitHub repo and tell me the branch name and I'll run the build again and provide relevant results.  It will take a little time, but should be relatively painless.

**Comment by michaelandrepearce** [comment]
@jbertram if you could check this one https://github.com/apache/activemq-artemis/pull/2354

**Comment by michaelandrepearce** [comment]
@clebertsuconic it doesn't fix the issue of lost security settings and address settings if they were changed, ive got another idea what i could do.... give me some time as its evening here already

**Comment by michaelandrepearce** [comment]
see https://github.com/apache/activemq-artemis/pull/2356

**Comment by clebertsuconic** [comment]
@jbertram can you close this please?

**Pull request closed without merging**
