### PR TITLE
ARTEMIS-1862: fix 'amqpLowCredits' XML config, update code defaults

### PR DESCRIPTION
**Pull request by gemmellr**
More details at https://issues.apache.org/jira/browse/ARTEMIS-1862

### CODE REVIEW

**Comment by gemmellr** [comment]
A separate change for later, but I think it would be nicer to remove the config from the XML by default as few will need/want to change it.

**Comment by clebertsuconic** [comment]
@gemmellr I placed it there as I thought it would be easier for users to change it without needing to look at docs. but if this is rarely needed.. perhaps it should go.

**Comment by gemmellr** [comment]
The CI failure doesnt seem related

**Comment by clebertsuconic** [comment]
@gemmellr  nice catch! thanks a lot!

**Comment by gemmellr** [comment]
@clebertsuconic I think having it configurable makes sense, but I think its mostly in the way being part of the default config.

**Pull request merged**
