### PR TITLE
ARTEMIS-994 Support Netty Native Epoll on Linux

### PR DESCRIPTION
**Pull request by michaelandrepearce**
The following changes are made to support Epoll.

* Refactored SharedNioEventLoopGroup into renamed SharedEventLoopGroup to be generic (as so we can re-use for both Nio and Epoll)
* Add support and toggles for Epoll in NettyAcceptor and NettyConnector (with fall back to NIO if cannot load Epoll)
* Removal from code of PartialPooledByteBufAllocator, caused bad address when doing native, and no longer needed - see jira discussion

New Connector Properties:

useEpoll - toggles to use epoll or not, default true (but we failback to nio gracefully)
epollRemotingThreads = same behaviour as nioRemotingThreads but for Epoll.
useEpollGlobalWorkerPool = same behaviour as useNioGlobalWorkerPool but for Epoll.

New Acceptor Properties:

useEpoll - toggles to use epoll or not, default true (but we failback to nio gracefully)
useEpollGlobalWorkerPool = same behaviour as useNioGlobalWorkerPool but for Epoll.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
I am running the testsuite, and if everything is ok I should merge it tomorrow...

I have 50% of tests running and so far so good.. will know in 2 hours...



BTW: can you run these commands please?


```sh
git pull -rebase upstream master
git push origin -f {your branch name}
```

and then:

```sh
git rebase -i upstream/master
```

And squash these committs into one, with a description that matches it?

I could do this myself, but I would rather have you finding the best commit name once you squash them.

**Comment by clebertsuconic** [comment]
Awesome work! Testsuite is good...

**Comment by michaelandrepearce** [comment]
@clebertsuconic I have just now rebased and squashed, hope this is what you were wanting me to do.

**Comment by clebertsuconic** [comment]
@michaelandrepearce I don't think you really need three parameters for this... just one would do...

- useEpoll...


the other two you introduced could just use the same parameter, being the same semantic.. being just epoll.


That way you would configure to use epoll or not with a single switch. If you need to configure different settings.. than you can just update the values.. it gets easier on users IMHO.


WDYT?

**Comment by michaelandrepearce** [comment]
@clebertsuconic I though about this but annoyingly theyre named nioBlah as such just using that would be not directly indicate you're affecting epoll. Like wise if we were to strip the nio part then they would be generic but would break any compatibility with existing clients as they'd have to change their properties if used. 

This is why I introduce the extra duplicate props. If you think renaming the existing properties to generic in nature I can do this but as noted wouldn't be back compatible.

**Comment by clebertsuconic** [comment]
@michaelandrepearce I will add a new generic parameter, and deprecate the old one.

Will do that on a separate commit. I just wanted to know if you had any reason.

**Comment by michaelandrepearce** [comment]
@clebertsuconic sounds good.

**Comment by michaelandrepearce** [comment]
@clebertsuconic I notice this didn't get merged still. Did I miss understand and you expected me to make the configuration changes? if so no worries, just let me know.

**Comment by clebertsuconic** [comment]
@michaelandrepearce nope.. I just procrastinated for an afternoon :) give me till tomorrow

**Comment by michaelandrepearce** [comment]
@clebertsuconic I was thinking this afternoon has 2.0.0 been cut for tagging? If not then maybe worth trying to get the property change done before that as a 2.0.0 is a major breaking release anyhow would avoid need for deprecating and creating a new generic we just would need a rename which would be cleaner

**Comment by clebertsuconic** [comment]
@michaelandrepearce 2.0.0 (Artemis) is already cut. 3 days ago.. it was just the vote on...

So this will be for 2.0.1.


I was thinking about setting the default as NIO at least for a while, and having a --epoll --no-epoll property through the CLI.

**Comment by clebertsuconic** [comment]
@michaelandrepearce I did some performance tests with https://github.com/ssorj/quiver and the test hung... I will have to take double care before merging this.. it may take some extra time, as I don't want to make the broker unstable now.

I would like to investigate what's happening before merging this.

**Comment by michaelandrepearce** [comment]
@clebertsuconic thanks, ill try look into also see if i spot anything.

I assume this is repeatable.
Was using the amqp client, looking at the quiver dependencies not the core or jms client. 
Also i assume the master currently doesn't suffer this?
Lastly does this occur when set to nio also in the branch? or only when epoll is on?

**Comment by clebertsuconic** [comment]
@michaelandrepearce I couldn't check other options.. I was using AMQP.. 

so, I was using this command line on quiver to replicate it:

```
quiver q0 --sender qpid-messaging-cpp --receiver qpid-messaging-cpp --messages 1m --body-size 100 --credit 1000 --timeout 10
```


you may need to use a few snapshots on quiver. but most stuff is available on fedora. Look at the list of dependencies if you like to try it.

**Comment by michaelandrepearce** [comment]
Hi @clebertsuconic i managed to get it running.

Some notes:
I was not able to run your command as is, using the version that comes via dnf / repo, seems some options are supported or something :S

I got the below output.

$ quiver q0 --sender qpid-messaging-cpp --receiver qpid-messaging-cpp --messages 1m --body-size 100 --credit 1000 --timeout 10
usage: quiver [-h] [-m COUNT] [--impl NAME] [--body-size COUNT]
              [--credit COUNT] [--timeout SECONDS] [--output DIRECTORY]
              [--init-only] [--quiet] [--verbose]
              ADDRESS
quiver: error: unrecognized arguments: --sender qpid-messaging-cpp --receiver qpid-messaging-cpp

I did however successfully run using just:

$ quiver q0 --messages 1m --body-size 100 --credit 1000 --timeout 10

I am using fedora 25.

It ran fine with both server acceptor set to epoll and nio for me. 

Attached is the output i got for both runs.

[quiver.epoll.txt](https://github.com/apache/activemq-artemis/files/852315/quiver.epoll.txt)
[quiver.nio.txt](https://github.com/apache/activemq-artemis/files/852316/quiver.nio.txt)

**Comment by michaelandrepearce** [comment]
the only comment is with epoll, i notice the producer was producing faster than the consumer during the test as such some queue depth occured, with nio producer and consumer speeds were closer as such less queue depth occured. 

epoll producer rate > nio producer rate by approx 200 messages a second where as consumer rates differed only by approx 50.

**Comment by franz1981** [comment]
@michaelandrepearce thanks for the results!

**Comment by clebertsuconic** [comment]
@michaelandrepearce you have to follow all the dependencies on quiver. probably the cpp didn't finish compilation on make?


There's something going on.. I will review it this week. if you run the cpp module, which generates a bit more load on AMQP and you will have a few weird errors. it just needs some testing.

**Comment by michaelandrepearce** [comment]
@clebertsuconic i have re-run with march larger run size, and now able to reproduce. 

So it seems there is a direct memory leak, this occurs with both epoll and nio set, as suchi assume this is around removal of PartialPooledByteBufAllocator for the default netty allocator rather than epoll itself. I will dig into this area first.

**Comment by michaelandrepearce** [comment]
i turned on the netty leak detector:

22:55:59,492 SEVERE [io.netty.util.ResourceLeakDetector] LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 4
#4:
	io.netty.buffer.AdvancedLeakAwareByteBuf.readBytes(AdvancedLeakAwareByteBuf.java:504)
	io.netty.buffer.WrappedByteBuf.readBytes(WrappedByteBuf.java:661)
	org.apache.activemq.artemis.protocol.amqp.proton.handler.ProtonHandler.inputBuffer(ProtonHandler.java:182)
	org.apache.activemq.artemis.protocol.amqp.proton.AMQPConnectionContext.inputBuffer(AMQPConnectionContext.java:110)
	org.apache.activemq.artemis.protocol.amqp.broker.ActiveMQProtonRemotingConnection.bufferReceived(ActiveMQProtonRemotingConnection.java:134)
	org.apache.activemq.artemis.core.remoting.server.impl.RemotingServiceImpl$DelegatingBufferHandler.bufferReceived(RemotingServiceImpl.java:629)
	org.apache.activemq.artemis.core.remoting.impl.netty.ActiveMQChannelHandler.channelRead(ActiveMQChannelHandler.java:68)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:219)
	io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:631)
	io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:468)
	io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:428)
	org.apache.activemq.artemis.core.protocol.ProtocolHandler$ProtocolDecoder.decode(ProtocolHandler.java:185)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	org.apache.activemq.artemis.core.protocol.ProtocolHandler$ProtocolDecoder.channelRead(ProtocolHandler.java:128)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	java.lang.Thread.run(Thread.java:745)

**Comment by michaelandrepearce** [comment]
Also:

#1:
	io.netty.buffer.AdvancedLeakAwareByteBuf.writeBytes(AdvancedLeakAwareByteBuf.java:600)
	io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:829)
	io.netty.buffer.WrappedByteBuf.readBytes(WrappedByteBuf.java:616)
	io.netty.buffer.AdvancedLeakAwareByteBuf.readBytes(AdvancedLeakAwareByteBuf.java:469)
	io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:217)
	io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:631)
	io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:468)
	io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:428)
	org.apache.activemq.artemis.core.protocol.ProtocolHandler$ProtocolDecoder.decode(ProtocolHandler.java:185)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	org.apache.activemq.artemis.core.protocol.ProtocolHandler$ProtocolDecoder.channelRead(ProtocolHandler.java:128)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	java.lang.Thread.run(Thread.java:745)

**Comment by clebertsuconic** [comment]
@michaelandrepearce that's what I was going after.. some sort of leak while dealing with AMQP.

I will review it this week.

**Comment by clebertsuconic** [comment]
I think I got to the bottom of this... there was a leak.. and some proton miss use.

**Comment by clebertsuconic** [comment]
@michaelandrepearce did you ammend anything on your PR? I can't build it any longer (especially outside of Linux.. like on a mac).

**Comment by michaelandrepearce** [comment]
No haven't touched it

**Comment by michaelandrepearce** [comment]
@clebertsuconic i just did a complete fresh clone and rebuild of this PR/My branch which i rebased the other day. It still built ok for me. Should i rebase again? Maybe some commit in the last few days might have broken something?

**Comment by clebertsuconic** [comment]
Please review master ?

**Comment by michaelandrepearce** [comment]
Many thanks Clebert. 

Had a brief look over tonight. Seems good. Will spend a bit more time tomorrow and also take the chance to update my fork.

**Pull request closed without merging**
