### PR TITLE
ARTEMIS-672 Use sh not bash in scripts

### PR DESCRIPTION
**Pull request by mtaylor**

### CODE REVIEW

**Comment by mtaylor** [comment]
@jdanekrh has offered to do some testing on the various flavours of linux.  Please don't merge until @jdanekrh has ack'd here.

**Comment by clebertsuconic** [comment]
@mtaylor  This looks nice to me. Can we merge it already? I have been testing it... it\s always working

**Comment by mtaylor** [comment]
@clebertsuconic yes go ahead and merge, I had a chat with @jdanekrh and it looks like it's working on various platforms.

**Comment by jdanekrh** [comment]
@clebertsuconic Were you able to run examples as well?

**Comment by clebertsuconic** [comment]
I was

**Comment by jdanekrh** [comment]
@clebertsuconic I cannot make them run on HP-UX. I am seeing

    [ERROR] Failed to execute goal org.apache.activemq:artemis-maven-plugin:1.4.0-SNAPSHOT:cli (start0) on project bridge: Cannot run program "./artemis" (in directory "/qa/home/jdanek/activemq-artemis/examples/features/standard/jms-bridge/target/server0/bin"): ./artemis: not found -> [Help 1]

I do not know why. The file /qa/home/jdanek/activemq-artemis/examples/features/standard/jms-bridge/target/server0/bin/artemis exists, is executable, has env sh in the beginning.

**Comment by clebertsuconic** [comment]
@jdanekrh  the example script is running zip | dezip... maybe something around that?

**Pull request closed without merging**
