### PR TITLE
ARTEMIS-3147 Fix auto created addresses reload

### PR DESCRIPTION
**Pull request by brusdev**

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
Lgtm +1

**Comment by clebertsuconic** [comment]
It does look good to me..

However I saw a couple of failing tests on a recent run on this PR.

I'm going to re-run this to make sure no tests are affected by this.


they will probably be a test issue as I don't see how this could break anything.. but still I would like to check it before merging it.

**Comment by brusdev** [comment]
@clebertsuconic I have executed the tests again but I can't find any failure

**Comment by clebertsuconic** [comment]
merging it

**Pull request closed without merging**
