### PR TITLE
ARTEMIS-1302 make quorum voting more transparent

### PR DESCRIPTION
**Pull request by jbertram**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
Is this just logging ?

**Comment by clebertsuconic** [comment]
I was asking just to confirm. As I don't see anything but logging.  There is one booolean change but I don't think it changed any semantic right ?

**Comment by jbertram** [comment]
Yes, this is just logging.  There are no semantic changes.

**Comment by andytaylor** [comment]
I'll merge this failure was env

**Pull request merged**
