### PR TITLE
ARTEMIS-565 Dealing with ClassLoading issues on managements. Caching …

### PR DESCRIPTION
**Pull request by clebertsuconic**
…provider loaded

### CODE REVIEW

**Comment by johnament** [comment]
What was happening prior to this change?

**Comment by clebertsuconic** [comment]
If you build and run message-count example without this fix you will see a class not found exception. 
The server is not loaded worth the appClassLoader (system class loader). And the Json is always loading the class loader thing. 

Management is using RMI and I have no control over the class loader. I would need to either do this is wrap every messaging call with setting the Tccl. 


This is the best solution I could find.  But I'm open to anything else.

**Comment by johnament** [comment]
If you don't mind, let me take a look over the weekend.  This sounds like more of an issue with the geronimo spec jar, which we can get changes into.  

https://github.com/apache/geronimo-specs/blob/trunk/geronimo-json_1.0_spec/src/main/java/javax/json/spi/JsonProvider.java#L67

**Comment by clebertsuconic** [comment]
i thought about changing JsonProvider to cache the loaded so this wouldn't be an issue (I could load it under the right class loader once)

**Comment by clebertsuconic** [comment]
Will wait for you then.

**Comment by johnament** [comment]
Mmmph.  So I can fix the spec jar for geronimo, but the problem will persist in the other spec jars, e.g. the same problem happens w/ the RI JAR and the JBoss JAR.  

Minor issue, I would do this as the loader method, to avoid casting

```
   private static JsonProvider loadProvider() {
      return AccessController.doPrivileged(new PrivilegedAction<JsonProvider>() {
         @Override
         public JsonProvider run() {
            ClassLoader originalLoader = Thread.currentThread().getContextClassLoader();
            try {
               Thread.currentThread().setContextClassLoader(JsonProvider.class.getClassLoader());
               return JsonProvider.provider();
            } finally {
               Thread.currentThread().setContextClassLoader(originalLoader);
            }
         }
      });

   }
```

**Comment by clebertsuconic** [comment]
@johnament I wouldn't need this whole thing if this was merged. Just sent the PR:

https://github.com/apache/geronimo-specs/pull/4


I"m not sure about the reasoning for loading the class every time. It seems silly to me... so I guess this PR should be an improvement. You know that project better than I do.

**Comment by johnament** [comment]
At this point, this is the best solution to ensure that it works across different impls and spec jars. +1

**Pull request merged**
