### PR TITLE
Fix missing JSON support

### PR DESCRIPTION
**Pull request by gnodet**
Not to be merged yet, as it's using a SNAPSHOT.

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
Can there be added a test case that this is fixing.

**Comment by jbertram** [comment]
It's not obvious to me what's actually being fixed here.  Also, if it's not to be merged then you should probably close the PR.

**Comment by gnodet** [comment]
Sorry, I was in vacation last week and haven't had any time to work further on that.
Artemis does use json in some cases.  The problem is that in OSGi, the json api bundle is deployed, but it can't locate any provider.  I pushed an updated spec to servicemix to fix the problem as it's usually done for this kind of spec bundles:
  https://git1-us-west.apache.org/repos/asf?p=servicemix-specs.git;a=commitdiff;h=9265f72331f26f8374765d4530522d238edeecf2
The above commit allows finding a json provider inside a bundle deployed in the OSGi framework.

So this commit deploys this new json api bundle and forces the installation of the johnzon provider.

I plan to create a test case to demonstrate the changes i've been working on, i.e. #1284, #1285 and #1286

**Comment by gnodet** [comment]
Superseded by #1307

**Pull request closed without merging**
