### PR TITLE
Restart Sequence

### PR DESCRIPTION
**Pull request by shchavan-source**
This document contains the restart sequence for the brokers under various situations.
These sequences can help to restart the brokers in a proper sequence so as to avoid the client applications to be restarted.

### CODE REVIEW

**Comment by franz1981** [comment]
I suggest to sign the apache ICLA (see https://www.apache.org/dev/new-committers-guide.html#submitting-your-individual-contributor-license-agreement-icla) and create an appropriate JIRA for this document change eg https://issues.apache.org/jira/browse/ARTEMIS-1730
The name of PR and the commit message should reflect the JIRA name to help tracking the motivation of the change :+1:

**Comment by clebertsuconic** [comment]
nice doc... it needs a JIRA

**Comment by clebertsuconic** [comment]
nice doc... it needs a JIRA

**Comment by jbertram** [comment]
IMO this belongs in the "High Availability" chapter rather than its own chapter.

**Comment by michaelpearce-gain** [comment]
@jbertram if no objections in next few hours, i will merge this, we can then move it later if wanted. I think the doc is useful

**Comment by michaelpearce-gain** [comment]
@clebertsuconic it seems this went quiet, but i think its a good contribution, to avoid issues with no Jira i have created one for it: https://issues.apache.org/jira/browse/ARTEMIS-2822

**Pull request closed without merging**
