### PR TITLE
ARTEMIS-1535 - settle delivery in same lock as sending the disposition

### PR DESCRIPTION
**Pull request by andytaylor**
https://issues.apache.org/jira/browse/ARTEMIS-1535

### CODE REVIEW

**Comment by andytaylor** [comment]
don't merge this yet

**Comment by tabish121** [comment]
Is it true that there's nothing that will be calling the IOCallback onError method?  If that isn't the case then it seems like there's a possible case here where the Declare or Discharge is never answered as in the error case no disposition or settlement is done which would leave a client dangling awaiting a response.

**Comment by andytaylor** [comment]
@clebertsuconic what do you think, should we do something in onError at least fro discharge?

**Comment by clebertsuconic** [comment]
@andytaylor are you in a hurry to merge this? if so, I will take a look later today.


But usually onError is not very useful. I will need to look at the solution closely.

**Comment by clebertsuconic** [comment]
@andytaylor @tabish121 onError isn't needed on this case... IOCriticalListener would kick in before (which is kicked after that method somewhere through the native interface on AIO).


@andytaylor I think your changes here are fine. It would be nice to see a test.. but it's fine..


I think it's ok to merge this, assuming you ran the AMQP tests on the testsuite.

**Pull request closed without merging**
