### PR TITLE
ARTEMIS-1011 Slow consumer detection after bursts

### PR DESCRIPTION
**Pull request by brusdev**
Fix slow consumer detection after a burst, taking into account messages
which are already in queue at the start of queueRateCheckTime period.

### CODE REVIEW

**Comment by brusdev** [comment]
I need to fix an error. Please do not merge.

**Comment by clebertsuconic** [comment]
@brusdev I added a Labla DO-NOT-MERGE-YET, please remove the label when you're ready.

**Comment by brusdev** [comment]
@clebertsuconic I fixed my error but I can not remove the label "DO-NOT-MERGE-YET".

**Comment by clebertsuconic** [comment]
I've fixed the issue on travis, can you please rebase:

```sh
git pull --rebase upstream master
git push origin <your-branch> -f
```

**Comment by brusdev** [comment]
rebased

**Pull request closed without merging**
