### PR TITLE
ARTEMIS-2496 Revert catch up with zero-copy, as it's causing issues i…

### PR DESCRIPTION
**Pull request by clebertsuconic**
…nto some integration usage

Revert "ARTEMIS-2336 Use zero copy to replicate journal/page/large message file"

This reverts commit 85b93f0883bc06a2dfe2de9d560805a59d626d38.

### CODE REVIEW

**Comment by franz1981** [comment]
@wy96f We are actually receiving (and sending) several 0s on the wire (via xnio on wildfly, that will wrap the replication connection as a HTTP one), that would break backup with a IIOBE:
```
2019-09-18 18:08:14,889 ERROR [org.apache.activemq.artemis.core.client] (Thread-5 (ActiveMQ-client-netty-threads)) AMQ214013: Failed to decode packet: java.lang.IndexOutOfBoundsException: readerIndex(4) + length(1) exceeds writerIndex(4): PooledUnsafeDirectByteBuf(ridx: 4, widx: 4, cap: 4)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1428)
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:723)
	at io.netty.buffer.WrappedByteBuf.readByte(WrappedByteBuf.java:521)
	at org.apache.activemq.artemis.core.buffers.impl.ChannelBufferWrapper.readByte(ChannelBufferWrapper.java:280)
	at org.apache.activemq.artemis.core.protocol.ServerPacketDecoder.decode(ServerPacketDecoder.java:126)
	at org.apache.activemq.artemis.core.protocol.core.impl.RemotingConnectionImpl.bufferReceived(RemotingConnectionImpl.java:377)
	at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl$DelegatingBufferHandler.bufferReceived(ClientSessionFactoryImpl.java:1198)
	at org.apache.activemq.artemis.core.remoting.impl.netty.ActiveMQChannelHandler.channelRead(ActiveMQChannelHandler.java:73)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at org.apache.activemq.artemis.utils.ActiveMQThreadFactory$1.run(ActiveMQThreadFactory.java:118)

2019-09-18 18:08:14,893 ERROR [org.apache.activemq.artemis.core.client] (Thread-5 (ActiveMQ-client-netty-threads)) AMQ214031: Failed to decode buffer, disconnect immediately.: java.lang.IllegalStateException: java.lang.IndexOutOfBoundsException: readerIndex(4) + length(1) exceeds writerIndex(4): PooledUnsafeDirectByteBuf(ridx: 4, widx: 4, cap: 4)
	at org.apache.activemq.artemis.core.protocol.core.impl.RemotingConnectionImpl.bufferReceived(RemotingConnectionImpl.java:390)
	at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl$DelegatingBufferHandler.bufferReceived(ClientSessionFactoryImpl.java:1198)
	at org.apache.activemq.artemis.core.remoting.impl.netty.ActiveMQChannelHandler.channelRead(ActiveMQChannelHandler.java:73)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at org.apache.activemq.artemis.utils.ActiveMQThreadFactory$1.run(ActiveMQThreadFactory.java:118)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(4) + length(1) exceeds writerIndex(4): PooledUnsafeDirectByteBuf(ridx: 4, widx: 4, cap: 4)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1428)
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:723)
	at io.netty.buffer.WrappedByteBuf.readByte(WrappedByteBuf.java:521)
	at org.apache.activemq.artemis.core.buffers.impl.ChannelBufferWrapper.readByte(ChannelBufferWrapper.java:280)
	at org.apache.activemq.artemis.core.protocol.ServerPacketDecoder.decode(ServerPacketDecoder.java:126)
	at org.apache.activemq.artemis.core.protocol.core.impl.RemotingConnectionImpl.bufferReceived(RemotingConnectionImpl.java:377)
	... 21 more
```
Just reverting this change will make it work, so would be better to work on it to see what/where is broken first

**Comment by michaelandrepearce** [comment]
Looking at the xnio the issue is before we worked on a copy, thus if xnio mutated the buffer it was safe, with zero copy now xnio is dangerously altering the buffer. Isnt the issue in xnio that its mutating a buffer without copying it?

**Comment by michaelandrepearce** [comment]
What im saying is because it was working before was by luck that we had made a copy. The issue is really we have exposed this unsafe code in xnio thats used by wildfly

**Comment by clebertsuconic** [comment]
@michaelandrepearce xnio has a wrapper using Netty libraries... it's not using any of our APIs.

but it seems the encoding is slightly off in a way that explodes in xnio, but it silently fails for us. as we test this we will probably revert this temporarily until we figure out what's going on.

**Comment by wy96f** [comment]
@clebertsuconic @franz1981 Hi, I didn't use wildfly/xnio. Will xnio use a HttpConnection which implements Connection like InVMConnection/NettyConnection?

```
         if (connection != null && connection.getTransportConnection() instanceof NettyConnection) {
            bufferSize -= dataSize;
            isNetty = true;
         }
         buffer = createPacket(connection, bufferSize);
         encodeHeader(buffer);
         encodeRest(buffer, connection);
         if (!isNetty) {
            if (buffer.byteBuf() != null && buffer.byteBuf().nioBufferCount() == 1 && buffer.byteBuf().isDirect()) {
               final ByteBuffer byteBuffer = buffer.byteBuf().internalNioBuffer(buffer.writerIndex(), buffer.writableBytes());
               readFile(byteBuffer);
            } else {
               final ByteBuf byteBuffer = PooledByteBufAllocator.DEFAULT.directBuffer(buffer.writableBytes(), buffer.writableBytes());
               try {
                  final ByteBuffer nioBuffer = byteBuffer.internalNioBuffer(0, buffer.writableBytes());
                  final int readBytes = readFile(nioBuffer);
                  if (readBytes > 0) {
                     //still use byteBuf to copy data
                     buffer.writeBytes(byteBuffer, 0, readBytes);
                  }
               } finally {
                  byteBuffer.release();
               }
            }
            buffer.writerIndex(buffer.capacity());
         }
         encodeSize(buffer, encodedSize);
         return buffer;
```
If not NettyConnection, file data will be read into buffer.

Then in ChannelImpl::send
```
connection.getTransportConnection().write(buffer);
connection.getTransportConnection().write(raf, fileChannel, offset, dataSize, callback == null ? null : (ChannelFutureListener) future -> callback.done(future == null || future.isSuccess()));
```
Both buffer and file will be written. For InVMConnection, actually no file data is transferred:
```
   @Override
   public void write(RandomAccessFile raf,
                     FileChannel fileChannel,
                     long offset,
                     int dataSize,
                     final ChannelFutureListener futureListener) {
      if (futureListener == null) {
         return;
      }
      try {
         executor.execute(() -> {
            try {
               futureListener.operationComplete(null);
            } catch (Exception e) {
               throw new IllegalStateException(e);
            }
         });
      } catch (RejectedExecutionException e) {

      }
   }
```
But if xnio implements a connection and transfers file data one more time in file send method, the mechanism is broken. Not sure if it is caused by this?

**Comment by franz1981** [comment]
@wy96f Thanks to reach out. Xnio is using https://github.com/xnio/netty-xnio-transport/blob/0.1/src/main/java/org/xnio/netty/transport/AbstractXnioSocketChannel.java#L149 that transparently would receive the flushed data into Netty ie no custom child of `Connection`

Another thing I've noticed: before the revert, `ChunkedFile` wasn't working for me...do we have tests to verify it?

**Comment by wy96f** [comment]
> Another thing I've noticed: before the revert, `ChunkedFile` wasn't working for me...do we have tests to verify it?

@franz1981 There is no test. I copied the code https://github.com/netty/netty/blob/ff7a9fa091a8bf2e10020f83fc4df1c44098bbbb/example/src/main/java/io/netty/example/file/FileServerHandler.java#L52

`ChunkedFile` will read file into bytebuf which would then be written into socket channel, https://github.com/netty/netty/blob/ff7a9fa091a8bf2e10020f83fc4df1c44098bbbb/handler/src/main/java/io/netty/handler/stream/ChunkedWriteHandler.java#L242
It should work as the operations are general. What problem did you encounter with `ChunkedFile`?

**Comment by franz1981** [comment]
@wy96f I've just run a naive test replacing FileRegion with ChunkedNioFile and it should work OOTB...but seems that netty is not reading data from it...I need to dig better into it

**Comment by wy96f** [comment]
> @wy96f I've just run a naive test replacing FileRegion with ChunkedNioFile and it should work OOTB...but seems that netty is not reading data from it...I need to dig better into it

@franz1981
I just notice `ChunkedWriteHandler` needs to be added in pipeline by using `ChunkedFile`, https://github.com/netty/netty/blob/ff7a9fa091a8bf2e10020f83fc4df1c44098bbbb/example/src/main/java/io/netty/example/file/FileServer.java#L77
It was my bad i missed this before revert. When using `ChunkedFile`(in the ssl case), exception would be thrown, https://github.com/netty/netty/blob/ff7a9fa091a8bf2e10020f83fc4df1c44098bbbb/transport/src/main/java/io/netty/channel/nio/AbstractNioByteChannel.java#L245

**Comment by clebertsuconic** [comment]
@wy96f is this really a feature you really would like to have?

- as we moved through this task, we realized the RegionFile is not actually doing zero-copy. it's using a ByteBuf just like before.

I bet there's an issue within Wildfly where the execution happens twice, and the actual move would happen on a secondary buffer or something...there's a loop within xnio capturing packets from HTTP into Netty (Wildfly has a single port for everything).

We had a few people working on it this week, this feature is getting lot of attention for little benefit.

If you really think this is a nice feature to have.. perhaps you can keep going... but as it stands I would say to keep it out!

**Pull request merged**
