### PR TITLE
ARTEMIS-1116 - added role mapper for LDAP roles to local ActiveMQ roles

### PR DESCRIPTION
**Pull request by sjhiggs**
For ARTEMIS-1116, allows configuring LDAP role mapping to local ActiveMQ roles.

### CODE REVIEW

**Comment by jbertram** [comment]
Couple of things:

- The commit message should follow the format outlined in the [Hacking Guide](https://github.com/apache/activemq-artemis/blob/master/docs/hacking-guide/en/maintainers.md#commit-messages).
- You have a fair number of checkstyle violations. See more [here](https://builds.apache.org/blue/organizations/jenkins/ActiveMQ-Artemis-PR-Build/detail/ActiveMQ-Artemis-PR-Build/2607/pipeline). You run the checkstyle stuff locally by using 'mvn -Pdev install'.
- I wonder if this feature would be better if it was more general so that it could be used with any login module rather than isolated only to the LDAP login module.  What do you think?

**Comment by jbertram** [comment]
Thanks for fixing the commit message and checkstyle issues.

The more I think about this the more I think this should be a general feature which all login modules can use rather than just the LDAP login module. In general, this functionality would only be useful for login modules pulling data from an external system like LDAP which makes it a natural fit for the LDAP login module, but other users might implement their own login module where this functionality would be useful (e.g. integrating with a legacy auth system) and I wouldn't want to require a re-implementation. Also, I think moving the configuration into broker.xml from login.config will be provide a better user experience.

From a configuration perspective this would be a good fit in <security-settings> next to <security-setting> and <security-setting-plugin>. The name <role-mapping> seems appropriate. It could have a "from" and "to" attribute where "from" is delimited with e.g. a comma.

**Comment by jbertram** [comment]
I was thinking something a bit less verbose like...

    <security-settings>
       ...
       <role-mapping to="admin" from="Administrator,amq"/>
       ...
    <security-settings>

**Comment by sjhiggs** [comment]
That's fine, I was assuming "from" was the external/LDAP role and "to" is the internal AMQ role, do you see it the opposite?

**Comment by jbertram** [comment]
> I was assuming "from" was the external/LDAP role and "to" is the internal AMQ role, do you see it the opposite?

I see the "from" was the external role and "to" is the internal Artemis role as you said.

> ...the from will probably need a different delimiter because the role name may be something like a DN.

Whatever makes sense from an implementation perspective is fine with me. I was just going on the fact that the original commit used commas as a delimiter.

**Comment by sjhiggs** [comment]
Updated - it works a little differently than I originally anticipated; a set of roles is calculated when parsing the broker.xml taking into account not only the original roles but the role mappings as well.  This commit is quite a bit more intrusive than the previous one.  Tests are included, but needs review all the same.

**Pull request closed without merging**
