### PR TITLE
ARTEMIS-1529 Fixing Ref count over asynchronous ack

### PR DESCRIPTION
**Pull request by clebertsuconic**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@tkratky I am adding the test you create through this PR.. attributing the authorship to you.

if you could review please?

**Comment by kornys** [comment]
@clebertsuconic dothese tests pass with current fixes?

**Comment by clebertsuconic** [comment]
with this fix, yes

**Comment by clebertsuconic** [comment]
please, do not merge this yet

**Comment by clebertsuconic** [comment]
it's fine now.. false alarm

**Pull request merged**
