### PR TITLE
ARTEMIS-2433 add ExternalCertificateLoginModule to surface a SASL EXT…

### PR DESCRIPTION
**Pull request by gtully**
…ERNAL identity (subjectDN) to JAAS.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
LGTM. Just a question though. would make sense to automate configuration through the CLi create? or better to keep it manual?

**Comment by gtully** [comment]
I don't think this is a candidate for the cli, the setup of jaas login config is too context specific

**Comment by gtully** [comment]
pushed an update with a rebase to resolve the conflict the ldif file

**Comment by jbertram** [comment]
@gtully, can you `rebase` and `push -f`? A defect was recently fixed that was preventing the Travis PR build from finishing properly. Thanks!

**Pull request closed without merging**
