### PR TITLE
ARTEMIS-1589 ActiveMQProtonRemotingConnection#getClientID() now returns remote client Id...

### PR DESCRIPTION
**Pull request by jostbg**
...instead of server client Id

### CODE REVIEW

**Comment by jostbg** [comment]
@jbertram Could you please check if my [observations](https://issues.apache.org/jira/browse/ARTEMIS-1589) and my trivial fix are correct. Thanks in advance!

**Comment by jbertram** [comment]
@jostbg, I'm not terribly familiar with AMQP so I can't comment with authority as to whether or not this is a good change.  @tabish121, could you perhaps take a look here?

**Comment by tabish121** [comment]
@jbertram @jostbg As far as I can see the patch looks correct, it would seem to make more sense to return the remote container ID here than the locally generated server side value as that provides more context into the remote connection.  That is of course if the getClientID API in RemotingConnection is referring to the value specified by the remote, which would make the most sense.

**Comment by jostbg** [comment]
The java doc of getClientID says "Returns the Client ID associated with this connection" which probably refers to the "client-side" ID. StompConnection for example returns the ID set by the client and not some server generated ID.

**Pull request closed without merging**
