### PR TITLE
ARTEMIS-1322 Add a ServerLocator option to ignore topology for load-balancing

### PR DESCRIPTION
**Pull request by gaohoward**
(2nd commit) Disable wait for topolocy when ignore topology for
load-balancing option is true.

### CODE REVIEW

**Comment by jbertram** [comment]
You might still want the topology for failover even if you don't want to use it for load balancing.

**Comment by gaohoward** [comment]
yes that's a problem.

**Comment by clebertsuconic** [comment]
@howardgao you would have to come up with a different implementation. I don't think we should go with this implementation.

**Comment by gaohoward** [comment]
I'm thinking of adding a similar option 'useClientFailover' to allow user to disable client side failover. If the user disable both loadbalancing and failover (as mostly useful in cloud envirnoment) then don't care about the topology waiting.

**Comment by jbertram** [comment]
@howardgao, don't we already have that option via the `ha` URL parameter? If `ha=false` then the client won't failover.

**Comment by gaohoward** [comment]
I found ha=false not quite disable the failover thing. The connection retry still looking for a backup in the topology regardless whether ha is on or off. Anyway I saw the Jira is closed. Maybe we can drop this PR?

**Pull request closed without merging**
