### PR TITLE
ARTEMIS-905 JCtools ConcurrentMap replacement

### PR DESCRIPTION
**Pull request by franz1981**
It's a total replacement of ConcurrentHasMap and ConcurrentHashSet usage with faster and lower memory footprint versions of jctools; a high performance concurrent collections library.

### CODE REVIEW

**Comment by jbertram** [comment]
Does this yield any measurable performance gains?  I'm curious about any benchmarks performed.

**Comment by ig-michaelpearce** [comment]
Out of interest why JCTools over some other libs with similar goals? Agrona, Kolobroke, GS collections, fastutil, HPPC & Trove

**Comment by franz1981** [comment]
@ig-michaelpearce Good libraries, but no one of them provide a concurrent map replacement AFAIK, this is one of the reasons behind the choice of JCtools.
In addition to that, JCtools has the fastest implementations of lock-free/wait-free queues; the next step IMHO will be to test if all the ConcurrentLinkedQueues/ArrayBlockingQueues used in Artemis could be replaced by these ones, hence we'll kill two birds with one stone (poor birds!)

**Comment by franz1981** [comment]
@jbertram I'm building some macro benchmark right know, as soon as I'll finish them I'll provide the results and metodology of the benchs :)
I suspect that I'll have to change a lil' bit the PR, just to be sure It doesn't corrupt any original behaviour...

**Comment by franz1981** [comment]
@jbertram 
I've attached the first results on [localhost.txt](https://github.com/apache/activemq-artemis/files/687370/localhost.txt).
The throughputs (end to end) are pretty the same (a lil' adavantage for the JCtools maps) and the memory footprint is similar.
What is pretty different is the latency distribution: the JCtools version deliver a more stable throughput probably due to fewer and shorter GC pauses (there are less Long and Node instances produced and collected).
The test configuration is:
- Max throughput, single queue, concurrent send and receive					
- Non-persistent messages, at-least-once delivery, auto acknowledge (JMS)					
- same machine RHEL 6.9 OpenJDK 1.8.0					
- 100000 warmup messages + 5 runs of 100000 messages					
- 100 bytes per message					
I've tested everything on the same machine with the default (AIO) persistence and the Artemis JMS client. 
It is not the typical benchmark that helps the JCtools maps to shine against the vanilla one.
I'm building a micro-benchmark to stress the journal and provides best case results too :)

**Comment by ig-michaelpearce** [comment]
@franz1981 I was just looking at the results, p50 (50%) and mean are equal so one expects these to be equal,  i notice in the results they have different values within the same test result.

**Comment by clebertsuconic** [comment]
+1 on this.

only thing is: make sure you run a full testsuite before running this.

**Comment by clebertsuconic** [comment]
@franz1981 please take a look, the build doesn't complete on this PR.

**Comment by ig-michaelpearce** [comment]
@franz1981 if all reference to ConcurrentHashSet are replaced, can the class be removed in org.apache.activemq.artemis.utils?

**Comment by franz1981** [comment]
@ig-michaelpearce Yes, are almost all replaced but I left it because of the tests that used them.
I'm evaluating if close or not the PR because even if there are (good) improvements, they are not so great if compared to the huge quantity of modifications along all the project code/tests!

**Comment by ig-michaelpearce** [comment]
@franz1981 to me it looks like a clean replacement you've done.

**Comment by ig-michaelpearce** [comment]
@franz1981 we patched the 1.x branch locally and ran this, we saw some unexpected jitter compared with 1.5.1 release. could be other 1.x code changes since 1.5.1, unfortunately cannot share result publicly but can share privately.

**Comment by franz1981** [comment]
@ig-michaelpearce No problem, I'll be more than happy to check it out and try to understand what could be happened; my personal email is on the GitHub profile

**Comment by clebertsuconic** [comment]
@franz1981 can you either rework this or close it?

**Comment by franz1981** [comment]
@clebertsuconic yes!

**Pull request closed without merging**
