### PR TITLE
ARTEMIS-274 ActiveMQThreadFactory has to be constructed within doPriv…

### PR DESCRIPTION
**Pull request by istudens**
…ileged block

https://issues.apache.org/jira/browse/ARTEMIS-274

This fix is related to 
https://issues.jboss.org/browse/WFLY-5166
https://issues.jboss.org/browse/JBEAP-814

### CODE REVIEW

**Comment by clebertsuconic** [comment]
I will merge this, but i will first ammend the checkstyle issue, and the change I asked here...

I will run the entire testsuite first.. so it will take me 1 hour before I can merge this.

**Comment by istudens** [comment]
It most likely can be simplified as you pointed out. I was following the WildFly code where it was done exactly as I did and I was not sure if it was done this way for a good reason or not. David Lloyd might know more. It partially came out of his (untracked in jira) change in JBossThreadFactory. 
Feel free to change it.

**Comment by istudens** [comment]
Hopefully there is no checkstyle issue in my fix. I converted my IDE settings to 3-spaces for working with Artemis project.

**Comment by clebertsuconic** [comment]
There was one checkstyle issue.. but I fixed here.

You could double check it by using the -Pdev profile

```sh
mvn install -Pdev install -DskipTests=true
```

**Comment by istudens** [comment]
Ah, thanks. I will do it better next time ;)

**Pull request closed without merging**
