### PR TITLE
ARTEMIS-1348 Support LVQ for AMQP

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Add support for LVQ, using the same property key as core "_AMQ_LVQ_NAME"
Add test case for AMQP LVQ.

### CODE REVIEW

**Comment by tabish121** [comment]
This approach has a couple of negatives going for it.  

First the use of application properties for message handling directives now requires that every incoming message will have to decode that section of the message where previously the broker attempted to not do so unless needed as there is significant overhead in the decode.

Second the LVQ property applied to the sent message is now carried on the outbound message which may confuse those who aren't expecting that property in the messages received, I think the core JMS client filters these out in getPropertyNames JMS APIs but I could be wrong, Qpid JMS certainly would not.  In any case it's odd that a routing directive is propagate all the way to the receiving client, these sorts of things are known to cause issues when the message is retransmitted or hops around a broker network.  

This would be better slotted in as a Message Annotation or maybe even a Delivery Annotation, would need some more thought to determine which is the right place.   In general the Application Properties of an AMQP message do not carry directives for the peer.

**Comment by michaelandrepearce** [comment]
@tabish121 

On point 1:
This only is queried (and parsed) if the address is configured for LVQ. I believe on QPID java broker it is set in the same place (application properties).

On point 2:
It it is carried over also on Core so id disagree a bit on this.

**Comment by clebertsuconic** [comment]
The reason I didn't implement it was the reason @tabish121 mentioned.. there's a proper way to do that with AMQPMessage (some property I don't remember now).

**Comment by michaelandrepearce** [comment]
There is the  _properties section (but these are predefined in qpid (org.apache.qpid.proton.amqp.messaging.Properties). e.g. you cannot add to this section as far as i can tell.

**Comment by michaelandrepearce** [comment]
As i dig through this, it seems the only option if using QPID JMS wrapper without making that vendor specific (aka that i think should remain agnostic to artemis), is to use application properties. It seems there is no dynamic way for telling it that a specific property should be in message annotations instead of application properties. (unless I'm missing something) 

So as it stands I'm struggling to see any better way for now.

**Comment by clebertsuconic** [comment]
I guess if the parse properties only happens inside the last value queue it will be ok.  I had tried to only parse properties when  needed. E.g. Filters.

**Comment by michaelandrepearce** [comment]
So I can confirm the method on interface Message.getLastValueProperty is only invoked by LastValueQueue.

**Comment by michaelandrepearce** [comment]
Added to test case to check the property in JMS is the consumed message. 
Added to test case for it to check the behaviour is identical to Core protocol
Lastly also I have updated the test case to check cross compatibility with core protocol also, e.g. produce with core, consume with amqp and vice versa. So as a user using JMS clients what you get is identical either side.

**Pull request merged**
