### PR TITLE
ARTEMIS-1737 fix for inaccessible slave console after failover

### PR DESCRIPTION
**Pull request by stanlyDoge**
Can anybody review this? I will try to write some tests meanwhile. Thank you.

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
Is this on fail back to master? With restart enabled?

If so shouldn’t the console be in the restarting logic with the other components?

**Comment by stanlyDoge** [comment]
Yes, it is. I used this conf: https://pastebin.com/2G0c341X
If I am not wrong, restaring logic is implemented as [this](https://github.com/apache/activemq-artemis/blob/master/artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/SharedNothingLiveActivation.java#L194).
I am not sure if it would be ok to iterate all ExternalComponents here and if it is web one, just start it again. What do you think?

**Comment by michaelandrepearce** [comment]
@stanlyDoge its not just the console affected. the root cause of the issue you are seeing was that actually fail() method called prior to your change used to have the isExit flag to false, there are actually a few places that can be invoked as well, as such whilst the negative effect of this change that ive called out, is most visible with the console, there are more serious bits seen that also look like they're affected such as Network Pinger. 

This really needs to have @clebertsuconic look over his original change, as it seems that it is what caused this, also others in my opinion. And any fix needs to not just care about the console.

**Comment by stanlyDoge** [comment]
Ah, I see. Yeah, it seem to be changed in [ARTEMIS-1440](https://issues.apache.org/jira/browse/ARTEMIS-1440). @clebertsuconic can you take a look?

**Comment by michaelandrepearce** [comment]
@stanlyDoge nice test though!! What ever the fix worth making sure it gets added in :)

**Comment by clebertsuconic** [comment]
I'm running the testsuite... I will merge a modified patch.. thanks a lot @stanlyDoge

**Comment by michaelandrepearce** [comment]
@clebertsuconic i assume you will PR your modifications before merge.

**Comment by clebertsuconic** [comment]
@michaelandrepearce will do.. I thought I would be able to do it tonight... I'm hitting another issue.. so it will be tomorrow.

**Pull request closed without merging**
