### PR TITLE
ARTEMIS-1661 Support splitting of broker.xml

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Support XML standard XInclude thus allowing splitting of the broker.xml
Added test cases with split out config using include.

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
just rebased.

**Comment by gaohoward** [comment]
@michaelandrepearce do you think we should add some documentation for this feature?

**Comment by adirubin** [comment]
Hi michaelandrepearce, thanks!
If I'm not mistaken, the server won't monitor the x-included files for changes, which could be a problem.

**Comment by michaelandrepearce** [comment]
@adirubin thats correct, you'll need to "touch" the broker.xml file still, this is very similar to the support  for config modularity such as log4j e.g. there also you need to "touch" the log4j.xml still.

**Comment by michaelandrepearce** [comment]
@gaohoward Updated docs 👍

**Comment by gaohoward** [comment]
@adirubin good point. I'm going to merge this and improve it in a separate commit.

**Comment by michaelandrepearce** [comment]
@gaohoward you on IRC? want to sync up / chat to avoid duplicating effort.

**Pull request merged**
