### PR TITLE
[ARTEMIS-1958] Artemis may not be able to delete pages when there are some empty page files

### PR DESCRIPTION
**Pull request by morefuntang**

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
Test case needed to

recreate the issueconfirm the fixavoid regression

**Comment by morefuntang** [comment]
Thank you for reminding, Already modified according to your opinion

**Comment by wy96f** [comment]
We've encountered same problem. Live server will force another page when backup server connects to live server. If zero size page is generated at first and at last, page files would not clean up even if all messages have been consumed.

**Comment by clebertsuconic** [comment]
@morefuntang are you sure you want your commit authored as 17103355 <17103355@cnsuning.com> ?

**Pull request closed without merging**
