### PR TITLE
ARTEMIS-1108: Removed AIOFileLockManager

### PR DESCRIPTION
**Pull request by bgutjahr**
AIOFileLockManager doesn't work on NFS-mounted shared store directories. Since the GFS2 bug https://bugzilla.redhat.com/show_bug.cgi?id=678585 has been fixed end of 2011, the class AIOFileLockManager is no longer needed and I have removed it.

	deleted:    artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/AIOFileLockNodeManager.java
	modified:   artemis-server/src/main/java/org/apache/activemq/artemis/core/server/impl/ActiveMQServerImpl.java
	modified:   artemis-server/src/test/java/org/apache/activemq/artemis/tests/util/ColocatedActiveMQServer.java
	modified:   tests/unit-tests/src/test/java/org/apache/activemq/artemis/tests/unit/core/server/impl/FileLockTest.java

### CODE REVIEW

**Comment by jbertram** [comment]
Have you actually tested this change on a GFS2 file-system to ensure fail-over happens as expected?

**Comment by bgutjahr** [comment]
No, I didn't actually test it with GFS2. I just based my change on the fact that the GFS2 bug 678585 has been closed as fixed in 2011, and that I using fcntl is typically recommended. Also it looks like NIO uses fcntl, so I would guess that NIO also didn't work with that GFS2 bug. I can try setting up a GFS2 file-system, but I haven't done it before. This would probably take at least a few days, maybe next week.

**Comment by clebertsuconic** [comment]
No, NIO wouldn't work with GFS2, we were recommending libaio with GFS2.

I would need to verify this works with GFS2 before we can merge it.

**Comment by bgutjahr** [comment]
I have now setup a GFS2 file system, shared between 2 nodes (with CentOS 6.9, gfs2-utils-3.0.12.1, most according to this description: https://hungred.com/how-to/setup-gfs2-gfs-linux-centos/). HA failover from life to backup server worked well multiple times.
BTW: it also worked with NIO. Initially NIO was used because libartemis-native-64.so version 1.5.4, which I got from mvnrepository.com, has a dependency to glibc-1.14. But CentOS 6 has glibc-1.12, so the library wasn't loaded and Artemis fell back to NIO. I had to compile the library on CentOS 6 to get AIO working.
Nevertheless, this was just a quick test that the failover worked. I have no idea how/where the GFS2 bug affected Artemis.

**Comment by clebertsuconic** [comment]
@bgutjahr I'm happy to let this locker go if locking works now.

This was a hack to go around the GFS2 bug. Now it can go freely 👍

**Pull request closed without merging**
