### PR TITLE
ARTEMIS-1289 Fix: Unable to configure queues containing "/" in broker.xml

### PR DESCRIPTION
**Pull request by michaelandrepearce**

### CODE REVIEW

**Comment by mtaylor** [comment]
@michaelandrepearce Thanks for this.

Any chance you could make the queue ID unique.

e.g.

```xml 
   <element name="addresses"...
        <xs:unique name="UniqueQueueName">
            <xs:selector xpath="address/*/queue/@name" />
            <xs:field xpath="@name" />
        </xs:unique>
    </element>
```

**Comment by mtaylor** [comment]
Actually, you could add this to the core element instead.  That means it would work for the 1.x way of defining queues.

**Comment by michaelandrepearce** [comment]
@mtaylor as discussed in IRC, few comments i would have.

- Address is currently xsd:string already (this is just following suit)

- Duplicate declaration is checked anyhow on config load, do we really need a complex schema? as we don't do this on address and the same applies, that it must be unique.

- Queues can be declared in two places it seems according to the xsd, either within an address, or within the queues section, as such an unique field within one element would not capture where it could be defined in two separate places.

**Comment by mtaylor** [comment]
@michaelandrepearce OK I think these are fair points.  I'll go ahead and merge this.

**Pull request closed without merging**
