### PR TITLE
ARTEMIS-1397 Removing Netty Copied classes

### PR DESCRIPTION
**Pull request by clebertsuconic**
instead of duplicating a buffer from Netty, this will use an existing Wrapped Unpooled Buffer
Which will in turn use Unsafe Properly.

### CODE REVIEW

**Comment by clebertsuconic** [comment]
@michaelandrepearce  / @franz1981  I don't really see much gain on saving the ByteBuf instance. Maybe page.write would create a few more instances.. but I doubt it would really matter here.

I would rather accept the little weight caused then having to maintain Unsafe just for that.

**Comment by clebertsuconic** [comment]
@michaelandrepearce this is following up after #1561

**Comment by clebertsuconic** [comment]
@michaelandrepearce fancy doing your first merge?

**Comment by michaelandrepearce** [comment]
@clebertsuconic yup lets, step me through the process, good chance to learn.

**Comment by michaelandrepearce** [comment]
@clebertsuconic just for record, i don't have issue with the class @franz1981 made, its more the very recent change that brought in the UnsafeByteBufUtil.java just so they could move package, for OSGI. Id much rather if that class is needed we request Netty to make its method public.

**Comment by clebertsuconic** [comment]
@michaelandrepearce I think the right thing is to use the Netty Buffer Like I am doing now... reusing the instance.. just to call wrap.. not even Netty guys mind about that...

If we really need it.. we could maybe convince Netty guys to provide a wrap method on a buffer, so we could always reuse the same instance.

**Comment by franz1981** [comment]
@clebertsuconic @michaelandrepearce  the reason behind that class was to have more stable latencies on hot paths with no data-sync enabled: if not reused it creates a big amount of garbage when you have bursts of writes.
With data-sync it won't make a big difference if you don't have a very fast disk...
Anyway I trust your the decision about it guys :)

**Comment by michaelandrepearce** [comment]
@franz1981 i agree with you, any chance we can get netty guys, to either take your class, or to get netty to make the methods you use in UnsafeByteBufUtil set to public? So we don't have to have a full copy of UnsafeByteBufUtil in artemis just to sort some OSGI issue?

**Comment by clebertsuconic** [comment]
@franz1981  we can have it back.. just would need to have it properly at Netty exposed.. either have your class, a super class we can easily extend.. or whatever is needed.

**Comment by franz1981** [comment]
@clebertsuconic @michaelandrepearce I've just posted on Netty's gitter what we have on Artemis, to see if there is any chance to have it directly on Netty (I will do the PR if I'll receive positive feedbacks) :+1:

**Comment by michaelandrepearce** [comment]
@franz1981 +100 thanks for doing that really appreciated it’s a good feature.

**Pull request merged**
