### PR TITLE
Fix javadoc warnings

### PR DESCRIPTION
**Pull request by gaohoward**

### CODE REVIEW

**Comment by gaohoward** [comment]
few more fixes (using java 1.8)

**Comment by clebertsuconic** [comment]
javadoc still fails.

Tried with your branch and if you perform these commands:

```sh
$ cd tests/activemq5-unit-tests/
$ mvn javadoc:javadoc
```


you would get this error output:

```
2 errors
1 warning
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.098 s
[INFO] Finished at: 2015-07-09T12:16:49-04:00
[INFO] Final Memory: 23M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9:javadoc (default-cli) on project activemq5-unit-tests: An error has occurred in JavaDocs report generation:
[ERROR] Exit code: 1 - /work/apache/six/tests/activemq5-unit-tests/src/main/java/org/apache/activemq/broker/region/policy/PolicyMap.java:52: error: unknown tag: org.apache.xbean.ElementType
[ERROR] * @org.apache.xbean.ElementType class="org.apache.activemq.broker.region.policy.PolicyEntry"
[ERROR] ^
[ERROR] /work/apache/six/tests/activemq5-unit-tests/src/main/java/org/apache/activemq/broker/region/policy/PolicyMap.java:54: warning: no @param for entries
[ERROR] public void setPolicyEntries(List entries)
[ERROR] ^
[ERROR] /work/apache/six/tests/activemq5-unit-tests/src/main/java/org/apache/activemq/broker/region/policy/PolicyMap.java:31: error: unknown tag: org.apache.xbean.XBean
[ERROR] * @org.apache.xbean.XBean
[ERROR] ^
[ERROR] 
[ERROR] Command line was: /Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/work/apache/six/tests/activemq5-unit-tests/target/site/apidocs' dir.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```


I don't mind about warnins on this case.. I just wanted javadoc to be buildable.

**Comment by gaohoward** [comment]
strange I didn't get the error on my machine. I'll find out.

**Comment by gaohoward** [comment]
hmm, now I just get the error. probably I missed something. sorry I'll fix that.

**Comment by gaohoward** [comment]
I didn't run it after rebase so those errors were missed.

**Comment by gaohoward** [comment]
I'll combine the two commits into one.

**Pull request merged**
