### PR TITLE
ARTEMIS-2044 Add onSendError, onMessageRouteError to broker plugin

### PR DESCRIPTION
**Pull request by calohmn**
This fixes [ARTEMIS-2044](https://issues.apache.org/jira/browse/ARTEMIS-2044).

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
LGTM, just would change the method names to on....Exception as its an exception being caught, and follows naming of other bits e.g. onException in JMS spec, CompletionListener

**Comment by calohmn** [comment]
Ok, I've renamed the methods and amended the commit.

**Comment by cshannon** [comment]
Adding exception callbacks seems good to me, one thing I noticed is a lot of white space changes. My guess is your IDE is set to use tabs instead of spaces so I would fix that before merging

**Comment by calohmn** [comment]
@cshannon Do you mean the changes in `PostOfficeImpl` and `ServerSessionImpl`? 
The added whitespace there is because of a new try-catch block in each class, adding indentation to the lines moved into that block.
And it's all added spaces there, no tabs. IDE is also configured to use spaces (setting coming from the imported artemis-codestyle).

**Comment by cshannon** [comment]
@calohmn - ah ok, yeah that makes sense I didn't look closely enough so if it's spaces then all should be good

**Comment by michaelandrepearce** [comment]
Looks like the failed build in this pr is just travis, being its normal self.

I created a branch of this and caused a new build https://github.com/apache/activemq-artemis/pull/2268 and it passed. 

As such ill look to merge soon

**Pull request closed without merging**
