### PR TITLE
ARTEMIS-149 Advisory Message Support

### PR DESCRIPTION
**Pull request by gaohoward**
Adding functions to send advisory messages.

### CODE REVIEW

**Comment by gaohoward** [comment]
Can you take a look @clebertsuconic ? Thanks.

**Comment by clebertsuconic** [comment]
I need your help with something.. right now I can't include the activemq-tests on the PRs because they are using invalid javadocs.. do you think you could fix that? remove the javadocs?

**Comment by gaohoward** [comment]
do you mean remove the javadocs in every java file in amq5 tests? I can do that.

**Comment by clebertsuconic** [comment]
No.. just some XDoclets that are breaking the build..


use mvn javadoc:javadoc on the folder and you will understand

**Comment by gaohoward** [comment]
btw I only get 6 warnings running mvn javadoc:javadoc. I'll fix those warnings anyway.

**Pull request closed without merging**
