### PR TITLE
new logging.properties and trace format

### PR DESCRIPTION
**Pull request by clebertsuconic**

### CODE REVIEW

**Comment by clebertsuconic** [comment]
I find this tracing format easier to read (especially when going through actual traces.log).


To see if you like it, make the following change on the main pom, and run a test through Idea:

**/logging.properties.traces**


** Idea will follow whatever change you make here. I'm not sure about Eclipse, but you can make a similar tweak on Eclipse to refer the traces.

```
      <activemq-surefire-argline>-Djava.util.logging.manager=org.jboss.logmanager.LogManager
         -Dlogging.configuration="file:${activemq.basedir}/tests/config/logging.properties.traces"
         -Djava.library.path="${activemq.basedir}/artemis-native/bin" -Djgroups.bind_addr=localhost -Dorg.apache.activemq.artemis.api.core.UDPBroadcastEndpointFactory.localBindAddress=localhost
         -Djava.net.preferIPv4Stack=true
      </activemq-surefire-argline>

```

**Comment by clebertsuconic** [comment]
If everyone usually working on this branch could review it please?

**Comment by jbertram** [comment]
IMO it's a bit verbose for normal test logging, but I can see how it might be useful for actual traces.

**Comment by clebertsuconic** [comment]
@jbertram  we may change just the .traces... I have been finding it more useful to read through as it gets more visual.

**Comment by mtaylor** [comment]
+1 on changing just the trace log format (if possible).

**Comment by clebertsuconic** [comment]
@mtaylor/@jbertram  I have added the thread to the current format with minimal changes...

and I have a format commented out on traces that I will usually switch to (and which I encourage people to use when over-using traces).

**Pull request closed without merging**
