### PR TITLE
ARTEMIS-3790 Support masked JMS credentials

### PR DESCRIPTION
**Pull request by ryan-highley**
Adds standard username and password value unmasking for JMS ActiveMQConnection instances and its subclasses

### CODE REVIEW

**Comment by jbertram** [comment]
My only concern here is that there's no way to set the codec. It is hard-coded to use the default coded. I think the simplest way to implement codec configuration is via a new property on `org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory` much like `deserializationWhiteList` so that the value could be set programmatically or via the connection URL. For example, if you created a `String` named `passwordCodec` then this could be set using `ActiveMQConnectionFactory.setPasswordCodec` or, e.g., something like `tcp://myHost:61616?passwordCodec=com.foo.Codec`. Then any encrypted credentials used on connections created from this connection factory would use that codec.

**Comment by jbertram** [comment]
@ryan-highley, any feedback here?

**Comment by ryan-highley** [comment]
@jbertram Sorry for the delay--day job and all....

That makes sense. I was attempting to move the unmasking with as little invasiveness as possible, hence the additional properties and unmask calls in the ActiveMQConnection constructor.

Looking at the `o.a.a.a.jms.client.ConnectionFactoryOptions` for how `deserializationWhiteList` is implemented led me to the equivalent unmasking approach in the resource adapter, which handles the `passwordCodec` property in its ConnectionFactory as you described.

I'll update this code to enable setting the codec aligning with the precedent in the RA code.

**Comment by jbertram** [comment]
@ryan-highley, no worries. I just didn't want this to fall completely off our radar. Your next steps sounds good. I'll review again once you push. Thanks!

**Comment by jbertram** [comment]
@ryan-highley, nice work! Thanks a lot.

**Pull request merged**
